// <auto-generated />
namespace SG_SST.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ampliar_Tipo_Documento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ampliar_Tipo_Documento));
        
        string IMigrationMetadata.Id
        {
            get { return "201706191517401_Ampliar_Tipo_Documento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
