// <auto-generated />
namespace SG_SST.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cambiomodelrequisitoslegalestablas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambiomodelrequisitoslegalestablas));
        
        string IMigrationMetadata.Id
        {
            get { return "201707081707408_cambiomodelrequisitoslegalestablas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
