// <auto-generated />
namespace SG_SST.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_tbl_plan_empresa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_tbl_plan_empresa));
        
        string IMigrationMetadata.Id
        {
            get { return "201707102337397_create_tbl_plan_empresa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
