namespace SG_SST.Models.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cu_algoritmo_software : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Tbl_ComunicadosAdjutos",
                c => new
                    {
                        pk_id_comadjunto = c.Int(nullable: false, identity: true),
                        nombre = c.String(),
                        entidad = c.String(),
                        descripcion = c.String(),
                        fecha = c.String(),
                        adjunto = c.String(),
                        requiere = c.String(),
                        respuesta = c.String(),
                        tipo = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_comadjunto);
            
            CreateTable(
                "dbo.Tbl_Eme_AnalisisRiesgo",
                c => new
                    {
                        pk_id_analisisriesgo = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        fk_id_identamenaza = c.Int(nullable: false),
                        bo_intervencion = c.Boolean(nullable: false),
                        plan_de_accion = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_analisisriesgo);
            
            CreateTable(
                "dbo.Tbl_Eme_Bd_Externa",
                c => new
                    {
                        pk_id_bd_externa = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        entidad = c.String(),
                        direccion = c.String(),
                        telefono = c.String(),
                        nombre_contacto = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_bd_externa);
            
            CreateTable(
                "dbo.Tbl_Eme_bd_Interna",
                c => new
                    {
                        pk_id_bd_interna = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        nombre = c.String(),
                        numdocumento = c.String(),
                        genero = c.String(),
                        eps = c.String(),
                        rh = c.String(),
                        contacto_nombre = c.String(),
                        contacto_telefono = c.String(),
                        contacto_parentesco = c.String(),
                        requiere_manejo = c.String(),
                        cual_manejo = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_bd_interna);
            
            CreateTable(
                "dbo.Tbl_Eme_CaracteristicasInstalacion",
                c => new
                    {
                        pk_id_cinstalaciones = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        ventilacion_mecanica = c.String(),
                        ascensores = c.String(),
                        sotanos = c.String(),
                        red_hidraulica = c.String(),
                        transformadores = c.String(),
                        plantas_electricas = c.String(),
                        escaleras = c.String(),
                        zonas_parqueo = c.String(),
                        areas_especiales = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_cinstalaciones);
            
            CreateTable(
                "dbo.Tbl_Eme_DescripcionOcupacion",
                c => new
                    {
                        pk_id_descocupacion = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        trabajadores_cantidad = c.String(),
                        trabajadores_hdesde = c.String(),
                        trabajadore_hhasta = c.String(),
                        contratista_cantidad = c.String(),
                        contratista_hdesde = c.String(),
                        contratista_hhasta = c.String(),
                        visitante_cantidad = c.String(),
                        visitante_hdesde = c.String(),
                        visitantte_hhasta = c.String(),
                        cliente_cantidad = c.String(),
                        cliente_hdesde = c.String(),
                        cliente_hhasta = c.String(),
                        bo_tratamiento_especial = c.Boolean(nullable: false),
                        cual = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_descocupacion);
            
            CreateTable(
                "dbo.Tbl_Eme_Elementos",
                c => new
                    {
                        pk_id_elementos = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        estructurales_descripcion = c.String(),
                        estructurales_ubicacion = c.String(),
                        equipos_descripcion = c.String(),
                        equipos_ubicacion = c.String(),
                        insumos_descripcion = c.String(),
                        insumos_ubicacion = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_elementos);
            
            CreateTable(
                "dbo.Tbl_Eme_EsquemaOrganizacional",
                c => new
                    {
                        pk_id_esquemaorganizacional = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        esquema_img = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_esquemaorganizacional);
            
            CreateTable(
                "dbo.Tbl_Eme_FrentesAccion",
                c => new
                    {
                        pk_id_frenteaccion = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        plan_seguridadfisica = c.String(),
                        plan_primerosaux = c.String(),
                        plan_contraincendios = c.String(),
                        plan_eval_pdf = c.String(),
                        nombrecoordinador = c.String(),
                        objetivos = c.String(),
                        estructura = c.String(),
                        proc_coordinacion = c.String(),
                        proc_internos = c.String(),
                        proc_externos = c.String(),
                        mecanismos_alarma = c.String(),
                        rutas_evac_pdf = c.String(),
                        simulacros = c.String(),
                        instructivo_evacuacion = c.String(),
                        proc_retorno = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_frenteaccion);
            
            CreateTable(
                "dbo.Tbl_Eme_Generalidades",
                c => new
                    {
                        pk_id_generalidades = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        objetivos = c.String(),
                        alcance = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_generalidades);
            
            CreateTable(
                "dbo.Tbl_Eme_Georeferenciacion",
                c => new
                    {
                        pk_id_georeferenciacion = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        interno_img = c.String(),
                        bo_externo = c.Boolean(nullable: false),
                        bo_colegio = c.Boolean(nullable: false),
                        bo_iglesia = c.Boolean(nullable: false),
                        bo_comercial = c.Boolean(nullable: false),
                        bo_centro_atencion = c.Boolean(nullable: false),
                        bo_parque = c.Boolean(nullable: false),
                        bo_otro = c.Boolean(nullable: false),
                        cual = c.String(),
                        punto_encuentro_img = c.String(),
                        ubicacion_hidrantes_img = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_georeferenciacion);
            
            CreateTable(
                "dbo.Tbl_Eme_InfoGeneral",
                c => new
                    {
                        pk_id_infogeneral = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        razon_social = c.String(),
                        identificacion_sede = c.String(),
                        direccion_sede = c.String(),
                        telefono_sede = c.String(),
                        correo_electronico = c.String(),
                        departamento_sede = c.String(),
                        municipio_sede = c.String(),
                        lindero_norte = c.String(),
                        lindero_sur = c.String(),
                        lindero_oriente = c.String(),
                        lindero_occidente = c.String(),
                        acceso_principales = c.String(),
                        acceso_alternas = c.String(),
                        actividad_economica = c.String(),
                        representante = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_infogeneral);
            
            CreateTable(
                "dbo.Tbl_Eme_NivelEmergencia",
                c => new
                    {
                        pk_id_nivelemergencia = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        nivel = c.String(),
                        emergencia = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_nivelemergencia);
            
            CreateTable(
                "dbo.Tbl_Eme_PlanAyuda",
                c => new
                    {
                        pk_id_planayuda = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        empresa = c.String(),
                        recurso = c.String(),
                        compensacion = c.String(),
                        reintegro = c.String(),
                        nombre_contacto = c.String(),
                        telefono_contacto = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_planayuda);
            
            CreateTable(
                "dbo.Tbl_Eme_ProcOpera_Normalizados",
                c => new
                    {
                        pk_id_proc_normalizados = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        nombre_proc = c.String(),
                        responsable = c.String(),
                        proc_antes = c.String(),
                        proc_durante = c.String(),
                        proc_despues = c.String(),
                        proc_recursos = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_proc_normalizados);
            
            CreateTable(
                "dbo.Tbl_Eme_RecursosHumanos",
                c => new
                    {
                        pk_id_recursosh = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        bpaux_nombre = c.String(),
                        bcontra_nombre = c.String(),
                        bevalresc_nombre = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_recursosh);
            
            CreateTable(
                "dbo.Tbl_Eme_RecursosTecnicos",
                c => new
                    {
                        pk_id_recursostecnicos = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        tipo = c.String(),
                        cantidad = c.String(),
                        ubicacion = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_recursostecnicos);
            
            CreateTable(
                "dbo.Tbl_Eme_Roles",
                c => new
                    {
                        pk_id_roles = c.Int(nullable: false, identity: true),
                        fk_id_sede = c.Int(nullable: false),
                        nombre = c.String(),
                        antes = c.String(),
                        durante = c.String(),
                        despues = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_roles);
            
            CreateTable(
                "dbo.Tbl_GruposComunicaciones",
                c => new
                    {
                        pk_id_grupo = c.Int(nullable: false, identity: true),
                        NombreGrupo = c.String(),
                    })
                .PrimaryKey(t => t.pk_id_grupo);
            
            CreateTable(
                "dbo.Tbl_GrupoUsuariosComunicaciones",
                c => new
                    {
                        pk_id_grupo_usuario_comunicaciones = c.Int(nullable: false, identity: true),
                        fk_id_grupo_comunicaciones = c.Int(nullable: false),
                        nombre_contacto = c.String(),
                        email = c.String(),
                        Status = c.Boolean(nullable: false),
                    })
                .PrimaryKey(t => t.pk_id_grupo_usuario_comunicaciones);
            
            CreateTable(
                "dbo.Tbl_IncidentesEL",
                c => new
                    {
                        PK_Incidentes_EL = c.Int(nullable: false, identity: true),
                        EnfLabCalificadaI = c.String(),
                        FechaInvestigacionI = c.String(),
                        DepartamentoI = c.String(),
                        MunicipioI = c.String(),
                        DireccionI = c.String(),
                        NombresApellidosI = c.String(),
                        ProfesionalI = c.String(),
                        NoLicenciaI = c.String(),
                        FotografiasI = c.String(),
                        IlustracionesI = c.String(),
                        DiagramasI = c.String(),
                        OtrosCualesI = c.String(),
                        EmpleadorII = c.String(),
                        ContratanteII = c.String(),
                        IndependienteII = c.String(),
                        CooperativaII = c.String(),
                        AgremiacionII = c.String(),
                        AsociacionII = c.String(),
                        CodActividadII = c.String(),
                        ActividadPrincipalII = c.String(),
                        RazonSocialII = c.String(),
                        TipoIdentificacionII = c.String(),
                        NumIdentificacionII = c.String(),
                        DireccionPrincipalII = c.String(),
                        TelefonoPpalII = c.String(),
                        FaxII = c.String(),
                        DeptoPpalII = c.String(),
                        McpioPpalII = c.String(),
                        EmailII = c.String(),
                        ZonaPpalII = c.String(),
                        CentroTrabajoPpalII = c.String(),
                        CentroCostoTelefonoII = c.String(),
                        CentroCostoFaxII = c.String(),
                        CodActEconoPpalII = c.String(),
                        ActEconoCentroTrabajoII = c.String(),
                        DeptoEmpleadorII = c.String(),
                        McpioEmpleadorII = c.String(),
                        EmailEmpleadorII = c.String(),
                        ZonaEmpleadorII = c.String(),
                        DeptoCentroTrabajoII = c.String(),
                        McpioCentroTrabajoII = c.String(),
                        PlantaIII = c.String(),
                        MisionIII = c.String(),
                        CooperadorIII = c.String(),
                        EstudianteIII = c.String(),
                        IndependienteIII = c.String(),
                        TipoIdentificacionIII = c.String(),
                        NumIdentificacionIII = c.String(),
                        PrimerApellidoIII = c.String(),
                        SegundoApellidoIII = c.String(),
                        PrimerNombreIII = c.String(),
                        SegundoNombreIII = c.String(),
                        FechaNacimientoIII = c.String(),
                        SexoIII = c.String(),
                        EPSAfiliadoIII = c.String(),
                        AFPAfiliadoIII = c.String(),
                        ARLAfiliadoIII = c.String(),
                        TelefonoIII = c.String(),
                        FaxIII = c.String(),
                        EmailTrabajadorIII = c.String(),
                        DireccionTrabajadorIII = c.String(),
                        ZonaIII = c.String(),
                        CargoIV = c.String(),
                        AntiguedadCargoAIV = c.String(),
                        AntiguedadCargoMIV = c.String(),
                        CodOcupacionIV = c.String(),
                        OcupacionHabitualIV = c.String(),
                        FechaMuerteIV = c.String(),
                        AreaActualIV = c.String(),
                        NombreCargoIV = c.String(),
                        AntiguedadCargoAnioIV = c.String(),
                        AntiguedadCargoMesesIV = c.String(),
                        DiurnoIV = c.String(),
                        NocturnoIV = c.String(),
                        MixtoIV = c.String(),
                        TurnosIV = c.String(),
                        CondicionesPuestoTrabajoIV = c.String(),
                        TareasCargo1IV = c.String(),
                        DedicacionJL1IV = c.String(),
                        DedicacionJL11IV = c.String(),
                        DedicacionJL12IV = c.String(),
                        RelacionMuyProbable1IV = c.String(),
                        RelacionProbable1IV = c.String(),
                        RelacionPocoProbable1IV = c.String(),
                        DedicacionJL21IV = c.String(),
                        DedicacionJL22IV = c.String(),
                        DedicacionJL23IV = c.String(),
                        RelacionMuyProbable2IV = c.String(),
                        RelacionProbable2IV = c.String(),
                        RelacionPocoProbable2IV = c.String(),
                        TareasCargo3IV = c.String(),
                        DedicacionJL31IV = c.String(),
                        DedicacionJL32IV = c.String(),
                        DedicacionJL33IV = c.String(),
                        RelacionMuyProbable3IV = c.String(),
                        RelacionProbable3IV = c.String(),
                        RelacionPocoProbable3IV = c.String(),
                        TareasCargo4IV = c.String(),
                        DedicacionJL41IV = c.String(),
                        DedicacionJL42IV = c.String(),
                        DedicacionJL43IV = c.String(),
                        RelacionMuyProbable4IV = c.String(),
                        RelacionProbable4IV = c.String(),
                        RelacionPocoProbable4IV = c.String(),
                        FormacionInformacionIV = c.String(),
                        ProteccionColectivaIV = c.String(),
                        EPPIV = c.String(),
                        DiseñoPuestoTrabajoIV = c.String(),
                        OrganizacionTrabajoIV = c.String(),
                        PreventivasIV = c.String(),
                        ImplementadasIV = c.String(),
                        DescripcionIV = c.String(),
                        CodigoCie1 = c.String(),
                        CodigoCie2 = c.String(),
                        CodigoCie3 = c.String(),
                        CodigoCie4 = c.String(),
                        DiagnosticoIV1 = c.String(),
                        DiagnosticoIV2 = c.String(),
                        DiagnosticoIV3 = c.String(),
                        DiagnosticoIV4 = c.String(),
                        FechaOrigenELV = c.String(),
                        OrigenLaboralIV = c.String(),
                        NoTrabajadoresV = c.String(),
                        CargosSimilaresV = c.String(),
                        NombresApellidosV1 = c.String(),
                        NombresApellidosV2 = c.String(),
                        NombresApellidosV3 = c.String(),
                        NombresApellidosV4 = c.String(),
                        AnioDiagnosticoV1 = c.String(),
                        AnioDiagnosticoV2 = c.String(),
                        AnioDiagnosticoV3 = c.String(),
                        AnioDiagnosticoV4 = c.String(),
                        PuestoEmpresaVI1 = c.String(),
                        AgentesBiologicosVI1 = c.String(),
                        FrasesVI1 = c.String(),
                        RutinariaVI1 = c.String(),
                        NORutinariaVI1 = c.String(),
                        TiempoExposicionMesesVI1 = c.String(),
                        TiempoExposicionHorasVI1 = c.String(),
                        TLVCorregidoVI1 = c.String(),
                        ConcentracionHalladaVI1 = c.String(),
                        FechaMediacionDiaV1 = c.String(),
                        FechaMediaMesV1 = c.String(),
                        FechaMediaAnioV1 = c.String(),
                        NivelRiesgoV1 = c.String(),
                        ViaEntradaV1 = c.String(),
                        PuestoEmpresaVI2 = c.String(),
                        AgentesBiologicosVI2 = c.String(),
                        FrasesVI2 = c.String(),
                        RutinariaVI2 = c.String(),
                        NORutinariaVI2 = c.String(),
                        TiempoExposicionMesesVI2 = c.String(),
                        TiempoExposicionHorasVI2 = c.String(),
                        TLVCorregidoVI2 = c.String(),
                        ConcentracionHalladaVI2 = c.String(),
                        FechaMediacionDiaV2 = c.String(),
                        FechaMediaMesV2 = c.String(),
                        FechaMediaAnioV2 = c.String(),
                        NivelRiesgoV2 = c.String(),
                        ViaEntradaV2 = c.String(),
                        PuestoEmpresaVI3 = c.String(),
                        AgentesBiologicosVI3 = c.String(),
                        FrasesVI3 = c.String(),
                        RutinariaVI3 = c.String(),
                        NORutinariaVI3 = c.String(),
                        TiempoExposicionMesesVI3 = c.String(),
                        TiempoExposicionHorasVI3 = c.String(),
                        TLVCorregidoVI3 = c.String(),
                        ConcentracionHalladaVI3 = c.String(),
                        FechaMediacionDiaV3 = c.String(),
                        FechaMediaMesV3 = c.String(),
                        FechaMediaAnioV3 = c.String(),
                        NivelRiesgoV3 = c.String(),
                        ViaEntradaV3 = c.String(),
                        PuestoEmpresaVI4 = c.String(),
                        AgentesBiologicosVI4 = c.String(),
                        FrasesVI4 = c.String(),
                        RutinariaVI4 = c.String(),
                        NORutinariaVI4 = c.String(),
                        TiempoExposicionMesesVI4 = c.String(),
                        TiempoExposicionHorasVI4 = c.String(),
                        TLVCorregidoVI4 = c.String(),
                        ConcentracionHalladaVI4 = c.String(),
                        FechaMediacionDiaVI4 = c.String(),
                        FechaMediaMesVI4 = c.String(),
                        FechaMediaAnioVI4 = c.String(),
                        NivelRiesgoVI4 = c.String(),
                        ViaEntradaVI4 = c.String(),
                        OficioEmpresa2V1 = c.String(),
                        AgenteRelBiologico2VI = c.String(),
                        FuenteAgente2VI1 = c.String(),
                        MecanismoTransmicion2VI1 = c.String(),
                        TipoActividadRutinaria2VI1 = c.String(),
                        TipoActividadNoRutinaria2VI1 = c.String(),
                        TiempoExposicionMeses2VI1 = c.String(),
                        TiempoExposicionHoras2VI1 = c.String(),
                        ConcentracionHallada2VI1 = c.String(),
                        NivelRiesgo2VI1 = c.String(),
                        Dia2VI1 = c.String(),
                        Mes2VI1 = c.String(),
                        Anio2VI1 = c.String(),
                        FrecRiesgo2VI1 = c.String(),
                        OficioEmpresa2V2 = c.String(),
                        AgenteRelBiologico2VI2 = c.String(),
                        FuenteAgente2VI2 = c.String(),
                        MecanismoTransmicion2VI2 = c.String(),
                        TipoActividadRutinaria2VI2 = c.String(),
                        TipoActividadNoRutinaria2VI2 = c.String(),
                        TiempoExposicionMeses2VI2 = c.String(),
                        TiempoExposicionHoras2VI2 = c.String(),
                        ConcentracionHallada2VI2 = c.String(),
                        NivelRiesgo2VI2 = c.String(),
                        Dia2VI2 = c.String(),
                        Mes2VI2 = c.String(),
                        Anio2VI2 = c.String(),
                        FrecRiesgo2VI2 = c.String(),
                        OficioEmpresa2V3 = c.String(),
                        AgenteRelBiologico2VI3 = c.String(),
                        FuenteAgente2VI3 = c.String(),
                        MecanismoTransmicion2VI3 = c.String(),
                        TipoActividadRutinaria2VI3 = c.String(),
                        TipoActividadNoRutinaria2VI3 = c.String(),
                        TiempoExposicionMeses2VI3 = c.String(),
                        TiempoExposicionHoras2VI3 = c.String(),
                        ConcentracionHallada2VI3 = c.String(),
                        NivelRiesgo2VI3 = c.String(),
                        Dia2VI3 = c.String(),
                        Mes2VI3 = c.String(),
                        Anio2VI3 = c.String(),
                        FrecRiesgo2VI3 = c.String(),
                        OficioEmpresa2V4 = c.String(),
                        AgenteRelBiologico2VI4 = c.String(),
                        FuenteAgente2VI4 = c.String(),
                        MecanismoTransmicion2VI4 = c.String(),
                        TipoActividadRutinaria2VI4 = c.String(),
                        TipoActividadNoRutinaria2VI4 = c.String(),
                        TiempoExposicionMeses2VI4 = c.String(),
                        TiempoExposicionHoras2VI4 = c.String(),
                        ConcentracionHallada2VI4 = c.String(),
                        NivelRiesgo2VI4 = c.String(),
                        Dia2VI4 = c.String(),
                        Mes2VI4 = c.String(),
                        Anio2VI4 = c.String(),
                        FrecRiesgo2VI4 = c.String(),
                        ExpoAccidentales2VI = c.String(),
                        CargoOficioPuesto3VI = c.String(),
                        Fuentes3VI = c.String(),
                        Meses3VI = c.String(),
                        HorasDia3VI = c.String(),
                        NivelAmbiental3VI = c.String(),
                        FMDia3VI = c.String(),
                        FMMes3VI = c.String(),
                        FMAnio3VI = c.String(),
                        DosisRuido3VI = c.String(),
                        FecMedDia3VI = c.String(),
                        FecMedMes3VI = c.String(),
                        FecMEdAnio3VI = c.String(),
                        ExpSusQuimimcas3VI = c.String(),
                        ExpoAccPrevias3VI = c.String(),
                        CargoOficioPuesto3VI1 = c.String(),
                        Fuentes3VI1 = c.String(),
                        Meses3VI1 = c.String(),
                        HorasDia3VI1 = c.String(),
                        NivelAmbiental3VI1 = c.String(),
                        FMDia3VI1 = c.String(),
                        FMMes3VI1 = c.String(),
                        FMAnio3VI1 = c.String(),
                        DosisRuido3VI1 = c.String(),
                        FecMedDia3VI1 = c.String(),
                        FecMedMes3VI1 = c.String(),
                        FecMEdAnio3VI1 = c.String(),
                        ExpSusQuimimcas3VI1 = c.String(),
                        ExpoAccPrevias3VI1 = c.String(),
                        CargoOficioPuesto3VI2 = c.String(),
                        Fuentes3VI2 = c.String(),
                        Meses3VI2 = c.String(),
                        HorasDia3VI2 = c.String(),
                        NivelAmbiental3VI2 = c.String(),
                        FMDia3VI2 = c.String(),
                        FMMes3VI2 = c.String(),
                        FMAnio3VI2 = c.String(),
                        DosisRuido3VI2 = c.String(),
                        FecMedDia3VI2 = c.String(),
                        FecMedMes3VI2 = c.String(),
                        FecMEdAnio3VI2 = c.String(),
                        ExpSusQuimimcas3VI2 = c.String(),
                        ExpoAccPrevias3VI2 = c.String(),
                        CargoOficioPuesto3VI3 = c.String(),
                        Fuentes3VI3 = c.String(),
                        Meses3VI3 = c.String(),
                        HorasDia3VI3 = c.String(),
                        NivelAmbiental3VI3 = c.String(),
                        FMDia3VI3 = c.String(),
                        FMMes3VI3 = c.String(),
                        FMAnio3VI3 = c.String(),
                        DosisRuido3VI3 = c.String(),
                        FecMedDia3VI3 = c.String(),
                        FecMedMes3VI3 = c.String(),
                        FecMEdAnio3VI3 = c.String(),
                        ExpSusQuimimcas3VI3 = c.String(),
                        ExpoAccPrevias3VI3 = c.String(),
                        CargoOficio4VI1 = c.String(),
                        DescActividad4VI1 = c.String(),
                        Duracion4VI1 = c.String(),
                        FrecActividad4VI1 = c.String(),
                        TipoTrabajoActividad4VI1 = c.String(),
                        WBTG4VI1 = c.String(),
                        TipoExpMeses4VI1 = c.String(),
                        TipoExpHD4VI1 = c.String(),
                        TasaTrabajo4VI1 = c.String(),
                        FechaMedDia4VI1 = c.String(),
                        FechaMedMes4VI1 = c.String(),
                        FechaMedAnio4VI1 = c.String(),
                        CargoOficio4VI2 = c.String(),
                        DescActividad4VI2 = c.String(),
                        Duracion4VI2 = c.String(),
                        FrecActividad4VI2 = c.String(),
                        TipoTrabajoActividad4VI2 = c.String(),
                        WBTG4VI2 = c.String(),
                        TipoExpMeses4VI2 = c.String(),
                        TipoExpHD4VI2 = c.String(),
                        TasaTrabajo4VI2 = c.String(),
                        FechaMedDia4VI2 = c.String(),
                        FechaMedMes4VI2 = c.String(),
                        FechaMedAnio4VI2 = c.String(),
                        CargoOficio4VI3 = c.String(),
                        DescActividad4VI3 = c.String(),
                        Duracion4VI3 = c.String(),
                        FrecActividad4VI3 = c.String(),
                        TipoTrabajoActividad4VI3 = c.String(),
                        WBTG4VI3 = c.String(),
                        TipoExpMeses4VI3 = c.String(),
                        TipoExpHD4VI3 = c.String(),
                        TasaTrabajo4VI3 = c.String(),
                        FechaMedDia4VI3 = c.String(),
                        FechaMedMes4VI3 = c.String(),
                        FechaMedAnio4VI3 = c.String(),
                        CargoOficio4VI4 = c.String(),
                        DescActividad4VI4 = c.String(),
                        Duracion4VI4 = c.String(),
                        FrecActividad4VI4 = c.String(),
                        TipoTrabajoActividad4VI4 = c.String(),
                        WBTG4VI4 = c.String(),
                        TipoExpMeses4VI4 = c.String(),
                        TipoExpHD4VI4 = c.String(),
                        TasaTrabajo4VI4 = c.String(),
                        FechaMedDia4VI4 = c.String(),
                        FechaMedMes4VI4 = c.String(),
                        FechaMedAnio4VI4 = c.String(),
                        RadCargoEmpresa5VI1 = c.String(),
                        RadDescripcionFuente5VI1 = c.String(),
                        RadDescripcionAct5VI1 = c.String(),
                        RadCondiciones5VI1 = c.String(),
                        RadTEDia5VI1 = c.String(),
                        RadTEMes5VI1 = c.String(),
                        RadTEAnio5VI1 = c.String(),
                        RadEvalAmbiental5VI1 = c.String(),
                        RadFMDia5VI1 = c.String(),
                        RadFMMes5VI1 = c.String(),
                        RadFMAnio5VI1 = c.String(),
                        RadCargoEmpresa5VI2 = c.String(),
                        RadDescripcionFuente5VI2 = c.String(),
                        RadDescripcionAct5VI2 = c.String(),
                        RadCondiciones5VI2 = c.String(),
                        RadTEDia5VI2 = c.String(),
                        RadTEMes5VI2 = c.String(),
                        RadTEAnio5VI2 = c.String(),
                        RadEvalAmbiental5VI2 = c.String(),
                        RadFMDia5VI2 = c.String(),
                        RadFMMes5VI2 = c.String(),
                        RadFMAnio5VI2 = c.String(),
                        RadCargoEmpresa5VI3 = c.String(),
                        RadDescripcionFuente5VI3 = c.String(),
                        RadDescripcionAct5VI3 = c.String(),
                        RadCondiciones5VI3 = c.String(),
                        RadTEDia5VI3 = c.String(),
                        RadTEMes5VI3 = c.String(),
                        RadTEAnio5VI3 = c.String(),
                        RadEvalAmbiental5VI3 = c.String(),
                        RadFMDia5VI3 = c.String(),
                        RadFMMes5VI3 = c.String(),
                        RadFMAnio5VI3 = c.String(),
                        RadCargoEmpresa5VI4 = c.String(),
                        RadDescripcionFuente5VI4 = c.String(),
                        RadDescripcionAct5VI4 = c.String(),
                        RadCondiciones5VI4 = c.String(),
                        RadTEDia5VI4 = c.String(),
                        RadTEMes5VI4 = c.String(),
                        RadTEAnio5V4 = c.String(),
                        RadEvalAmbiental5VI4 = c.String(),
                        RadFMDia5VI4 = c.String(),
                        RadFMMes5VI4 = c.String(),
                        RadFMAnio5VI4 = c.String(),
                        VibCargoEmpresa6VI1 = c.String(),
                        VibDescFuente6VI1 = c.String(),
                        BooTipoVibCE6VI1 = c.Boolean(nullable: false),
                        BooTipoVibMB6VI1 = c.Boolean(nullable: false),
                        TiempoExpMeses6VI1 = c.String(),
                        TiempoExpHD6VI1 = c.String(),
                        VCE6VI1 = c.String(),
                        VMB6VI1 = c.String(),
                        AceTotal6VI1 = c.String(),
                        EjeDominante6VI1 = c.String(),
                        AceEjeDominante6VI1 = c.String(),
                        Frecuencia6VI1 = c.String(),
                        Aceleracion6VI1 = c.String(),
                        FechaMedDia6VI1 = c.String(),
                        FechaMedMes6VI1 = c.String(),
                        FechaMedAnio6VI1 = c.String(),
                        BooExpoRuido6VI1 = c.Boolean(nullable: false),
                        VibCargoEmpresa6VI2 = c.String(),
                        VibDescFuente6VI2 = c.String(),
                        BooTipoVibCE6VI2 = c.Boolean(nullable: false),
                        BooTipoVibMB6VI2 = c.Boolean(nullable: false),
                        TiempoExpMeses6VI2 = c.String(),
                        TiempoExpHD6VI2 = c.String(),
                        VCE6VI2 = c.String(),
                        VMB6VI2 = c.String(),
                        AceTotal6VI2 = c.String(),
                        EjeDominante6VI2 = c.String(),
                        AceEjeDominante6VI2 = c.String(),
                        Frecuencia6VI2 = c.String(),
                        Aceleracion6VI2 = c.String(),
                        FechaMedDia6VI2 = c.String(),
                        FechaMedMes6VI2 = c.String(),
                        FechaMedAnio6VI2 = c.String(),
                        BooExpoRuido6VI2 = c.Boolean(nullable: false),
                        VibCargoEmpresa6VI3 = c.String(),
                        VibDescFuente6VI3 = c.String(),
                        BooTipoVibCE6VI3 = c.Boolean(nullable: false),
                        BooTipoVibMB6VI3 = c.Boolean(nullable: false),
                        TiempoExpMeses6VI3 = c.String(),
                        TiempoExpHD6VI3 = c.String(),
                        VCE6VI3 = c.String(),
                        VMB6VI3 = c.String(),
                        AceTotal6VI3 = c.String(),
                        EjeDominante6VI3 = c.String(),
                        AceEjeDominante6VI3 = c.String(),
                        Frecuencia6VI3 = c.String(),
                        Aceleracion6VI3 = c.String(),
                        FechaMedDia6VI3 = c.String(),
                        FechaMedMes6VI3 = c.String(),
                        FechaMedAnio6VI3 = c.String(),
                        BooExpoRuido6VI3 = c.Boolean(nullable: false),
                        VibCargoEmpresa6VI4 = c.String(),
                        VibDescFuente6VI4 = c.String(),
                        BooTipoVibCE6VI4 = c.Boolean(nullable: false),
                        BooTipoVibMB6VI4 = c.Boolean(nullable: false),
                        TiempoExpMeses6VI4 = c.String(),
                        TiempoExpHD6VI4 = c.String(),
                        VCE6VI4 = c.String(),
                        VMB6VI4 = c.String(),
                        AceTotal6VI4 = c.String(),
                        EjeDominante6VI4 = c.String(),
                        AceEjeDominante6VI4 = c.String(),
                        Frecuencia6VI4 = c.String(),
                        Aceleracion6VI4 = c.String(),
                        FechaMedDia6VI4 = c.String(),
                        FechaMedMes6VI4 = c.String(),
                        FechaMedAnio6VI4 = c.String(),
                        BooExpoRuido6VI4 = c.Boolean(nullable: false),
                        VibCargoEmpresa6VI5 = c.String(),
                        VibDescFuente6VI5 = c.String(),
                        BooTipoVibCE6VI5 = c.Boolean(nullable: false),
                        BooTipoVibMB6VI5 = c.Boolean(nullable: false),
                        TiempoExpMeses6VI5 = c.String(),
                        TiempoExpHD6VI5 = c.String(),
                        VCE6VI5 = c.String(),
                        VMB6VI5 = c.String(),
                        AceTotal6VI5 = c.String(),
                        EjeDominante6VI5 = c.String(),
                        AceEjeDominante6VI5 = c.String(),
                        Frecuencia6VI5 = c.String(),
                        Aceleracion6VI5 = c.String(),
                        FechaMedDia6VI5 = c.String(),
                        FechaMedMes6VI5 = c.String(),
                        FechaMedAnio6VI5 = c.String(),
                        BooExpoRuido6VI5 = c.Boolean(nullable: false),
                        VibCargoEmpresa6VI6 = c.String(),
                        VibDescFuente6VI6 = c.String(),
                        BooTipoVibCE6VI6 = c.Boolean(nullable: false),
                        BooTipoVibMB6VI6 = c.Boolean(nullable: false),
                        TiempoExpMeses6VI6 = c.String(),
                        TiempoExpHD6VI6 = c.String(),
                        VCE6VI6 = c.String(),
                        VMB6VI6 = c.String(),
                        AceTotal6VI6 = c.String(),
                        EjeDominante6VI6 = c.String(),
                        AceEjeDominante6VI6 = c.String(),
                        Frecuencia6VI6 = c.String(),
                        Aceleracion6VI6 = c.String(),
                        FechaMedDia6VI6 = c.String(),
                        FechaMedMes6VI6 = c.String(),
                        FechaMedAnio6VI6 = c.String(),
                        BooExpoRuido6VI6 = c.Boolean(nullable: false),
                        DescEventoInv6VI = c.String(),
                        FrecPresAltoVI1 = c.String(),
                        FrecPresMedioVI1 = c.String(),
                        FrecPresBajoVI1 = c.String(),
                        TiempoExpAltoVI1 = c.String(),
                        TiempoExpMedioVI1 = c.String(),
                        TiempoExpBajoVI1 = c.String(),
                        IntensidadAltoVI1 = c.String(),
                        IntensidadMedioVI1 = c.String(),
                        IntensidadBajoVI1 = c.String(),
                        VarPsicoObservacionesVI1 = c.String(),
                        FrecPresAltoVI2 = c.String(),
                        FrecPresMedioVI2 = c.String(),
                        FrecPresBajoVI2 = c.String(),
                        TiempoExpAltoVI2 = c.String(),
                        TiempoExpMedioVI2 = c.String(),
                        TiempoExpBajoVI2 = c.String(),
                        IntensidadAltoVI2 = c.String(),
                        IntensidadMedioVI2 = c.String(),
                        IntensidadBajoVI2 = c.String(),
                        VarPsicoObservacionesVI2 = c.String(),
                        FrecPresAltoVI3 = c.String(),
                        FrecPresMedioVI3 = c.String(),
                        FrecPresBajoVI3 = c.String(),
                        TiempoExpAltoVI3 = c.String(),
                        TiempoExpMedioVI3 = c.String(),
                        TiempoExpBajoVI3 = c.String(),
                        IntensidadAltoVI3 = c.String(),
                        IntensidadMedioVI3 = c.String(),
                        IntensidadBajoVI3 = c.String(),
                        VarPsicoObservacionesVI3 = c.String(),
                        FrecPresAltoVI4 = c.String(),
                        FrecPresMedioVI4 = c.String(),
                        FrecPresBajoVI4 = c.String(),
                        TiempoExpAltoVI4 = c.String(),
                        TiempoExpMedioVI4 = c.String(),
                        TiempoExpBajoV4 = c.String(),
                        IntensidadAltoVI4 = c.String(),
                        IntensidadMedioVI4 = c.String(),
                        IntensidadBajoVI4 = c.String(),
                        VarPsicoObservacionesVI4 = c.String(),
                        IntensidadAltaVI1 = c.String(),
                        IntensidadMediaVI1 = c.String(),
                        IntensidadBajaVI1 = c.String(),
                        IntensidadObservVI1 = c.String(),
                        IntensidadAltaVI2 = c.String(),
                        IntensidadMediaVI2 = c.String(),
                        IntensidadBajaVI2 = c.String(),
                        IntensidadObservVI2 = c.String(),
                        NivelRiesgoLabVI = c.String(),
                        NivelRiesgoExtralabVI = c.String(),
                        NivelRiesgoIndiviVI = c.String(),
                        NivelEstresVI = c.String(),
                        BooPostPieProlongada = c.Boolean(nullable: false),
                        BooPostPieSedente = c.Boolean(nullable: false),
                        BooPosturaIncomodaBrazosManos = c.Boolean(nullable: false),
                        BooEsfuerzoBrazosManos = c.Boolean(nullable: false),
                        BooPosturaIncomodaEspalda = c.Boolean(nullable: false),
                        BooLabRepetitivaColumna = c.Boolean(nullable: false),
                        BooLabRepetitivaBrazoMuMano = c.Boolean(nullable: false),
                        BooPeriodoRecuperacionFisica = c.Boolean(nullable: false),
                        BooEsfuerzoManos = c.Boolean(nullable: false),
                        BooEsfuerzoCuerpo = c.Boolean(nullable: false),
                        BooManipulacionCargas = c.Boolean(nullable: false),
                        DMEResumen = c.String(),
                        BooCauRelPrevVI1 = c.Boolean(nullable: false),
                        CauRelPrevVI1 = c.String(),
                        BooCauRelPrevVI2 = c.Boolean(nullable: false),
                        CauRelPrevVI2 = c.String(),
                        BooCauRelPrevVI3 = c.Boolean(nullable: false),
                        CauRelPrevVI3 = c.String(),
                        BooCauRelPrevVI4 = c.Boolean(nullable: false),
                        CauRelPrevVI4 = c.String(),
                        BooCauRelPrevVI5 = c.Boolean(nullable: false),
                        CauRelPrevVI5 = c.String(),
                        BooCauRelPrevVI6 = c.Boolean(nullable: false),
                        CauRelPrevVI6 = c.String(),
                        BooCauRelPrevVI7 = c.Boolean(nullable: false),
                        CauRelPrevVI7 = c.String(),
                        BooCauRelPrevVI8 = c.Boolean(nullable: false),
                        CauRelPrevVI8 = c.String(),
                        BooCauRelPrevVI9 = c.Boolean(nullable: false),
                        CauRelPrevVI9 = c.String(),
                        BooCauRelPrevVI10 = c.Boolean(nullable: false),
                        CauRelPrevVI10 = c.String(),
                        BooCauRelPrevVI11 = c.Boolean(nullable: false),
                        CauRelPrevVI11 = c.String(),
                        BooCauRelPrevVI12 = c.Boolean(nullable: false),
                        CauRelPrevVI12 = c.String(),
                        OtrosDatosInteresVI = c.String(),
                        CausasEnfermedadLaboralVI = c.String(),
                        MedidasPreventivasVII1 = c.String(),
                        ResponsableImplementacionVII1 = c.String(),
                        FechaEjeMesVII1 = c.String(),
                        FechaEjeDiaVII1 = c.String(),
                        MedidasPreventivasVII2 = c.String(),
                        ResponsableImplementacionVII2 = c.String(),
                        FechaEjeMesVII3 = c.String(),
                        FechaEjeDiaVII3 = c.String(),
                        MedidasPreventivasVII4 = c.String(),
                        ResponsableImplementacionVII4 = c.String(),
                        FechaEjeMesVII4 = c.String(),
                        FechaEjeDiaVII4 = c.String(),
                        MedidasPreventivasVII5 = c.String(),
                        ResponsableImplementacionVII5 = c.String(),
                        FechaEjeMesVII5 = c.String(),
                        FechaEjeDiaVII5 = c.String(),
                        MedidasPreventivasVII6 = c.String(),
                        ResponsableImplementacionVII6 = c.String(),
                        FechaEjeMesVII6 = c.String(),
                        FechaEjeDiaVII6 = c.String(),
                        MedidasPreventivasVII7 = c.String(),
                        ResponsableImplementacionVII7 = c.String(),
                        FechaEjeMesVII7 = c.String(),
                        FechaEjeDiaVII7 = c.String(),
                        MedidasPreventivasVII8 = c.String(),
                        ResponsableImplementacionVII8 = c.String(),
                        FechaEjeMesVII8 = c.String(),
                        FechaEjeDiaVII8 = c.String(),
                        TipoIdentificacionVIII1 = c.String(),
                        JefeInmediatoVIII1 = c.String(),
                        CargoVIII1 = c.String(),
                        NumeroIdentificacionVIII1 = c.String(),
                        TipoIdentificacionVIII2 = c.String(),
                        JefeInmediatoVIII2 = c.String(),
                        CargoVIII2 = c.String(),
                        NumeroIdentificacionVIII2 = c.String(),
                        TipoIdentificacionVIII3 = c.String(),
                        JefeInmediatoVIII3 = c.String(),
                        CargoVIII3 = c.String(),
                        NumeroIdentificacionVIII3 = c.String(),
                        TipoIdentificacionVIII4 = c.String(),
                        JefeInmediatoVIII4 = c.String(),
                        CargoVIII4 = c.String(),
                        NumeroIdentificacionVIII4 = c.String(),
                        TipoIdentificacionVIII5 = c.String(),
                        JefeInmediatoVIII5 = c.String(),
                        CargoVIII5 = c.String(),
                        NumeroIdentificacionVIII5 = c.String(),
                        TipoIdentificacionVIII6 = c.String(),
                        JefeInmediatoVIII6 = c.String(),
                        CargoVIII6 = c.String(),
                        NumeroIdentificacionVIII6 = c.String(),
                        TipoIdentificacionVIII7 = c.String(),
                        EspecialistaOcupacionalVIII = c.String(),
                        LicenciaNumVIII1 = c.String(),
                        LicenciaAnioVIII1 = c.String(),
                        NumeroIdentificacionVIII7 = c.String(),
                        TipoIdentificacionVIII8 = c.String(),
                        RepresentanteArlVIII8 = c.String(),
                        LicenciaNumeroVIII8 = c.String(),
                        LicenciaAnioVIII8 = c.String(),
                        NumeroIdentificacionVIII8 = c.String(),
                        EmpresaRepresentaVIII8 = c.String(),
                        NitVIII8 = c.String(),
                        FechaRemisionIX = c.String(),
                        NoFoliosIX = c.String(),
                        TipoIdentificacionIX = c.Boolean(nullable: false),
                        NombreApellidoIX = c.String(),
                        CargoIX = c.String(),
                        NumeroIdentificacionIX = c.String(),
                        FechaRemisionARLIX = c.String(),
                        FecRemisionTerritorialIX = c.String(),
                        DisponibleRemisionARLIX = c.String(),
                        ResponsablesRemisionARLIX = c.String(),
                        CargoARLIX = c.String(),
                        TipoIdentificacionX = c.Boolean(nullable: false),
                        ResponsableVerficiacionX = c.String(),
                        CargoX = c.String(),
                        NumeroIdentificacionX = c.String(),
                        MedidasIntervencionX = c.Boolean(nullable: false),
                        ObsevacionesX = c.String(),
                        FechaVerficacionX = c.String(),
                        TipoIdentificacionXI = c.Boolean(nullable: false),
                        ResponsableVerficiacionXI = c.String(),
                        CargoXI = c.String(),
                        NumeroIdentificacionXI = c.String(),
                        MedidasIntervencionXI = c.Boolean(nullable: false),
                        ObsevacionesARLXI = c.String(),
                        FechaVerficacionXI = c.String(),
                    })
                .PrimaryKey(t => t.PK_Incidentes_EL);
            
            AddColumn("dbo.Tbl_ComunicadosAPP", "Estado", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.Tbl_ComunicadosAPP", "Estado");
            DropTable("dbo.Tbl_IncidentesEL");
            DropTable("dbo.Tbl_GrupoUsuariosComunicaciones");
            DropTable("dbo.Tbl_GruposComunicaciones");
            DropTable("dbo.Tbl_Eme_Roles");
            DropTable("dbo.Tbl_Eme_RecursosTecnicos");
            DropTable("dbo.Tbl_Eme_RecursosHumanos");
            DropTable("dbo.Tbl_Eme_ProcOpera_Normalizados");
            DropTable("dbo.Tbl_Eme_PlanAyuda");
            DropTable("dbo.Tbl_Eme_NivelEmergencia");
            DropTable("dbo.Tbl_Eme_InfoGeneral");
            DropTable("dbo.Tbl_Eme_Georeferenciacion");
            DropTable("dbo.Tbl_Eme_Generalidades");
            DropTable("dbo.Tbl_Eme_FrentesAccion");
            DropTable("dbo.Tbl_Eme_EsquemaOrganizacional");
            DropTable("dbo.Tbl_Eme_Elementos");
            DropTable("dbo.Tbl_Eme_DescripcionOcupacion");
            DropTable("dbo.Tbl_Eme_CaracteristicasInstalacion");
            DropTable("dbo.Tbl_Eme_bd_Interna");
            DropTable("dbo.Tbl_Eme_Bd_Externa");
            DropTable("dbo.Tbl_Eme_AnalisisRiesgo");
            DropTable("dbo.Tbl_ComunicadosAdjutos");
        }
    }
}
