//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG_SST.Recursos.AdministracionUsuarios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajesAdministracionUsuarios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesAdministracionUsuarios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SG_SST.Recursos.AdministracionUsuarios.MensajesAdministracionUsuarios", typeof(MensajesAdministracionUsuarios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no se puede crear porque ya se superó la cantidad máxima de usuarios para este Rol y todos están aprobados..
        /// </summary>
        public static string CantidadUsuariosAprobadosPorRolSuperada {
            get {
                return ResourceManager.GetString("CantidadUsuariosAprobadosPorRolSuperada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no se puede crear porque ya se superó la cantidad máxima de usuarios para este Rol y algunos están sin ser aprobados..
        /// </summary>
        public static string CantidadUsuariosPorRolSuperada {
            get {
                return ResourceManager.GetString("CantidadUsuariosPorRolSuperada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no se puede crear porque el empleado asociado al tipo y número de documento se encuentra inactivo..
        /// </summary>
        public static string EmpleadoInactivo {
            get {
                return ResourceManager.GetString("EmpleadoInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se encuentra inactivo..
        /// </summary>
        public static string EmpleadoInactivoLogin {
            get {
                return ResourceManager.GetString("EmpleadoInactivoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no se puede crear porque no existe un empleado asociado al tipo y número de documento ingresados..
        /// </summary>
        public static string EmpleadoNoExiste {
            get {
                return ResourceManager.GetString("EmpleadoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El documento del usuario no se encuentra relacionado al documento de la empresa ingresados..
        /// </summary>
        public static string EmpleadoNoExisteLogin {
            get {
                return ResourceManager.GetString("EmpleadoNoExisteLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El documento ingresado del empleador y usuario no presenta relación laboral..
        /// </summary>
        public static string EmpresaInactiva {
            get {
                return ResourceManager.GetString("EmpresaInactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La empresa se encuentra inactiva.
        /// </summary>
        public static string EmpresaInactivaLogin {
            get {
                return ResourceManager.GetString("EmpresaInactivaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no se puede crear porque no existe una empresa asociada al tipo y número de documento ingresados..
        /// </summary>
        public static string EmpresaNoExiste {
            get {
                return ResourceManager.GetString("EmpresaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El documento ingresado del empleador y usuario no presenta relación laboral..
        /// </summary>
        public static string EmpresaNoExisteLogin {
            get {
                return ResourceManager.GetString("EmpresaNoExisteLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al registrar el usuario para aprobar. Intente más tarde..
        /// </summary>
        public static string ErrorUsuarioParaAprobar {
            get {
                return ResourceManager.GetString("ErrorUsuarioParaAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se registró con éxito en el sistema, recuerde que está pendiente la aprobación y activación por parte de Positiva Compañía de Seguros S.A. Por favor revisar la bandeja del correo electrónico registrado en la solicitud..
        /// </summary>
        public static string UsuarioCreado {
            get {
                return ResourceManager.GetString("UsuarioCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se encuentra inactivo..
        /// </summary>
        public static string UsuarioInactivoPorSistema {
            get {
                return ResourceManager.GetString("UsuarioInactivoPorSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no se pudo registrrar en el sistema. Intente nuevamente..
        /// </summary>
        public static string UsuarioNoCreado {
            get {
                return ResourceManager.GetString("UsuarioNoCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ya se encuentra registrado en el sistema para la empresa ingresada..
        /// </summary>
        public static string UsuarioParaAprobarExiste {
            get {
                return ResourceManager.GetString("UsuarioParaAprobarExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario se registró con éxito y está pendiente por aprobación..
        /// </summary>
        public static string UsuarioParaAprobarRegistrado {
            get {
                return ResourceManager.GetString("UsuarioParaAprobarRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no se puede crear porque el Usuario con Rol Representante Legal asociado a la emrpesa se encuentra Inactivo..
        /// </summary>
        public static string UsuarioPorRolInactivo {
            get {
                return ResourceManager.GetString("UsuarioPorRolInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no se puede crear porque no existe un Usuario con Rol Representante Legal asociado a la empresa..
        /// </summary>
        public static string UsuarioPorRolNoExiste {
            get {
                return ResourceManager.GetString("UsuarioPorRolNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no se puede crear porque existe un Usuario con Rol Representante Legal pendiente por aprobacion..
        /// </summary>
        public static string UsuarioPorRolPorAprobar {
            get {
                return ResourceManager.GetString("UsuarioPorRolPorAprobar", resourceCulture);
            }
        }
    }
}
