$(function () {
	ConstruirDatePickerPorElemento('FechaInvestigacionI');
	ConstruirDatePickerPorElemento('FechaNacimientoIII');
	ConstruirDatePickerPorElemento('FechaMuerteIV');
	ConstruirDatePickerPorElemento('FechaOrigenELV');
	ConstruirDatePickerPorElemento('FechaMediacionDiaV1');
	ConstruirDatePickerPorElemento('FechaMediaMesV1');
	ConstruirDatePickerPorElemento('FechaMediaAnioV1');
	ConstruirDatePickerPorElemento('FechaMediacionDiaV2');
	ConstruirDatePickerPorElemento('FechaMediaMesV2');
	ConstruirDatePickerPorElemento('FechaMediaAnioV2');
	ConstruirDatePickerPorElemento('FechaMediacionDiaV3');
	ConstruirDatePickerPorElemento('FechaMediaMesV3');
	ConstruirDatePickerPorElemento('FechaMediaAnioV3');
	ConstruirDatePickerPorElemento('FechaMediacionDiaVI4');
	ConstruirDatePickerPorElemento('FechaMediaMesVI4');
	ConstruirDatePickerPorElemento('FechaMediaAnioVI4');
	ConstruirDatePickerPorElemento('FechaMedDia4VI1');
	ConstruirDatePickerPorElemento('FechaMedMes4VI1');
	ConstruirDatePickerPorElemento('FechaMedAnio4VI1');
	ConstruirDatePickerPorElemento('FechaMedDia4VI2');
	ConstruirDatePickerPorElemento('FechaMedMes4VI2');
	ConstruirDatePickerPorElemento('FechaMedAnio4VI2');
	ConstruirDatePickerPorElemento('FechaMedDia4VI3');
	ConstruirDatePickerPorElemento('FechaMedMes4VI3');
	ConstruirDatePickerPorElemento('FechaMedAnio4VI3');
	ConstruirDatePickerPorElemento('FechaMedDia4VI4');
	ConstruirDatePickerPorElemento('FechaMedMes4VI4');
	ConstruirDatePickerPorElemento('FechaMedAnio4VI4');
	ConstruirDatePickerPorElemento('FechaMedDia6VI1');
	ConstruirDatePickerPorElemento('FechaMedMes6VI1');
	ConstruirDatePickerPorElemento('FechaMedAnio6VI1');
	ConstruirDatePickerPorElemento('FechaMedDia6VI2');
	ConstruirDatePickerPorElemento('FechaMedMes6VI2');
	ConstruirDatePickerPorElemento('FechaMedAnio6VI2');
	ConstruirDatePickerPorElemento('FechaMedDia6VI3');
	ConstruirDatePickerPorElemento('FechaMedMes6VI3');
	ConstruirDatePickerPorElemento('FechaMedAnio6VI3');
	ConstruirDatePickerPorElemento('FechaMedDia6VI4');
	ConstruirDatePickerPorElemento('FechaMedMes6VI4');
	ConstruirDatePickerPorElemento('FechaMedAnio6VI4');    
	ConstruirDatePickerPorElemento('FechaMedDia6VI5');
	ConstruirDatePickerPorElemento('FechaMedMes6VI5');
	ConstruirDatePickerPorElemento('FechaMedAnio6VI5');       
	ConstruirDatePickerPorElemento('FechaMedDia6VI6');
	ConstruirDatePickerPorElemento('FechaMedMes6VI6');
	ConstruirDatePickerPorElemento('FechaMedAnio6VI6');
	/*ConstruirDatePickerPorElemento('FechaEjeMesVII1');
	ConstruirDatePickerPorElemento('FechaEjeDiaVII1');
	ConstruirDatePickerPorElemento('FechaEjeMesVII3');
	ConstruirDatePickerPorElemento('FechaEjeDiaVII3');
	ConstruirDatePickerPorElemento('FechaEjeMesVII4');
	ConstruirDatePickerPorElemento('FechaEjeDiaVII4');
	ConstruirDatePickerPorElemento('FechaEjeMesVII5');
	ConstruirDatePickerPorElemento('FechaEjeDiaVII5');
	ConstruirDatePickerPorElemento('FechaEjeMesVII6');
	ConstruirDatePickerPorElemento('FechaEjeDiaVII6');
	ConstruirDatePickerPorElemento('FechaEjeMesVII7');
	ConstruirDatePickerPorElemento('FechaEjeDiaVII7');
	ConstruirDatePickerPorElemento('FechaEjeMesVII8');
	ConstruirDatePickerPorElemento('FechaEjeDiaVII8');*/
	ConstruirDatePickerPorElemento('FechaRemisionIX');
	ConstruirDatePickerPorElemento('FechaRemisionARLIX');
	ConstruirDatePickerPorElemento('FechaVerficacionX');    
	ConstruirDatePickerPorElemento('FechaVerficacionXI');
	ConstruirDatePickerPorElemento('FecRemisionTerritorialIX');
	ConstruirDatePickerPorElemento('FechaIngresoIV');
	
	
	$("#HoraInicioI").timepicker();
	$("#HoraFinI").timepicker	();
	$("#TiempoExposicionHorasVI1").timepicker();
	$("#TiempoExposicionHorasVI2").timepicker();
	$("#TiempoExposicionHorasVI3").timepicker();
	$("#TiempoExposicionHorasVI4").timepicker();
	$("#TiempoExposicionHoras2VI1").timepicker();
	$("#TiempoExposicionHoras2VI2").timepicker();
	$("#TiempoExposicionHoras2VI3").timepicker();
	$("#TiempoExposicionHoras2VI4").timepicker();
	$("#HorasDia3VI").timepicker();
	$("#HorasDia3VI1").timepicker();
	$("#HorasDia3VI2").timepicker();
	$("#HorasDia3VI3").timepicker();


    $("#accordion1").accordion({
        heightStyle: "content"
    });
});

function CargarMunicipios(codDepto){
	$.ajax({
		type: 'GET',
		url: '/IncidentesAT/ObtenerMunicipiosxDepto',
		data: { pk_id_depto : codDepto },
		success: function (result) {
		 $("#pk_MunicipioI").empty();
		 $.each(result, function(k,v){
			$("#pk_MunicipioI").append("<option value=\""+v.Pk_Id_Municipio+"\">"+v.Nombre_Municipio+"</option>");
		 });
		}
	});
}

function CargarMunicipiosI(codDepto){
	$.ajax({
		type: 'GET',
		url: '/IncidentesAT/ObtenerMunicipiosxDepto',
		data: { pk_id_depto : codDepto },
		success: function (result) {
		 $("#pk_McpioPpalII").empty();
		 $.each(result, function(k,v){
			$("#pk_McpioPpalII").append("<option value=\""+v.Pk_Id_Municipio+"\">"+v.Nombre_Municipio+"</option>");
		 });
		}
	});
}

function CargarMunicipiosII(codDepto){
	$.ajax({
		type: 'GET',
		url: '/IncidentesAT/ObtenerMunicipiosxDepto',
		data: { pk_id_depto : codDepto },
		success: function (result) {
		 $("#pk_McpioEmpleadorII").empty();
		 $.each(result, function(k,v){
			$("#pk_McpioEmpleadorII").append("<option value=\""+v.Pk_Id_Municipio+"\">"+v.Nombre_Municipio+"</option>");
		 });
		}
	});
}

function CargarMunicipiosIII(codDepto){
	$.ajax({
		type: 'GET',
		url: '/IncidentesAT/ObtenerMunicipiosxDepto',
		data: { pk_id_depto : codDepto },
		success: function (result) {
		 $("#pk_McpioCentroTrabajoII").empty();
		 $.each(result, function(k,v){
			$("#pk_McpioCentroTrabajoII").append("<option value=\""+v.Pk_Id_Municipio+"\">"+v.Nombre_Municipio+"</option>");
		 });
		}
	});
}

function GuardarParcial(accordId){
	ValidaGuardarFormulario();
	if ($("#frmIncidentesEL").valid()) {
		$("#accordion1").accordion({ active: accordId });
	}
}

function GuardarDefinitivo(){
   ValidaGuardarFormulario();
	if ($("#frmIncidentesEL").valid()) {
		PopupPosition();
		$.ajax({
			type: 'POST',
			url: '/IncidentesEL/GuardarIncidenteEL',
			data: $("#frmIncidentesEL").serialize(),
			traditional: true,
			success: function (result) {
				OcultarPopupposition();
				$("#PK_Incidentes_EL_Id").val(result);
				$("#accordion1").accordion({ active: 0 });
			}
		});
	}
}

function ValidaGuardarFormulario(){
	$("#frmIncidentesEL").validate({
        errorClass: "error",
        rules: {
			EnfLabCalificadaI :{ required: true },
			FechaInvestigacionI :{ required: true }, 
			DepartamentoI :{ required: true }, 
			MunicipioI :{ required: true }, 
			DireccionI :{ required: true }, 
			NombresApellidosI :{ required: true }, 
			ProfesionalI :{ required: true }, 
			NoLicenciaI :{ required: true }, 
			FotografiasI :{ required: false }, 
			IlustracionesI :{ required: false }, 
			DiagramasI :{ required: false }, 
			OtrosCualesI :{ required: false }, 


			EmpleadorII :{ required: false }, 
			ContratanteII :{ required: false }, 
			IndependienteII :{ required: false }, 
			CooperativaII :{ required: false }, 
			AgremiacionII :{ required: false }, 
			AsociacionII :{ required: false }, 
			CodActividadII :{ required: true }, 
			ActividadPrincipalII :{ required: true }, 
			RazonSocialII :{ required: true }, 
			TipoIdentificacionII :{ required: true }, 
			NumIdentificacionII :{ required: true }, 

			DireccionPrincipalII :{ required: true }, 
			TelefonoPpalII :{ required: true }, 
			FaxII :{ required: true }, 
			DeptoPpalII :{ required: true }, 
			McpioPpalII :{ required: true }, 
			EmailII :{ required: true }, 
			//boZonaPpalII :{ required: true }, 
			CentroTrabajoPpalII :{ required: true }, 

			CentroCostoTelefonoII :{ required: true }, 
			CentroCostoFaxII :{ required: true }, 
			CodActEconoPpalII :{ required: true }, 
			ActEconoCentroTrabajoII :{ required: true }, 
			DeptoEmpleadorII :{ required: true }, 
			McpioEmpleadorII :{ required: true }, 
			EmailEmpleadorII :{ required: true }, 
			//boZonaEmpleadorII :{ required: true }, 
			DeptoCentroTrabajoII :{ required: true }, 
			McpioCentroTrabajoII :{ required: true }, 


			PlantaIII :{ required: false }, 
			MisionIII :{ required: false }, 
			CooperadorIII :{ required: false }, 
			EstudianteIII :{ required: false }, 
			IndependienteIII :{ required: false }, 
			TipoIdentificacionIII :{ required: true }, 
			NumIdentificacionIII :{ required: true }, 
			PrimerApellidoIII :{ required: true }, 
			SegundoApellidoIII :{ required: true }, 
			PrimerNombreIII :{ required: true }, 
			SegundoNombreIII :{ required: true }, 
			FechaNacimientoIII :{ required: true }, 
			SexoIII :{ required: true }, 
			EPSAfiliadoIII :{ required: true }, 
			AFPAfiliadoIII :{ required: true }, 
			ARLAfiliadoIII :{ required: true }, 
			TelefonoIII :{ required: true }, 
			FaxIII  :{ required: true }, 
			EmailTrabajadorIII :{ required: true }, 
			DireccionTrabajadorIII :{ required: true }, 
			//boZonaIII :{ required: true }, 


			CargoIV :{ required: true }, 
			AntiguedadCargoAIV :{ required: true }, 
			AntiguedadCargoMIV :{ required: true }, 
			CodOcupacionIV :{ required: true }, 
			OcupacionHabitualIV :{ required: true }, 
			FechaMuerteIV :{ required: true }, 
			AreaActualIV :{ required: true }, 
			NombreCargoIV :{ required: true }, 
			AntiguedadCargoAnioIV :{ required: true }, 
			AntiguedadCargoMesesIV :{ required: true }, 
			DiurnoIV :{ required: true }, 
			NocturnoIV :{ required: true }, 
			MixtoIV :{ required: true }, 
			TurnosIV :{ required: true }, 
			CondicionesPuestoTrabajoIV :{ required: true }, 

			TareasCargo1IV :{ required: false }, 
			DedicacionJL1IV :{ required: false }, 
			DedicacionJL11IV :{ required: false }, 
			DedicacionJL12IV :{ required: false }, 
			RelacionMuyProbable1IV :{ required: false }, 
			RelacionProbable1IV :{ required: false }, 
			RelacionPocoProbable1IV :{ required: false }, 
			DedicacionJL21IV :{ required: false }, 
			DedicacionJL22IV :{ required: false }, 
			DedicacionJL23IV :{ required: false }, 
			RelacionMuyProbable2IV :{ required: false }, 
			RelacionProbable2IV :{ required: false }, 
			RelacionPocoProbable2IV :{ required: false }, 

			TareasCargo3IV :{ required: false }, 
			DedicacionJL31IV :{ required: false }, 
			DedicacionJL32IV :{ required: false }, 
			DedicacionJL33IV :{ required: false }, 
			RelacionMuyProbable3IV :{ required: false }, 
			RelacionProbable3IV :{ required: false }, 
			RelacionPocoProbable3IV :{ required: false }, 

			TareasCargo4IV :{ required: false }, 
			DedicacionJL41IV :{ required: false }, 
			DedicacionJL42IV :{ required: false }, 
			DedicacionJL43IV :{ required: false }, 
			RelacionMuyProbable4IV :{ required: false }, 
			RelacionProbable4IV :{ required: false }, 
			RelacionPocoProbable4IV :{ required: false }, 

			FormacionInformacionIV :{ required: false }, 
			ProteccionColectivaIV :{ required: false }, 
			EPPIV :{ required: false },   
			DiseñoPuestoTrabajoIV :{ required: false },  
			OrganizacionTrabajoIV :{ required: false }, 
			PreventivasIV :{ required: false }, 
			ImplementadasIV :{ required: false }, 
			DescripcionIV :{ required: false }, 

			CodigoCie1 :{ required: false }, 
			CodigoCie2 :{ required: false }, 
			CodigoCie3 :{ required: false }, 
			CodigoCie4 :{ required: false }, 
			DiagnosticoIV1 :{ required: false }, 
			DiagnosticoIV2 :{ required: false }, 
			DiagnosticoIV3 :{ required: false }, 
			DiagnosticoIV4 :{ required: false }, 


			FechaOrigenELV :{ required: true }, 
			OrigenLaboralIV :{ required: true }, 
			NoTrabajadoresV :{ required: true }, 
			CargosSimilaresV :{ required: true }, 

			NombresApellidosV1 :{ required: true }, 
			NombresApellidosV2 :{ required: true }, 
			NombresApellidosV3 :{ required: true }, 
			NombresApellidosV4 :{ required: true }, 

			AnioDiagnosticoV1 :{ required: true }, 
			AnioDiagnosticoV2 :{ required: true }, 
			AnioDiagnosticoV3 :{ required: true }, 
			AnioDiagnosticoV4 :{ required: true }, 


			PuestoEmpresaVI1 :{ required: false }, 
			AgentesBiologicosVI1 :{ required: false }, 
			FrasesVI1 :{ required: false }, 
			RutinariaVI1 :{ required: false }, 
			NORutinariaVI1 :{ required: false }, 
			TiempoExposicionMesesVI1 :{ required: false }, 
			TiempoExposicionHorasVI1 :{ required: false }, 
			TLVCorregidoVI1 :{ required: false }, 
			ConcentracionHalladaVI1 :{ required: false }, 
			FechaMediacionDiaV1 :{ required: false }, 
			FechaMediaMesV1 :{ required: false }, 
			FechaMediaAnioV1 :{ required: false }, 
			NivelRiesgoV1 :{ required: false }, 
			ViaEntradaV1 :{ required: false }, 

			PuestoEmpresaVI2 :{ required: false }, 
			AgentesBiologicosVI2 :{ required: false }, 
			FrasesVI2 :{ required: false }, 
			RutinariaVI2 :{ required: false }, 
			NORutinariaVI2 :{ required: false }, 
			TiempoExposicionMesesVI2 :{ required: false }, 
			TiempoExposicionHorasVI2 :{ required: false }, 
			TLVCorregidoVI2 :{ required: false }, 
			ConcentracionHalladaVI2 :{ required: false }, 
			FechaMediacionDiaV2 :{ required: false }, 
			FechaMediaMesV2 :{ required: false }, 
			FechaMediaAnioV2 :{ required: false }, 
			NivelRiesgoV2 :{ required: false }, 
			ViaEntradaV2 :{ required: false }, 

			PuestoEmpresaVI3 :{ required: false }, 
			AgentesBiologicosVI3 :{ required: false }, 
			FrasesVI3 :{ required: false }, 
			RutinariaVI3 :{ required: false }, 
			NORutinariaVI3 :{ required: false }, 
			TiempoExposicionMesesVI3 :{ required: false }, 
			TiempoExposicionHorasVI3 :{ required: false }, 
			TLVCorregidoVI3 :{ required: false }, 
			ConcentracionHalladaVI3 :{ required: false }, 
			FechaMediacionDiaV3 :{ required: false }, 
			FechaMediaMesV3 :{ required: false }, 
			FechaMediaAnioV3 :{ required: false }, 
			NivelRiesgoV3 :{ required: false }, 
			ViaEntradaV3 :{ required: false }, 

			PuestoEmpresaVI4 :{ required: false }, 
			AgentesBiologicosVI4 :{ required: false }, 
			FrasesVI4 :{ required: false }, 
			RutinariaVI4 :{ required: false }, 
			NORutinariaVI4 :{ required: false }, 
			TiempoExposicionMesesVI4 :{ required: false }, 
			TiempoExposicionHorasVI4 :{ required: false }, 
			TLVCorregidoVI4 :{ required: false }, 
			ConcentracionHalladaVI4 :{ required: false }, 
			FechaMediacionDiaVI4 :{ required: false }, 
			FechaMediaMesVI4 :{ required: false }, 
			FechaMediaAnioVI4 :{ required: false }, 
			NivelRiesgoVI4 :{ required: false }, 
			ViaEntradaVI4 :{ required: false }, 

			OficioEmpresa2V1 :{ required: false }, 
			AgenteRelBiologico2VI :{ required: false }, 
			FuenteAgente2VI1 :{ required: false }, 
			MecanismoTransmicion2VI1 :{ required: false }, 
			TipoActividadRutinaria2VI1 :{ required: false }, 
			TipoActividadNoRutinaria2VI1 :{ required: false }, 
			TiempoExposicionMeses2VI1 :{ required: false }, 
			TiempoExposicionHoras2VI1 :{ required: false }, 
			ConcentracionHallada2VI1 :{ required: false }, 
			NivelRiesgo2VI1 :{ required: false }, 
			Dia2VI1 :{ required: false }, 
			Mes2VI1 :{ required: false }, 
			Anio2VI1 :{ required: false }, 
			FrecRiesgo2VI1 :{ required: false }, 

			OficioEmpresa2V2 :{ required: false }, 
			AgenteRelBiologico2VI2 :{ required: false }, 
			FuenteAgente2VI2 :{ required: false }, 
			MecanismoTransmicion2VI2 :{ required: false }, 
			TipoActividadRutinaria2VI2 :{ required: false }, 
			TipoActividadNoRutinaria2VI2 :{ required: false }, 
			TiempoExposicionMeses2VI2 :{ required: false }, 
			TiempoExposicionHoras2VI2 :{ required: false }, 
			ConcentracionHallada2VI2 :{ required: false }, 
			NivelRiesgo2VI2 :{ required: false }, 
			Dia2VI2 :{ required: false }, 
			Mes2VI2 :{ required: false }, 
			Anio2VI2 :{ required: false }, 
			FrecRiesgo2VI2 :{ required: false }, 

			OficioEmpresa2V3 :{ required: false }, 
			AgenteRelBiologico2VI3 :{ required: false }, 
			FuenteAgente2VI3 :{ required: false }, 
			MecanismoTransmicion2VI3 :{ required: false }, 
			TipoActividadRutinaria2VI3 :{ required: false }, 
			TipoActividadNoRutinaria2VI3 :{ required: false }, 
			TiempoExposicionMeses2VI3 :{ required: false }, 
			TiempoExposicionHoras2VI3 :{ required: false }, 
			ConcentracionHallada2VI3 :{ required: false }, 
			NivelRiesgo2VI3 :{ required: false }, 
			Dia2VI3 :{ required: false }, 
			Mes2VI3 :{ required: false }, 
			Anio2VI3 :{ required: false }, 
			FrecRiesgo2VI3 :{ required: false }, 

			OficioEmpresa2V4 :{ required: false }, 
			AgenteRelBiologico2VI4 :{ required: false }, 
			FuenteAgente2VI4 :{ required: false }, 
			MecanismoTransmicion2VI4 :{ required: false }, 
			TipoActividadRutinaria2VI4 :{ required: false }, 
			TipoActividadNoRutinaria2VI4 :{ required: false }, 
			TiempoExposicionMeses2VI4 :{ required: false }, 
			TiempoExposicionHoras2VI4 :{ required: false }, 
			ConcentracionHallada2VI4 :{ required: false }, 
			NivelRiesgo2VI4 :{ required: false }, 
			Dia2VI4 :{ required: false }, 
			Mes2VI4 :{ required: false }, 
			Anio2VI4 :{ required: false }, 
			FrecRiesgo2VI4 :{ required: false }, 
			ExpoAccidentales2VI :{ required: false }, 

			CargoOficioPuesto3VI :{ required: false }, 
			Fuentes3VI :{ required: false }, 
			Meses3VI :{ required: false }, 
			HorasDia3VI :{ required: false }, 
			NivelAmbiental3VI :{ required: false }, 
			FMDia3VI :{ required: false }, 
			FMMes3VI :{ required: false }, 
			FMAnio3VI :{ required: false }, 
			DosisRuido3VI :{ required: false }, 
			FecMedDia3VI :{ required: false }, 
			FecMedMes3VI :{ required: false }, 
			FecMEdAnio3VI :{ required: false }, 
			ExpSusQuimimcas3VI :{ required: false }, 
			ExpoAccPrevias3VI :{ required: false }, 

			CargoOficioPuesto3VI1 :{ required: false }, 
			Fuentes3VI1 :{ required: false }, 
			Meses3VI1 :{ required: false }, 
			HorasDia3VI1 :{ required: false }, 
			NivelAmbiental3VI1 :{ required: false }, 
			FMDia3VI1 :{ required: false }, 
			FMMes3VI1 :{ required: false }, 
			FMAnio3VI1 :{ required: false }, 
			DosisRuido3VI1 :{ required: false }, 
			FecMedDia3VI1 :{ required: false }, 
			FecMedMes3VI1 :{ required: false }, 
			FecMEdAnio3VI1 :{ required: false }, 
			ExpSusQuimimcas3VI1 :{ required: false }, 
			ExpoAccPrevias3VI1 :{ required: false }, 

			CargoOficioPuesto3VI2 :{ required: false }, 
			Fuentes3VI2 :{ required: false }, 
			Meses3VI2 :{ required: false }, 
			HorasDia3VI2 :{ required: false }, 
			NivelAmbiental3VI2 :{ required: false }, 
			FMDia3VI2 :{ required: false }, 
			FMMes3VI2 :{ required: false }, 
			FMAnio3VI2 :{ required: false }, 
			DosisRuido3VI2 :{ required: false }, 
			FecMedDia3VI2 :{ required: false }, 
			FecMedMes3VI2 :{ required: false }, 
			FecMEdAnio3VI2 :{ required: false }, 
			ExpSusQuimimcas3VI2 :{ required: false }, 
			ExpoAccPrevias3VI2 :{ required: false }, 


			CargoOficioPuesto3VI3 :{ required: false }, 
			Fuentes3VI3 :{ required: false }, 
			Meses3VI3 :{ required: false }, 
			HorasDia3VI3 :{ required: false }, 
			NivelAmbiental3VI3 :{ required: false }, 
			FMDia3VI3 :{ required: false }, 
			FMMes3VI3 :{ required: false }, 
			FMAnio3VI3 :{ required: false }, 
			DosisRuido3VI3 :{ required: false }, 
			FecMedDia3VI3 :{ required: false }, 
			FecMedMes3VI3 :{ required: false }, 
			FecMEdAnio3VI3 :{ required: false }, 
			ExpSusQuimimcas3VI3 :{ required: false }, 
			ExpoAccPrevias3VI3 :{ required: false }, 

			CargoOficio4VI1 :{ required: false }, 
			DescActividad4VI1 :{ required: false }, 
			Duracion4VI1 :{ required: false }, 
			FrecActividad4VI1 :{ required: false }, 
			TipoTrabajoActividad4VI1 :{ required: false }, 
			WBTG4VI1 :{ required: false }, 
			TipoExpMeses4VI1 :{ required: false }, 
			TipoExpHD4VI1 :{ required: false }, 
			TasaTrabajo4VI1 :{ required: false }, 
			FechaMedDia4VI1 :{ required: false }, 
			FechaMedMes4VI1 :{ required: false }, 
			FechaMedAnio4VI1 :{ required: false }, 

			CargoOficio4VI2 :{ required: false }, 
			DescActividad4VI2 :{ required: false }, 
			Duracion4VI2 :{ required: false }, 
			FrecActividad4VI2 :{ required: false }, 
			TipoTrabajoActividad4VI2 :{ required: false }, 
			WBTG4VI2 :{ required: false }, 
			TipoExpMeses4VI2 :{ required: false }, 
			TipoExpHD4VI2 :{ required: false }, 
			TasaTrabajo4VI2 :{ required: false }, 
			FechaMedDia4VI2 :{ required: false }, 
			FechaMedMes4VI2 :{ required: false }, 
			FechaMedAnio4VI2 :{ required: false }, 


			CargoOficio4VI3 :{ required: false }, 
			DescActividad4VI3 :{ required: false }, 
			Duracion4VI3 :{ required: false }, 
			FrecActividad4VI3 :{ required: false }, 
			TipoTrabajoActividad4VI3 :{ required: false }, 
			WBTG4VI3 :{ required: false }, 
			TipoExpMeses4VI3 :{ required: false }, 
			TipoExpHD4VI3 :{ required: false }, 
			TasaTrabajo4VI3 :{ required: false }, 
			FechaMedDia4VI3 :{ required: false }, 
			FechaMedMes4VI3 :{ required: false }, 
			FechaMedAnio4VI3 :{ required: false }, 

			CargoOficio4VI4 :{ required: false }, 
			DescActividad4VI4 :{ required: false }, 
			Duracion4VI4 :{ required: false }, 
			FrecActividad4VI4 :{ required: false }, 
			TipoTrabajoActividad4VI4 :{ required: false }, 
			WBTG4VI4 :{ required: false }, 
			TipoExpMeses4VI4 :{ required: false }, 
			TipoExpHD4VI4 :{ required: false }, 
			TasaTrabajo4VI4 :{ required: false }, 
			FechaMedDia4VI4 :{ required: false }, 
			FechaMedMes4VI4 :{ required: false }, 
			FechaMedAnio4VI4 :{ required: false }, 

			RadCargoEmpresa5VI1 :{ required: false }, 
			RadDescripcionFuente5VI1 :{ required: false }, 
			RadDescripcionAct5VI1 :{ required: false }, 
			RadCondiciones5VI1 :{ required: false }, 
			RadTEDia5VI1 :{ required: false }, 
			RadTEMes5VI1 :{ required: false }, 
			RadTEAnio5VI1 :{ required: false }, 
			RadEvalAmbiental5VI1 :{ required: false }, 
			RadFMDia5VI1 :{ required: false }, 
			RadFMMes5VI1 :{ required: false }, 
			RadFMAnio5VI1 :{ required: false }, 

			RadCargoEmpresa5VI2 :{ required: false }, 
			RadDescripcionFuente5VI2 :{ required: false }, 
			RadDescripcionAct5VI2 :{ required: false }, 
			RadCondiciones5VI2 :{ required: false }, 
			RadTEDia5VI2 :{ required: false }, 
			RadTEMes5VI2 :{ required: false }, 
			RadTEAnio5VI2 :{ required: false }, 
			RadEvalAmbiental5VI2 :{ required: false }, 
			RadFMDia5VI2 :{ required: false }, 
			RadFMMes5VI2 :{ required: false }, 
			RadFMAnio5VI2 :{ required: false }, 


			RadCargoEmpresa5VI3 :{ required: false }, 
			RadDescripcionFuente5VI3 :{ required: false }, 
			RadDescripcionAct5VI3 :{ required: false }, 
			RadCondiciones5VI3 :{ required: false }, 
			RadTEDia5VI3 :{ required: false }, 
			RadTEMes5VI3 :{ required: false }, 
			RadTEAnio5VI3 :{ required: false }, 
			RadEvalAmbiental5VI3 :{ required: false }, 
			RadFMDia5VI3 :{ required: false }, 
			RadFMMes5VI3 :{ required: false }, 
			RadFMAnio5VI3 :{ required: false }, 


			RadCargoEmpresa5VI4 :{ required: false }, 
			RadDescripcionFuente5VI4 :{ required: false }, 
			RadDescripcionAct5VI4 :{ required: false }, 
			RadCondiciones5VI4 :{ required: false }, 
			RadTEDia5VI4 :{ required: false }, 
			RadTEMes5VI4 :{ required: false }, 
			RadTEAnio5V4 :{ required: false }, 
			RadEvalAmbiental5VI4 :{ required: false }, 
			RadFMDia5VI4 :{ required: false }, 
			RadFMMes5VI4 :{ required: false }, 
			RadFMAnio5VI4 :{ required: false }, 

			VibCargoEmpresa6VI1 :{ required: false }, 
			VibDescFuente6VI1 :{ required: false }, 
			//BooTipoVibCE6VI1 :{ required: false }, 
			//BooTipoVibMB6VI1 :{ required: false }, 
			TiempoExpMeses6VI1 :{ required: false }, 
			TiempoExpHD6VI1 :{ required: false }, 
			VCE6VI1 :{ required: false }, 
			VMB6VI1 :{ required: false }, 
			AceTotal6VI1 :{ required: false }, 
			EjeDominante6VI1 :{ required: false }, 
			AceEjeDominante6VI1 :{ required: false }, 
			Frecuencia6VI1 :{ required: false }, 
			Aceleracion6VI1 :{ required: false }, 
			FechaMedDia6VI1 :{ required: false }, 
			FechaMedMes6VI1 :{ required: false }, 
			FechaMedAnio6VI1 :{ required: false }, 
			//BooExpoRuido6VI1 :{ required: false }, 

			VibCargoEmpresa6VI2 :{ required: false }, 
			VibDescFuente6VI2 :{ required: false }, 
			//BooTipoVibCE6VI2 :{ required: false }, 
			//BooTipoVibMB6VI2 :{ required: false }, 
			TiempoExpMeses6VI2 :{ required: false }, 
			TiempoExpHD6VI2 :{ required: false }, 
			VCE6VI2 :{ required: false }, 
			VMB6VI2 :{ required: false }, 
			AceTotal6VI2 :{ required: false }, 
			EjeDominante6VI2 :{ required: false }, 
			AceEjeDominante6VI2 :{ required: false }, 
			Frecuencia6VI2 :{ required: false }, 
			Aceleracion6VI2 :{ required: false }, 
			FechaMedDia6VI2 :{ required: false }, 
			FechaMedMes6VI2 :{ required: false }, 
			FechaMedAnio6VI2 :{ required: false }, 
			//BooExpoRuido6VI2 :{ required: false }, 

			VibCargoEmpresa6VI3 :{ required: false }, 
			VibDescFuente6VI3 :{ required: false }, 
			//BooTipoVibCE6VI3 :{ required: false }, 
			//BooTipoVibMB6VI3 :{ required: false }, 
			TiempoExpMeses6VI3 :{ required: false }, 
			TiempoExpHD6VI3 :{ required: false }, 
			VCE6VI3 :{ required: false }, 
			VMB6VI3 :{ required: false }, 
			AceTotal6VI3 :{ required: false }, 
			EjeDominante6VI3 :{ required: false }, 
			AceEjeDominante6VI3 :{ required: false }, 
			Frecuencia6VI3 :{ required: false }, 
			Aceleracion6VI3 :{ required: false }, 
			FechaMedDia6VI3 :{ required: false }, 
			FechaMedMes6VI3 :{ required: false }, 
			FechaMedAnio6VI3 :{ required: false }, 
			//BooExpoRuido6VI3 :{ required: false }, 

			VibCargoEmpresa6VI4 :{ required: false }, 
			VibDescFuente6VI4 :{ required: false }, 
			//BooTipoVibCE6VI4 :{ required: false }, 
			//BooTipoVibMB6VI4 :{ required: false }, 
			TiempoExpMeses6VI4 :{ required: false }, 
			TiempoExpHD6VI4 :{ required: false }, 
			VCE6VI4 :{ required: false }, 
			VMB6VI4 :{ required: false }, 
			AceTotal6VI4 :{ required: false }, 
			EjeDominante6VI4 :{ required: false }, 
			AceEjeDominante6VI4 :{ required: false }, 
			Frecuencia6VI4 :{ required: false }, 
			Aceleracion6VI4 :{ required: false }, 
			FechaMedDia6VI4 :{ required: false }, 
			FechaMedMes6VI4 :{ required: false }, 
			FechaMedAnio6VI4 :{ required: false }, 
			//BooExpoRuido6VI4 :{ required: false }, 

			VibCargoEmpresa6VI5 :{ required: false }, 
			VibDescFuente6VI5 :{ required: false }, 
			//BooTipoVibCE6VI5 :{ required: false }, 
			//BooTipoVibMB6VI5 :{ required: false }, 
			TiempoExpMeses6VI5 :{ required: false }, 
			TiempoExpHD6VI5 :{ required: false }, 
			VCE6VI5 :{ required: false }, 
			VMB6VI5 :{ required: false }, 
			AceTotal6VI5 :{ required: false }, 
			EjeDominante6VI5 :{ required: false }, 
			AceEjeDominante6VI5 :{ required: false }, 
			Frecuencia6VI5 :{ required: false }, 
			Aceleracion6VI5 :{ required: false }, 
			FechaMedDia6VI5 :{ required: false }, 
			FechaMedMes6VI5 :{ required: false }, 
			FechaMedAnio6VI5 :{ required: false }, 
			//BooExpoRuido6VI5 :{ required: false }, 

			VibCargoEmpresa6VI6 :{ required: false }, 
			VibDescFuente6VI6 :{ required: false }, 
			//BooTipoVibCE6VI6 :{ required: false }, 
			//BooTipoVibMB6VI6 :{ required: false }, 
			TiempoExpMeses6VI6 :{ required: false }, 
			TiempoExpHD6VI6 :{ required: false }, 
			VCE6VI6 :{ required: false }, 
			VMB6VI6 :{ required: false }, 
			AceTotal6VI6 :{ required: false }, 
			EjeDominante6VI6 :{ required: false }, 
			AceEjeDominante6VI6 :{ required: false }, 
			Frecuencia6VI6 :{ required: false }, 
			Aceleracion6VI6 :{ required: false }, 
			FechaMedDia6VI6 :{ required: false }, 
			FechaMedMes6VI6 :{ required: false }, 
			FechaMedAnio6VI6 :{ required: false }, 
			//BooExpoRuido6VI6 :{ required: false }, 

			DescEventoInv6VI :{ required: false }, 


			FrecPresAltoVI1 :{ required: false }, 
			FrecPresMedioVI1 :{ required: false }, 
			FrecPresBajoVI1 :{ required: false }, 
			TiempoExpAltoVI1 :{ required: false }, 
			TiempoExpMedioVI1 :{ required: false }, 
			TiempoExpBajoVI1 :{ required: false }, 
			IntensidadAltoVI1 :{ required: false }, 
			IntensidadMedioVI1 :{ required: false }, 
			IntensidadBajoVI1 :{ required: false }, 
			VarPsicoObservacionesVI1 :{ required: false }, 

			FrecPresAltoVI2 :{ required: false }, 
			FrecPresMedioVI2 :{ required: false }, 
			FrecPresBajoVI2 :{ required: false }, 
			TiempoExpAltoVI2 :{ required: false }, 
			TiempoExpMedioVI2 :{ required: false }, 
			TiempoExpBajoVI2 :{ required: false }, 
			IntensidadAltoVI2 :{ required: false }, 
			IntensidadMedioVI2 :{ required: false }, 
			IntensidadBajoVI2 :{ required: false }, 
			VarPsicoObservacionesVI2 :{ required: false }, 


			FrecPresAltoVI3 :{ required: false }, 
			FrecPresMedioVI3 :{ required: false }, 
			FrecPresBajoVI3 :{ required: false }, 
			TiempoExpAltoVI3 :{ required: false }, 
			TiempoExpMedioVI3 :{ required: false }, 
			TiempoExpBajoVI3 :{ required: false }, 
			IntensidadAltoVI3 :{ required: false }, 
			IntensidadMedioVI3 :{ required: false }, 
			IntensidadBajoVI3 :{ required: false }, 
			VarPsicoObservacionesVI3 :{ required: false }, 

			FrecPresAltoVI4 :{ required: false }, 
			FrecPresMedioVI4 :{ required: false }, 
			FrecPresBajoVI4 :{ required: false }, 
			TiempoExpAltoVI4 :{ required: false }, 
			TiempoExpMedioVI4 :{ required: false }, 
			TiempoExpBajoV4 :{ required: false }, 
			IntensidadAltoVI4 :{ required: false }, 
			IntensidadMedioVI4 :{ required: false }, 
			IntensidadBajoVI4 :{ required: false }, 
			VarPsicoObservacionesVI4 :{ required: false }, 

			IntensidadAltaVI1 :{ required: false }, 
			IntensidadMediaVI1 :{ required: false }, 
			IntensidadBajaVI1 :{ required: false }, 
			IntensidadObservVI1 :{ required: false }, 

			IntensidadAltaVI2 :{ required: false }, 
			IntensidadMediaVI2 :{ required: false }, 
			IntensidadBajaVI2 :{ required: false }, 
			IntensidadObservVI2 :{ required: false }, 

			NivelRiesgoLabVI :{ required: false }, 
			NivelRiesgoExtralabVI :{ required: false }, 
			NivelRiesgoIndiviVI :{ required: false }, 
			NivelEstresVI :{ required: false }, 

			//BooPostPieProlongada :{ required: false }, 
			//BooPostPieSedente :{ required: false }, 
			//BooPosturaIncomodaBrazosManos :{ required: false }, 
			//BooEsfuerzoBrazosManos :{ required: false }, 
			//BooPosturaIncomodaEspalda :{ required: false }, 
			//BooLabRepetitivaColumna :{ required: false }, 
			//BooLabRepetitivaBrazoMuMano :{ required: false }, 
			//BooPeriodoRecuperacionFisica :{ required: false }, 
			//BooEsfuerzoManos :{ required: false }, 
			//BooEsfuerzoCuerpo :{ required: false }, 
			//BooManipulacionCargas :{ required: false }, 
			DMEResumen :{ required: false }, 

			//BooCauRelPrevVI1 :{ required: false }, 	
			CauRelPrevVI1 :{ required: false }, 
			//BooCauRelPrevVI2 :{ required: false }, 	
			CauRelPrevVI2 :{ required: false }, 
			//BooCauRelPrevVI3 :{ required: false }, 	
			CauRelPrevVI3 :{ required: false }, 
			//BooCauRelPrevVI4 :{ required: false }, 	
			CauRelPrevVI4 :{ required: false }, 
			//BooCauRelPrevVI5 :{ required: false }, 	
			CauRelPrevVI5 :{ required: false }, 
			//BooCauRelPrevVI6 :{ required: false }, 	
			CauRelPrevVI6 :{ required: false }, 
			//BooCauRelPrevVI7 :{ required: false }, 	
			CauRelPrevVI7 :{ required: false }, 
			//BooCauRelPrevVI8 :{ required: false }, 	
			CauRelPrevVI8 :{ required: false }, 
			//BooCauRelPrevVI9 :{ required: false }, 	
			CauRelPrevVI9 :{ required: false }, 
			//BooCauRelPrevVI10 :{ required: false }, 	
			CauRelPrevVI10 :{ required: false }, 
			//BooCauRelPrevVI11 :{ required: false }, 	
			CauRelPrevVI11 :{ required: false }, 
			//BooCauRelPrevVI12 :{ required: false }, 
			CauRelPrevVI12 :{ required: false }, 

			OtrosDatosInteresVI :{ required: false }, 
			CausasEnfermedadLaboralVI :{ required: false }, 

			MedidasPreventivasVII1 :{ required: true }, 
			ResponsableImplementacionVII1 :{ required: true }, 
			FechaEjeMesVII1 :{ required: true }, 
			FechaEjeDiaVII1 :{ required: true }, 

			MedidasPreventivasVII2 :{ required: true }, 
			ResponsableImplementacionVII2 :{ required: true }, 
			FechaEjeMesVII3 :{ required: true }, 
			FechaEjeDiaVII3 :{ required: true }, 

			MedidasPreventivasVII4 :{ required: true }, 
			ResponsableImplementacionVII4 :{ required: true }, 
			FechaEjeMesVII4 :{ required: true }, 
			FechaEjeDiaVII4 :{ required: true }, 

			MedidasPreventivasVII5 :{ required: true }, 
			ResponsableImplementacionVII5 :{ required: true }, 
			FechaEjeMesVII5 :{ required: true }, 
			FechaEjeDiaVII5 :{ required: true }, 

			MedidasPreventivasVII6 :{ required: true }, 
			ResponsableImplementacionVII6 :{ required: true }, 
			FechaEjeMesVII6 :{ required: true }, 
			FechaEjeDiaVII6 :{ required: true }, 

			MedidasPreventivasVII7 :{ required: true }, 
			ResponsableImplementacionVII7 :{ required: true }, 
			FechaEjeMesVII7 :{ required: true }, 
			FechaEjeDiaVII7 :{ required: true }, 

			MedidasPreventivasVII8 :{ required: true }, 
			ResponsableImplementacionVII8 :{ required: true }, 
			FechaEjeMesVII8 :{ required: true }, 
			FechaEjeDiaVII8 :{ required: true }, 

			TipoIdentificacionVIII1 :{ required: true }, 
			JefeInmediatoVIII1 :{ required: true }, 
			CargoVIII1 :{ required: true }, 
			NumeroIdentificacionVIII1 :{ required: true }, 

			TipoIdentificacionVIII2 :{ required: true }, 
			JefeInmediatoVIII2 :{ required: true }, 
			CargoVIII2 :{ required: true }, 
			NumeroIdentificacionVIII2 :{ required: true }, 

			TipoIdentificacionVIII3 :{ required: true }, 
			JefeInmediatoVIII3 :{ required: true }, 
			CargoVIII3 :{ required: true }, 
			NumeroIdentificacionVIII3 :{ required: true }, 

			TipoIdentificacionVIII4 :{ required: true }, 
			JefeInmediatoVIII4 :{ required: true }, 
			CargoVIII4 :{ required: true }, 
			NumeroIdentificacionVIII4 :{ required: true }, 

			TipoIdentificacionVIII5 :{ required: true }, 
			JefeInmediatoVIII5 :{ required: true }, 
			CargoVIII5 :{ required: true }, 
			NumeroIdentificacionVIII5 :{ required: true }, 

			TipoIdentificacionVIII6 :{ required: true }, 
			JefeInmediatoVIII6 :{ required: true }, 
			CargoVIII6 :{ required: true }, 
			NumeroIdentificacionVIII6 :{ required: true }, 


			TipoIdentificacionVIII7 :{ required: true }, 
			EspecialistaOcupacionalVIII :{ required: true }, 
			LicenciaNumVIII1 :{ required: true }, 
			LicenciaAnioVIII1 :{ required: true }, 
			NumeroIdentificacionVIII7 :{ required: true }, 


			TipoIdentificacionVIII8 :{ required: true }, 
			RepresentanteArlVIII8 :{ required: true }, 
			LicenciaNumeroVIII8 :{ required: true }, 
			LicenciaAnioVIII8 :{ required: true }, 
			NumeroIdentificacionVIII8 :{ required: true }, 
			EmpresaRepresentaVIII8 :{ required: true }, 
			NitVIII8 :{ required: true }, 

			FechaRemisionIX :{ required: true }, 
			NoFoliosIX :{ required: true }, 
			TipoIdentificacionIX :{ required: true }, 
			NombreApellidoIX :{ required: true }, 
			CargoIX :{ required: true }, 
			NumeroIdentificacionIX :{ required: true }, 

			FechaRemisionARLIX :{ required: true }, 
			FecRemisionTerritorialIX     :{ required: true }, 
			DisponibleRemisionARLIX :{ required: true }, 
			ResponsablesRemisionARLIX :{ required: true }, 
			CargoARLIX :{ required: true }, 

			TipoIdentificacionX :{ required: true }, 
			ResponsableVerficiacionX :{ required: true }, 
			CargoX :{ required: true }, 
			NumeroIdentificacionX :{ required: true }, 

			MedidasIntervencionX :{ required: true }, 
			ObsevacionesX :{ required: true }, 
			FechaVerficacionX :{ required: true }, 


			TipoIdentificacionXI :{ required: true }, 
			ResponsableVerficiacionXI :{ required: true }, 
			CargoXI :{ required: true }, 
			NumeroIdentificacionXI :{ required: true }, 

			MedidasIntervencionXI :{ required: true }, 
			ObsevacionesARLXI :{ required: true }, 
			FechaVerficacionXI :{ required: true } 
		},
        messages: {
			EnfLabCalificadaI :{ required: "Este campo es requerido" },
			FechaInvestigacionI :{ required: "Este campo es requerido" }, 
			DepartamentoI :{ required: "Este campo es requerido" }, 
			MunicipioI :{ required: "Este campo es requerido" }, 
			DireccionI :{ required: "Este campo es requerido" }, 
			NombresApellidosI :{ required: "Este campo es requerido" }, 
			ProfesionalI :{ required: "Este campo es requerido" }, 
			NoLicenciaI :{ required: "Este campo es requerido" }, 
			FotografiasI :{ required: "Este campo es requerido" }, 
			IlustracionesI :{ required: "Este campo es requerido" }, 
			DiagramasI :{ required: "Este campo es requerido" }, 
			OtrosCualesI :{ required: "Este campo es requerido" }, 


			EmpleadorII :{ required: "Este campo es requerido" }, 
			ContratanteII :{ required: "Este campo es requerido" }, 
			IndependienteII :{ required: "Este campo es requerido" }, 
			CooperativaII :{ required: "Este campo es requerido" }, 
			AgremiacionII :{ required: "Este campo es requerido" }, 
			AsociacionII :{ required: "Este campo es requerido" }, 
			CodActividadII :{ required: "Este campo es requerido" }, 
			ActividadPrincipalII :{ required: "Este campo es requerido" }, 
			RazonSocialII :{ required: "Este campo es requerido" }, 
			TipoIdentificacionII :{ required: "Este campo es requerido" }, 
			NumIdentificacionII :{ required: "Este campo es requerido" }, 

			DireccionPrincipalII :{ required: "Este campo es requerido" }, 
			TelefonoPpalII :{ required: "Este campo es requerido" }, 
			FaxII :{ required: "Este campo es requerido" }, 
			DeptoPpalII :{ required: "Este campo es requerido" }, 
			McpioPpalII :{ required: "Este campo es requerido" }, 
			EmailII :{ required: "Este campo es requerido" }, 
			//boZonaPpalII :{ required: "Este campo es requerido" }, 
			CentroTrabajoPpalII :{ required: "Este campo es requerido" }, 

			CentroCostoTelefonoII :{ required: "Este campo es requerido" }, 
			CentroCostoFaxII :{ required: "Este campo es requerido" }, 
			CodActEconoPpalII :{ required: "Este campo es requerido" }, 
			ActEconoCentroTrabajoII :{ required: "Este campo es requerido" }, 
			DeptoEmpleadorII :{ required: "Este campo es requerido" }, 
			McpioEmpleadorII :{ required: "Este campo es requerido" }, 
			EmailEmpleadorII :{ required: "Este campo es requerido" }, 
			//boZonaEmpleadorII :{ required: "Este campo es requerido" }, 
			DeptoCentroTrabajoII :{ required: "Este campo es requerido" }, 
			McpioCentroTrabajoII :{ required: "Este campo es requerido" }, 


			PlantaIII :{ required: "Este campo es requerido" }, 
			MisionIII :{ required: "Este campo es requerido" }, 
			CooperadorIII :{ required: "Este campo es requerido" }, 
			EstudianteIII :{ required: "Este campo es requerido" }, 
			IndependienteIII :{ required: "Este campo es requerido" }, 
			TipoIdentificacionIII :{ required: "Este campo es requerido" }, 
			NumIdentificacionIII :{ required: "Este campo es requerido" }, 
			PrimerApellidoIII :{ required: "Este campo es requerido" }, 
			SegundoApellidoIII :{ required: "Este campo es requerido" }, 
			PrimerNombreIII :{ required: "Este campo es requerido" }, 
			SegundoNombreIII :{ required: "Este campo es requerido" }, 
			FechaNacimientoIII :{ required: "Este campo es requerido" }, 
			SexoIII :{ required: "Este campo es requerido" }, 
			EPSAfiliadoIII :{ required: "Este campo es requerido" }, 
			AFPAfiliadoIII :{ required: "Este campo es requerido" }, 
			ARLAfiliadoIII :{ required: "Este campo es requerido" }, 
			TelefonoIII :{ required: "Este campo es requerido" }, 
			FaxIII  :{ required: "Este campo es requerido" }, 
			EmailTrabajadorIII :{ required: "Este campo es requerido" }, 
			DireccionTrabajadorIII :{ required: "Este campo es requerido" }, 
			//boZonaIII :{ required: "Este campo es requerido" }, 


			CargoIV :{ required: "Este campo es requerido" }, 
			AntiguedadCargoAIV :{ required: "Este campo es requerido" }, 
			AntiguedadCargoMIV :{ required: "Este campo es requerido" }, 
			CodOcupacionIV :{ required: "Este campo es requerido" }, 
			OcupacionHabitualIV :{ required: "Este campo es requerido" }, 
			FechaMuerteIV :{ required: "Este campo es requerido" }, 
			AreaActualIV :{ required: "Este campo es requerido" }, 
			NombreCargoIV :{ required: "Este campo es requerido" }, 
			AntiguedadCargoAnioIV :{ required: "Este campo es requerido" }, 
			AntiguedadCargoMesesIV :{ required: "Este campo es requerido" }, 
			DiurnoIV :{ required: "Este campo es requerido" }, 
			NocturnoIV :{ required: "Este campo es requerido" }, 
			MixtoIV :{ required: "Este campo es requerido" }, 
			TurnosIV :{ required: "Este campo es requerido" }, 
			CondicionesPuestoTrabajoIV :{ required: "Este campo es requerido" }, 

			TareasCargo1IV :{ required: "Este campo es requerido" }, 
			DedicacionJL1IV :{ required: "Este campo es requerido" }, 
			DedicacionJL11IV :{ required: "Este campo es requerido" }, 
			DedicacionJL12IV :{ required: "Este campo es requerido" }, 
			RelacionMuyProbable1IV :{ required: "Este campo es requerido" }, 
			RelacionProbable1IV :{ required: "Este campo es requerido" }, 
			RelacionPocoProbable1IV :{ required: "Este campo es requerido" }, 
			DedicacionJL21IV :{ required: "Este campo es requerido" }, 
			DedicacionJL22IV :{ required: "Este campo es requerido" }, 
			DedicacionJL23IV :{ required: "Este campo es requerido" }, 
			RelacionMuyProbable2IV :{ required: "Este campo es requerido" }, 
			RelacionProbable2IV :{ required: "Este campo es requerido" }, 
			RelacionPocoProbable2IV :{ required: "Este campo es requerido" }, 

			TareasCargo3IV :{ required: "Este campo es requerido" }, 
			DedicacionJL31IV :{ required: "Este campo es requerido" }, 
			DedicacionJL32IV :{ required: "Este campo es requerido" }, 
			DedicacionJL33IV :{ required: "Este campo es requerido" }, 
			RelacionMuyProbable3IV :{ required: "Este campo es requerido" }, 
			RelacionProbable3IV :{ required: "Este campo es requerido" }, 
			RelacionPocoProbable3IV :{ required: "Este campo es requerido" }, 

			TareasCargo4IV :{ required: "Este campo es requerido" }, 
			DedicacionJL41IV :{ required: "Este campo es requerido" }, 
			DedicacionJL42IV :{ required: "Este campo es requerido" }, 
			DedicacionJL43IV :{ required: "Este campo es requerido" }, 
			RelacionMuyProbable4IV :{ required: "Este campo es requerido" }, 
			RelacionProbable4IV :{ required: "Este campo es requerido" }, 
			RelacionPocoProbable4IV :{ required: "Este campo es requerido" }, 

			FormacionInformacionIV :{ required: "Este campo es requerido" }, 
			ProteccionColectivaIV :{ required: "Este campo es requerido" }, 
			EPPIV :{ required: "Este campo es requerido" },   
			DiseñoPuestoTrabajoIV :{ required: "Este campo es requerido" },  
			OrganizacionTrabajoIV :{ required: "Este campo es requerido" }, 
			PreventivasIV :{ required: "Este campo es requerido" }, 
			ImplementadasIV :{ required: "Este campo es requerido" }, 
			DescripcionIV :{ required: "Este campo es requerido" }, 

			CodigoCie1 :{ required: "Este campo es requerido" }, 
			CodigoCie2 :{ required: "Este campo es requerido" }, 
			CodigoCie3 :{ required: "Este campo es requerido" }, 
			CodigoCie4 :{ required: "Este campo es requerido" }, 
			DiagnosticoIV1 :{ required: "Este campo es requerido" }, 
			DiagnosticoIV2 :{ required: "Este campo es requerido" }, 
			DiagnosticoIV3 :{ required: "Este campo es requerido" }, 
			DiagnosticoIV4 :{ required: "Este campo es requerido" }, 


			FechaOrigenELV :{ required: "Este campo es requerido" }, 
			OrigenLaboralIV :{ required: "Este campo es requerido" }, 
			NoTrabajadoresV :{ required: "Este campo es requerido" }, 
			CargosSimilaresV :{ required: "Este campo es requerido" }, 

			NombresApellidosV1 :{ required: "Este campo es requerido" }, 
			NombresApellidosV2 :{ required: "Este campo es requerido" }, 
			NombresApellidosV3 :{ required: "Este campo es requerido" }, 
			NombresApellidosV4 :{ required: "Este campo es requerido" }, 

			AnioDiagnosticoV1 :{ required: "Este campo es requerido" }, 
			AnioDiagnosticoV2 :{ required: "Este campo es requerido" }, 
			AnioDiagnosticoV3 :{ required: "Este campo es requerido" }, 
			AnioDiagnosticoV4 :{ required: "Este campo es requerido" }, 


			PuestoEmpresaVI1 :{ required: "Este campo es requerido" }, 
			AgentesBiologicosVI1 :{ required: "Este campo es requerido" }, 
			FrasesVI1 :{ required: "Este campo es requerido" }, 
			RutinariaVI1 :{ required: "Este campo es requerido" }, 
			NORutinariaVI1 :{ required: "Este campo es requerido" }, 
			TiempoExposicionMesesVI1 :{ required: "Este campo es requerido" }, 
			TiempoExposicionHorasVI1 :{ required: "Este campo es requerido" }, 
			TLVCorregidoVI1 :{ required: "Este campo es requerido" }, 
			ConcentracionHalladaVI1 :{ required: "Este campo es requerido" }, 
			FechaMediacionDiaV1 :{ required: "Este campo es requerido" }, 
			FechaMediaMesV1 :{ required: "Este campo es requerido" }, 
			FechaMediaAnioV1 :{ required: "Este campo es requerido" }, 
			NivelRiesgoV1 :{ required: "Este campo es requerido" }, 
			ViaEntradaV1 :{ required: "Este campo es requerido" }, 

			PuestoEmpresaVI2 :{ required: "Este campo es requerido" }, 
			AgentesBiologicosVI2 :{ required: "Este campo es requerido" }, 
			FrasesVI2 :{ required: "Este campo es requerido" }, 
			RutinariaVI2 :{ required: "Este campo es requerido" }, 
			NORutinariaVI2 :{ required: "Este campo es requerido" }, 
			TiempoExposicionMesesVI2 :{ required: "Este campo es requerido" }, 
			TiempoExposicionHorasVI2 :{ required: "Este campo es requerido" }, 
			TLVCorregidoVI2 :{ required: "Este campo es requerido" }, 
			ConcentracionHalladaVI2 :{ required: "Este campo es requerido" }, 
			FechaMediacionDiaV2 :{ required: "Este campo es requerido" }, 
			FechaMediaMesV2 :{ required: "Este campo es requerido" }, 
			FechaMediaAnioV2 :{ required: "Este campo es requerido" }, 
			NivelRiesgoV2 :{ required: "Este campo es requerido" }, 
			ViaEntradaV2 :{ required: "Este campo es requerido" }, 

			PuestoEmpresaVI3 :{ required: "Este campo es requerido" }, 
			AgentesBiologicosVI3 :{ required: "Este campo es requerido" }, 
			FrasesVI3 :{ required: "Este campo es requerido" }, 
			RutinariaVI3 :{ required: "Este campo es requerido" }, 
			NORutinariaVI3 :{ required: "Este campo es requerido" }, 
			TiempoExposicionMesesVI3 :{ required: "Este campo es requerido" }, 
			TiempoExposicionHorasVI3 :{ required: "Este campo es requerido" }, 
			TLVCorregidoVI3 :{ required: "Este campo es requerido" }, 
			ConcentracionHalladaVI3 :{ required: "Este campo es requerido" }, 
			FechaMediacionDiaV3 :{ required: "Este campo es requerido" }, 
			FechaMediaMesV3 :{ required: "Este campo es requerido" }, 
			FechaMediaAnioV3 :{ required: "Este campo es requerido" }, 
			NivelRiesgoV3 :{ required: "Este campo es requerido" }, 
			ViaEntradaV3 :{ required: "Este campo es requerido" }, 

			PuestoEmpresaVI4 :{ required: "Este campo es requerido" }, 
			AgentesBiologicosVI4 :{ required: "Este campo es requerido" }, 
			FrasesVI4 :{ required: "Este campo es requerido" }, 
			RutinariaVI4 :{ required: "Este campo es requerido" }, 
			NORutinariaVI4 :{ required: "Este campo es requerido" }, 
			TiempoExposicionMesesVI4 :{ required: "Este campo es requerido" }, 
			TiempoExposicionHorasVI4 :{ required: "Este campo es requerido" }, 
			TLVCorregidoVI4 :{ required: "Este campo es requerido" }, 
			ConcentracionHalladaVI4 :{ required: "Este campo es requerido" }, 
			FechaMediacionDiaVI4 :{ required: "Este campo es requerido" }, 
			FechaMediaMesVI4 :{ required: "Este campo es requerido" }, 
			FechaMediaAnioVI4 :{ required: "Este campo es requerido" }, 
			NivelRiesgoVI4 :{ required: "Este campo es requerido" }, 
			ViaEntradaVI4 :{ required: "Este campo es requerido" }, 

			OficioEmpresa2V1 :{ required: "Este campo es requerido" }, 
			AgenteRelBiologico2VI :{ required: "Este campo es requerido" }, 
			FuenteAgente2VI1 :{ required: "Este campo es requerido" }, 
			MecanismoTransmicion2VI1 :{ required: "Este campo es requerido" }, 
			TipoActividadRutinaria2VI1 :{ required: "Este campo es requerido" }, 
			TipoActividadNoRutinaria2VI1 :{ required: "Este campo es requerido" }, 
			TiempoExposicionMeses2VI1 :{ required: "Este campo es requerido" }, 
			TiempoExposicionHoras2VI1 :{ required: "Este campo es requerido" }, 
			ConcentracionHallada2VI1 :{ required: "Este campo es requerido" }, 
			NivelRiesgo2VI1 :{ required: "Este campo es requerido" }, 
			Dia2VI1 :{ required: "Este campo es requerido" }, 
			Mes2VI1 :{ required: "Este campo es requerido" }, 
			Anio2VI1 :{ required: "Este campo es requerido" }, 
			FrecRiesgo2VI1 :{ required: "Este campo es requerido" }, 

			OficioEmpresa2V2 :{ required: "Este campo es requerido" }, 
			AgenteRelBiologico2VI2 :{ required: "Este campo es requerido" }, 
			FuenteAgente2VI2 :{ required: "Este campo es requerido" }, 
			MecanismoTransmicion2VI2 :{ required: "Este campo es requerido" }, 
			TipoActividadRutinaria2VI2 :{ required: "Este campo es requerido" }, 
			TipoActividadNoRutinaria2VI2 :{ required: "Este campo es requerido" }, 
			TiempoExposicionMeses2VI2 :{ required: "Este campo es requerido" }, 
			TiempoExposicionHoras2VI2 :{ required: "Este campo es requerido" }, 
			ConcentracionHallada2VI2 :{ required: "Este campo es requerido" }, 
			NivelRiesgo2VI2 :{ required: "Este campo es requerido" }, 
			Dia2VI2 :{ required: "Este campo es requerido" }, 
			Mes2VI2 :{ required: "Este campo es requerido" }, 
			Anio2VI2 :{ required: "Este campo es requerido" }, 
			FrecRiesgo2VI2 :{ required: "Este campo es requerido" }, 

			OficioEmpresa2V3 :{ required: "Este campo es requerido" }, 
			AgenteRelBiologico2VI3 :{ required: "Este campo es requerido" }, 
			FuenteAgente2VI3 :{ required: "Este campo es requerido" }, 
			MecanismoTransmicion2VI3 :{ required: "Este campo es requerido" }, 
			TipoActividadRutinaria2VI3 :{ required: "Este campo es requerido" }, 
			TipoActividadNoRutinaria2VI3 :{ required: "Este campo es requerido" }, 
			TiempoExposicionMeses2VI3 :{ required: "Este campo es requerido" }, 
			TiempoExposicionHoras2VI3 :{ required: "Este campo es requerido" }, 
			ConcentracionHallada2VI3 :{ required: "Este campo es requerido" }, 
			NivelRiesgo2VI3 :{ required: "Este campo es requerido" }, 
			Dia2VI3 :{ required: "Este campo es requerido" }, 
			Mes2VI3 :{ required: "Este campo es requerido" }, 
			Anio2VI3 :{ required: "Este campo es requerido" }, 
			FrecRiesgo2VI3 :{ required: "Este campo es requerido" }, 

			OficioEmpresa2V4 :{ required: "Este campo es requerido" }, 
			AgenteRelBiologico2VI4 :{ required: "Este campo es requerido" }, 
			FuenteAgente2VI4 :{ required: "Este campo es requerido" }, 
			MecanismoTransmicion2VI4 :{ required: "Este campo es requerido" }, 
			TipoActividadRutinaria2VI4 :{ required: "Este campo es requerido" }, 
			TipoActividadNoRutinaria2VI4 :{ required: "Este campo es requerido" }, 
			TiempoExposicionMeses2VI4 :{ required: "Este campo es requerido" }, 
			TiempoExposicionHoras2VI4 :{ required: "Este campo es requerido" }, 
			ConcentracionHallada2VI4 :{ required: "Este campo es requerido" }, 
			NivelRiesgo2VI4 :{ required: "Este campo es requerido" }, 
			Dia2VI4 :{ required: "Este campo es requerido" }, 
			Mes2VI4 :{ required: "Este campo es requerido" }, 
			Anio2VI4 :{ required: "Este campo es requerido" }, 
			FrecRiesgo2VI4 :{ required: "Este campo es requerido" }, 
			ExpoAccidentales2VI :{ required: "Este campo es requerido" }, 
			/// <summary>
			/// 
			/// </summary>
			CargoOficioPuesto3VI :{ required: "Este campo es requerido" }, 
			Fuentes3VI :{ required: "Este campo es requerido" }, 
			Meses3VI :{ required: "Este campo es requerido" }, 
			HorasDia3VI :{ required: "Este campo es requerido" }, 
			NivelAmbiental3VI :{ required: "Este campo es requerido" }, 
			FMDia3VI :{ required: "Este campo es requerido" }, 
			FMMes3VI :{ required: "Este campo es requerido" }, 
			FMAnio3VI :{ required: "Este campo es requerido" }, 
			DosisRuido3VI :{ required: "Este campo es requerido" }, 
			FecMedDia3VI :{ required: "Este campo es requerido" }, 
			FecMedMes3VI :{ required: "Este campo es requerido" }, 
			FecMEdAnio3VI :{ required: "Este campo es requerido" }, 
			ExpSusQuimimcas3VI :{ required: "Este campo es requerido" }, 
			ExpoAccPrevias3VI :{ required: "Este campo es requerido" }, 

			CargoOficioPuesto3VI1 :{ required: "Este campo es requerido" }, 
			Fuentes3VI1 :{ required: "Este campo es requerido" }, 
			Meses3VI1 :{ required: "Este campo es requerido" }, 
			HorasDia3VI1 :{ required: "Este campo es requerido" }, 
			NivelAmbiental3VI1 :{ required: "Este campo es requerido" }, 
			FMDia3VI1 :{ required: "Este campo es requerido" }, 
			FMMes3VI1 :{ required: "Este campo es requerido" }, 
			FMAnio3VI1 :{ required: "Este campo es requerido" }, 
			DosisRuido3VI1 :{ required: "Este campo es requerido" }, 
			FecMedDia3VI1 :{ required: "Este campo es requerido" }, 
			FecMedMes3VI1 :{ required: "Este campo es requerido" }, 
			FecMEdAnio3VI1 :{ required: "Este campo es requerido" }, 
			ExpSusQuimimcas3VI1 :{ required: "Este campo es requerido" }, 
			ExpoAccPrevias3VI1 :{ required: "Este campo es requerido" }, 

			CargoOficioPuesto3VI2 :{ required: "Este campo es requerido" }, 
			Fuentes3VI2 :{ required: "Este campo es requerido" }, 
			Meses3VI2 :{ required: "Este campo es requerido" }, 
			HorasDia3VI2 :{ required: "Este campo es requerido" }, 
			NivelAmbiental3VI2 :{ required: "Este campo es requerido" }, 
			FMDia3VI2 :{ required: "Este campo es requerido" }, 
			FMMes3VI2 :{ required: "Este campo es requerido" }, 
			FMAnio3VI2 :{ required: "Este campo es requerido" }, 
			DosisRuido3VI2 :{ required: "Este campo es requerido" }, 
			FecMedDia3VI2 :{ required: "Este campo es requerido" }, 
			FecMedMes3VI2 :{ required: "Este campo es requerido" }, 
			FecMEdAnio3VI2 :{ required: "Este campo es requerido" }, 
			ExpSusQuimimcas3VI2 :{ required: "Este campo es requerido" }, 
			ExpoAccPrevias3VI2 :{ required: "Este campo es requerido" }, 


			CargoOficioPuesto3VI3 :{ required: "Este campo es requerido" }, 
			Fuentes3VI3 :{ required: "Este campo es requerido" }, 
			Meses3VI3 :{ required: "Este campo es requerido" }, 
			HorasDia3VI3 :{ required: "Este campo es requerido" }, 
			NivelAmbiental3VI3 :{ required: "Este campo es requerido" }, 
			FMDia3VI3 :{ required: "Este campo es requerido" }, 
			FMMes3VI3 :{ required: "Este campo es requerido" }, 
			FMAnio3VI3 :{ required: "Este campo es requerido" }, 
			DosisRuido3VI3 :{ required: "Este campo es requerido" }, 
			FecMedDia3VI3 :{ required: "Este campo es requerido" }, 
			FecMedMes3VI3 :{ required: "Este campo es requerido" }, 
			FecMEdAnio3VI3 :{ required: "Este campo es requerido" }, 
			ExpSusQuimimcas3VI3 :{ required: "Este campo es requerido" }, 
			ExpoAccPrevias3VI3 :{ required: "Este campo es requerido" }, 

			CargoOficio4VI1 :{ required: "Este campo es requerido" }, 
			DescActividad4VI1 :{ required: "Este campo es requerido" }, 
			Duracion4VI1 :{ required: "Este campo es requerido" }, 
			FrecActividad4VI1 :{ required: "Este campo es requerido" }, 
			TipoTrabajoActividad4VI1 :{ required: "Este campo es requerido" }, 
			WBTG4VI1 :{ required: "Este campo es requerido" }, 
			TipoExpMeses4VI1 :{ required: "Este campo es requerido" }, 
			TipoExpHD4VI1 :{ required: "Este campo es requerido" }, 
			TasaTrabajo4VI1 :{ required: "Este campo es requerido" }, 
			FechaMedDia4VI1 :{ required: "Este campo es requerido" }, 
			FechaMedMes4VI1 :{ required: "Este campo es requerido" }, 
			FechaMedAnio4VI1 :{ required: "Este campo es requerido" }, 

			CargoOficio4VI2 :{ required: "Este campo es requerido" }, 
			DescActividad4VI2 :{ required: "Este campo es requerido" }, 
			Duracion4VI2 :{ required: "Este campo es requerido" }, 
			FrecActividad4VI2 :{ required: "Este campo es requerido" }, 
			TipoTrabajoActividad4VI2 :{ required: "Este campo es requerido" }, 
			WBTG4VI2 :{ required: "Este campo es requerido" }, 
			TipoExpMeses4VI2 :{ required: "Este campo es requerido" }, 
			TipoExpHD4VI2 :{ required: "Este campo es requerido" }, 
			TasaTrabajo4VI2 :{ required: "Este campo es requerido" }, 
			FechaMedDia4VI2 :{ required: "Este campo es requerido" }, 
			FechaMedMes4VI2 :{ required: "Este campo es requerido" }, 
			FechaMedAnio4VI2 :{ required: "Este campo es requerido" }, 


			CargoOficio4VI3 :{ required: "Este campo es requerido" }, 
			DescActividad4VI3 :{ required: "Este campo es requerido" }, 
			Duracion4VI3 :{ required: "Este campo es requerido" }, 
			FrecActividad4VI3 :{ required: "Este campo es requerido" }, 
			TipoTrabajoActividad4VI3 :{ required: "Este campo es requerido" }, 
			WBTG4VI3 :{ required: "Este campo es requerido" }, 
			TipoExpMeses4VI3 :{ required: "Este campo es requerido" }, 
			TipoExpHD4VI3 :{ required: "Este campo es requerido" }, 
			TasaTrabajo4VI3 :{ required: "Este campo es requerido" }, 
			FechaMedDia4VI3 :{ required: "Este campo es requerido" }, 
			FechaMedMes4VI3 :{ required: "Este campo es requerido" }, 
			FechaMedAnio4VI3 :{ required: "Este campo es requerido" }, 

			CargoOficio4VI4 :{ required: "Este campo es requerido" }, 
			DescActividad4VI4 :{ required: "Este campo es requerido" }, 
			Duracion4VI4 :{ required: "Este campo es requerido" }, 
			FrecActividad4VI4 :{ required: "Este campo es requerido" }, 
			TipoTrabajoActividad4VI4 :{ required: "Este campo es requerido" }, 
			WBTG4VI4 :{ required: "Este campo es requerido" }, 
			TipoExpMeses4VI4 :{ required: "Este campo es requerido" }, 
			TipoExpHD4VI4 :{ required: "Este campo es requerido" }, 
			TasaTrabajo4VI4 :{ required: "Este campo es requerido" }, 
			FechaMedDia4VI4 :{ required: "Este campo es requerido" }, 
			FechaMedMes4VI4 :{ required: "Este campo es requerido" }, 
			FechaMedAnio4VI4 :{ required: "Este campo es requerido" }, 

			RadCargoEmpresa5VI1 :{ required: "Este campo es requerido" }, 
			RadDescripcionFuente5VI1 :{ required: "Este campo es requerido" }, 
			RadDescripcionAct5VI1 :{ required: "Este campo es requerido" }, 
			RadCondiciones5VI1 :{ required: "Este campo es requerido" }, 
			RadTEDia5VI1 :{ required: "Este campo es requerido" }, 
			RadTEMes5VI1 :{ required: "Este campo es requerido" }, 
			RadTEAnio5VI1 :{ required: "Este campo es requerido" }, 
			RadEvalAmbiental5VI1 :{ required: "Este campo es requerido" }, 
			RadFMDia5VI1 :{ required: "Este campo es requerido" }, 
			RadFMMes5VI1 :{ required: "Este campo es requerido" }, 
			RadFMAnio5VI1 :{ required: "Este campo es requerido" }, 

			RadCargoEmpresa5VI2 :{ required: "Este campo es requerido" }, 
			RadDescripcionFuente5VI2 :{ required: "Este campo es requerido" }, 
			RadDescripcionAct5VI2 :{ required: "Este campo es requerido" }, 
			RadCondiciones5VI2 :{ required: "Este campo es requerido" }, 
			RadTEDia5VI2 :{ required: "Este campo es requerido" }, 
			RadTEMes5VI2 :{ required: "Este campo es requerido" }, 
			RadTEAnio5VI2 :{ required: "Este campo es requerido" }, 
			RadEvalAmbiental5VI2 :{ required: "Este campo es requerido" }, 
			RadFMDia5VI2 :{ required: "Este campo es requerido" }, 
			RadFMMes5VI2 :{ required: "Este campo es requerido" }, 
			RadFMAnio5VI2 :{ required: "Este campo es requerido" }, 


			RadCargoEmpresa5VI3 :{ required: "Este campo es requerido" }, 
			RadDescripcionFuente5VI3 :{ required: "Este campo es requerido" }, 
			RadDescripcionAct5VI3 :{ required: "Este campo es requerido" }, 
			RadCondiciones5VI3 :{ required: "Este campo es requerido" }, 
			RadTEDia5VI3 :{ required: "Este campo es requerido" }, 
			RadTEMes5VI3 :{ required: "Este campo es requerido" }, 
			RadTEAnio5VI3 :{ required: "Este campo es requerido" }, 
			RadEvalAmbiental5VI3 :{ required: "Este campo es requerido" }, 
			RadFMDia5VI3 :{ required: "Este campo es requerido" }, 
			RadFMMes5VI3 :{ required: "Este campo es requerido" }, 
			RadFMAnio5VI3 :{ required: "Este campo es requerido" }, 


			RadCargoEmpresa5VI4 :{ required: "Este campo es requerido" }, 
			RadDescripcionFuente5VI4 :{ required: "Este campo es requerido" }, 
			RadDescripcionAct5VI4 :{ required: "Este campo es requerido" }, 
			RadCondiciones5VI4 :{ required: "Este campo es requerido" }, 
			RadTEDia5VI4 :{ required: "Este campo es requerido" }, 
			RadTEMes5VI4 :{ required: "Este campo es requerido" }, 
			RadTEAnio5V4 :{ required: "Este campo es requerido" }, 
			RadEvalAmbiental5VI4 :{ required: "Este campo es requerido" }, 
			RadFMDia5VI4 :{ required: "Este campo es requerido" }, 
			RadFMMes5VI4 :{ required: "Este campo es requerido" }, 
			RadFMAnio5VI4 :{ required: "Este campo es requerido" }, 

			VibCargoEmpresa6VI1 :{ required: "Este campo es requerido" }, 
			VibDescFuente6VI1 :{ required: "Este campo es requerido" }, 
			//BooTipoVibCE6VI1 :{ required: "Este campo es requerido" }, 
			//BooTipoVibMB6VI1 :{ required: "Este campo es requerido" }, 
			TiempoExpMeses6VI1 :{ required: "Este campo es requerido" }, 
			TiempoExpHD6VI1 :{ required: "Este campo es requerido" }, 
			VCE6VI1 :{ required: "Este campo es requerido" }, 
			VMB6VI1 :{ required: "Este campo es requerido" }, 
			AceTotal6VI1 :{ required: "Este campo es requerido" }, 
			EjeDominante6VI1 :{ required: "Este campo es requerido" }, 
			AceEjeDominante6VI1 :{ required: "Este campo es requerido" }, 
			Frecuencia6VI1 :{ required: "Este campo es requerido" }, 
			Aceleracion6VI1 :{ required: "Este campo es requerido" }, 
			FechaMedDia6VI1 :{ required: "Este campo es requerido" }, 
			FechaMedMes6VI1 :{ required: "Este campo es requerido" }, 
			FechaMedAnio6VI1 :{ required: "Este campo es requerido" }, 
			//BooExpoRuido6VI1 :{ required: "Este campo es requerido" }, 

			VibCargoEmpresa6VI2 :{ required: "Este campo es requerido" }, 
			VibDescFuente6VI2 :{ required: "Este campo es requerido" }, 
			//BooTipoVibCE6VI2 :{ required: "Este campo es requerido" }, 
			//BooTipoVibMB6VI2 :{ required: "Este campo es requerido" }, 
			TiempoExpMeses6VI2 :{ required: "Este campo es requerido" }, 
			TiempoExpHD6VI2 :{ required: "Este campo es requerido" }, 
			VCE6VI2 :{ required: "Este campo es requerido" }, 
			VMB6VI2 :{ required: "Este campo es requerido" }, 
			AceTotal6VI2 :{ required: "Este campo es requerido" }, 
			EjeDominante6VI2 :{ required: "Este campo es requerido" }, 
			AceEjeDominante6VI2 :{ required: "Este campo es requerido" }, 
			Frecuencia6VI2 :{ required: "Este campo es requerido" }, 
			Aceleracion6VI2 :{ required: "Este campo es requerido" }, 
			FechaMedDia6VI2 :{ required: "Este campo es requerido" }, 
			FechaMedMes6VI2 :{ required: "Este campo es requerido" }, 
			FechaMedAnio6VI2 :{ required: "Este campo es requerido" }, 
			//BooExpoRuido6VI2 :{ required: "Este campo es requerido" }, 

			VibCargoEmpresa6VI3 :{ required: "Este campo es requerido" }, 
			VibDescFuente6VI3 :{ required: "Este campo es requerido" }, 
			//BooTipoVibCE6VI3 :{ required: "Este campo es requerido" }, 
			//BooTipoVibMB6VI3 :{ required: "Este campo es requerido" }, 
			TiempoExpMeses6VI3 :{ required: "Este campo es requerido" }, 
			TiempoExpHD6VI3 :{ required: "Este campo es requerido" }, 
			VCE6VI3 :{ required: "Este campo es requerido" }, 
			VMB6VI3 :{ required: "Este campo es requerido" }, 
			AceTotal6VI3 :{ required: "Este campo es requerido" }, 
			EjeDominante6VI3 :{ required: "Este campo es requerido" }, 
			AceEjeDominante6VI3 :{ required: "Este campo es requerido" }, 
			Frecuencia6VI3 :{ required: "Este campo es requerido" }, 
			Aceleracion6VI3 :{ required: "Este campo es requerido" }, 
			FechaMedDia6VI3 :{ required: "Este campo es requerido" }, 
			FechaMedMes6VI3 :{ required: "Este campo es requerido" }, 
			FechaMedAnio6VI3 :{ required: "Este campo es requerido" }, 
			//BooExpoRuido6VI3 :{ required: "Este campo es requerido" }, 

			VibCargoEmpresa6VI4 :{ required: "Este campo es requerido" }, 
			VibDescFuente6VI4 :{ required: "Este campo es requerido" }, 
			//BooTipoVibCE6VI4 :{ required: "Este campo es requerido" }, 
			//BooTipoVibMB6VI4 :{ required: "Este campo es requerido" }, 
			TiempoExpMeses6VI4 :{ required: "Este campo es requerido" }, 
			TiempoExpHD6VI4 :{ required: "Este campo es requerido" }, 
			VCE6VI4 :{ required: "Este campo es requerido" }, 
			VMB6VI4 :{ required: "Este campo es requerido" }, 
			AceTotal6VI4 :{ required: "Este campo es requerido" }, 
			EjeDominante6VI4 :{ required: "Este campo es requerido" }, 
			AceEjeDominante6VI4 :{ required: "Este campo es requerido" }, 
			Frecuencia6VI4 :{ required: "Este campo es requerido" }, 
			Aceleracion6VI4 :{ required: "Este campo es requerido" }, 
			FechaMedDia6VI4 :{ required: "Este campo es requerido" }, 
			FechaMedMes6VI4 :{ required: "Este campo es requerido" }, 
			FechaMedAnio6VI4 :{ required: "Este campo es requerido" }, 
			//BooExpoRuido6VI4 :{ required: "Este campo es requerido" }, 

			VibCargoEmpresa6VI5 :{ required: "Este campo es requerido" }, 
			VibDescFuente6VI5 :{ required: "Este campo es requerido" }, 
			//BooTipoVibCE6VI5 :{ required: "Este campo es requerido" }, 
			//BooTipoVibMB6VI5 :{ required: "Este campo es requerido" }, 
			TiempoExpMeses6VI5 :{ required: "Este campo es requerido" }, 
			TiempoExpHD6VI5 :{ required: "Este campo es requerido" }, 
			VCE6VI5 :{ required: "Este campo es requerido" }, 
			VMB6VI5 :{ required: "Este campo es requerido" }, 
			AceTotal6VI5 :{ required: "Este campo es requerido" }, 
			EjeDominante6VI5 :{ required: "Este campo es requerido" }, 
			AceEjeDominante6VI5 :{ required: "Este campo es requerido" }, 
			Frecuencia6VI5 :{ required: "Este campo es requerido" }, 
			Aceleracion6VI5 :{ required: "Este campo es requerido" }, 
			FechaMedDia6VI5 :{ required: "Este campo es requerido" }, 
			FechaMedMes6VI5 :{ required: "Este campo es requerido" }, 
			FechaMedAnio6VI5 :{ required: "Este campo es requerido" }, 
			//BooExpoRuido6VI5 :{ required: "Este campo es requerido" }, 

			VibCargoEmpresa6VI6 :{ required: "Este campo es requerido" }, 
			VibDescFuente6VI6 :{ required: "Este campo es requerido" }, 
			//BooTipoVibCE6VI6 :{ required: "Este campo es requerido" }, 
			//BooTipoVibMB6VI6 :{ required: "Este campo es requerido" }, 
			TiempoExpMeses6VI6 :{ required: "Este campo es requerido" }, 
			TiempoExpHD6VI6 :{ required: "Este campo es requerido" }, 
			VCE6VI6 :{ required: "Este campo es requerido" }, 
			VMB6VI6 :{ required: "Este campo es requerido" }, 
			AceTotal6VI6 :{ required: "Este campo es requerido" }, 
			EjeDominante6VI6 :{ required: "Este campo es requerido" }, 
			AceEjeDominante6VI6 :{ required: "Este campo es requerido" }, 
			Frecuencia6VI6 :{ required: "Este campo es requerido" }, 
			Aceleracion6VI6 :{ required: "Este campo es requerido" }, 
			FechaMedDia6VI6 :{ required: "Este campo es requerido" }, 
			FechaMedMes6VI6 :{ required: "Este campo es requerido" }, 
			FechaMedAnio6VI6 :{ required: "Este campo es requerido" }, 
			//BooExpoRuido6VI6 :{ required: "Este campo es requerido" }, 

			DescEventoInv6VI :{ required: "Este campo es requerido" }, 


			FrecPresAltoVI1 :{ required: "Este campo es requerido" }, 
			FrecPresMedioVI1 :{ required: "Este campo es requerido" }, 
			FrecPresBajoVI1 :{ required: "Este campo es requerido" }, 
			TiempoExpAltoVI1 :{ required: "Este campo es requerido" }, 
			TiempoExpMedioVI1 :{ required: "Este campo es requerido" }, 
			TiempoExpBajoVI1 :{ required: "Este campo es requerido" }, 
			IntensidadAltoVI1 :{ required: "Este campo es requerido" }, 
			IntensidadMedioVI1 :{ required: "Este campo es requerido" }, 
			IntensidadBajoVI1 :{ required: "Este campo es requerido" }, 
			VarPsicoObservacionesVI1 :{ required: "Este campo es requerido" }, 

			FrecPresAltoVI2 :{ required: "Este campo es requerido" }, 
			FrecPresMedioVI2 :{ required: "Este campo es requerido" }, 
			FrecPresBajoVI2 :{ required: "Este campo es requerido" }, 
			TiempoExpAltoVI2 :{ required: "Este campo es requerido" }, 
			TiempoExpMedioVI2 :{ required: "Este campo es requerido" }, 
			TiempoExpBajoVI2 :{ required: "Este campo es requerido" }, 
			IntensidadAltoVI2 :{ required: "Este campo es requerido" }, 
			IntensidadMedioVI2 :{ required: "Este campo es requerido" }, 
			IntensidadBajoVI2 :{ required: "Este campo es requerido" }, 
			VarPsicoObservacionesVI2 :{ required: "Este campo es requerido" }, 


			FrecPresAltoVI3 :{ required: "Este campo es requerido" }, 
			FrecPresMedioVI3 :{ required: "Este campo es requerido" }, 
			FrecPresBajoVI3 :{ required: "Este campo es requerido" }, 
			TiempoExpAltoVI3 :{ required: "Este campo es requerido" }, 
			TiempoExpMedioVI3 :{ required: "Este campo es requerido" }, 
			TiempoExpBajoVI3 :{ required: "Este campo es requerido" }, 
			IntensidadAltoVI3 :{ required: "Este campo es requerido" }, 
			IntensidadMedioVI3 :{ required: "Este campo es requerido" }, 
			IntensidadBajoVI3 :{ required: "Este campo es requerido" }, 
			VarPsicoObservacionesVI3 :{ required: "Este campo es requerido" }, 

			FrecPresAltoVI4 :{ required: "Este campo es requerido" }, 
			FrecPresMedioVI4 :{ required: "Este campo es requerido" }, 
			FrecPresBajoVI4 :{ required: "Este campo es requerido" }, 
			TiempoExpAltoVI4 :{ required: "Este campo es requerido" }, 
			TiempoExpMedioVI4 :{ required: "Este campo es requerido" }, 
			TiempoExpBajoV4 :{ required: "Este campo es requerido" }, 
			IntensidadAltoVI4 :{ required: "Este campo es requerido" }, 
			IntensidadMedioVI4 :{ required: "Este campo es requerido" }, 
			IntensidadBajoVI4 :{ required: "Este campo es requerido" }, 
			VarPsicoObservacionesVI4 :{ required: "Este campo es requerido" }, 

			IntensidadAltaVI1 :{ required: "Este campo es requerido" }, 
			IntensidadMediaVI1 :{ required: "Este campo es requerido" }, 
			IntensidadBajaVI1 :{ required: "Este campo es requerido" }, 
			IntensidadObservVI1 :{ required: "Este campo es requerido" }, 

			IntensidadAltaVI2 :{ required: "Este campo es requerido" }, 
			IntensidadMediaVI2 :{ required: "Este campo es requerido" }, 
			IntensidadBajaVI2 :{ required: "Este campo es requerido" }, 
			IntensidadObservVI2 :{ required: "Este campo es requerido" }, 

			NivelRiesgoLabVI :{ required: "Este campo es requerido" }, 
			NivelRiesgoExtralabVI :{ required: "Este campo es requerido" }, 
			NivelRiesgoIndiviVI :{ required: "Este campo es requerido" }, 
			NivelEstresVI :{ required: "Este campo es requerido" }, 

			//BooPostPieProlongada :{ required: "Este campo es requerido" }, 
			//BooPostPieSedente :{ required: "Este campo es requerido" }, 
			//BooPosturaIncomodaBrazosManos :{ required: "Este campo es requerido" }, 
			//BooEsfuerzoBrazosManos :{ required: "Este campo es requerido" }, 
			//BooPosturaIncomodaEspalda :{ required: "Este campo es requerido" }, 
			//BooLabRepetitivaColumna :{ required: "Este campo es requerido" }, 
			//BooLabRepetitivaBrazoMuMano :{ required: "Este campo es requerido" }, 
			//BooPeriodoRecuperacionFisica :{ required: "Este campo es requerido" }, 
			//BooEsfuerzoManos :{ required: "Este campo es requerido" }, 
			//BooEsfuerzoCuerpo :{ required: "Este campo es requerido" }, 
			//BooManipulacionCargas :{ required: "Este campo es requerido" }, 
			DMEResumen :{ required: "Este campo es requerido" }, 

			//BooCauRelPrevVI1 :{ required: "Este campo es requerido" }, 	
			CauRelPrevVI1 :{ required: "Este campo es requerido" }, 
			//BooCauRelPrevVI2 :{ required: "Este campo es requerido" }, 	
			CauRelPrevVI2 :{ required: "Este campo es requerido" }, 
			//BooCauRelPrevVI3 :{ required: "Este campo es requerido" }, 	
			CauRelPrevVI3 :{ required: "Este campo es requerido" }, 
			//BooCauRelPrevVI4 :{ required: "Este campo es requerido" }, 	
			CauRelPrevVI4 :{ required: "Este campo es requerido" }, 
			//BooCauRelPrevVI5 :{ required: "Este campo es requerido" }, 	
			CauRelPrevVI5 :{ required: "Este campo es requerido" }, 
			//BooCauRelPrevVI6 :{ required: "Este campo es requerido" }, 	
			CauRelPrevVI6 :{ required: "Este campo es requerido" }, 
			//BooCauRelPrevVI7 :{ required: "Este campo es requerido" }, 	
			CauRelPrevVI7 :{ required: "Este campo es requerido" }, 
			//BooCauRelPrevVI8 :{ required: "Este campo es requerido" }, 	
			CauRelPrevVI8 :{ required: "Este campo es requerido" }, 
			//BooCauRelPrevVI9 :{ required: "Este campo es requerido" }, 	
			CauRelPrevVI9 :{ required: "Este campo es requerido" }, 
			//BooCauRelPrevVI10 :{ required: "Este campo es requerido" }, 	
			CauRelPrevVI10 :{ required: "Este campo es requerido" }, 
			//BooCauRelPrevVI11 :{ required: "Este campo es requerido" }, 	
			CauRelPrevVI11 :{ required: "Este campo es requerido" }, 
			//BooCauRelPrevVI12 :{ required: "Este campo es requerido" }, 
			CauRelPrevVI12 :{ required: "Este campo es requerido" }, 

			OtrosDatosInteresVI :{ required: "Este campo es requerido" }, 
			CausasEnfermedadLaboralVI :{ required: "Este campo es requerido" }, 

			MedidasPreventivasVII1 :{ required: "Este campo es requerido" }, 
			ResponsableImplementacionVII1 :{ required: "Este campo es requerido" }, 
			FechaEjeMesVII1 :{ required: "Este campo es requerido" }, 
			FechaEjeDiaVII1 :{ required: "Este campo es requerido" }, 

			MedidasPreventivasVII2 :{ required: "Este campo es requerido" }, 
			ResponsableImplementacionVII2 :{ required: "Este campo es requerido" }, 
			FechaEjeMesVII3 :{ required: "Este campo es requerido" }, 
			FechaEjeDiaVII3 :{ required: "Este campo es requerido" }, 

			MedidasPreventivasVII4 :{ required: "Este campo es requerido" }, 
			ResponsableImplementacionVII4 :{ required: "Este campo es requerido" }, 
			FechaEjeMesVII4 :{ required: "Este campo es requerido" }, 
			FechaEjeDiaVII4 :{ required: "Este campo es requerido" }, 

			MedidasPreventivasVII5 :{ required: "Este campo es requerido" }, 
			ResponsableImplementacionVII5 :{ required: "Este campo es requerido" }, 
			FechaEjeMesVII5 :{ required: "Este campo es requerido" }, 
			FechaEjeDiaVII5 :{ required: "Este campo es requerido" }, 

			MedidasPreventivasVII6 :{ required: "Este campo es requerido" }, 
			ResponsableImplementacionVII6 :{ required: "Este campo es requerido" }, 
			FechaEjeMesVII6 :{ required: "Este campo es requerido" }, 
			FechaEjeDiaVII6 :{ required: "Este campo es requerido" }, 

			MedidasPreventivasVII7 :{ required: "Este campo es requerido" }, 
			ResponsableImplementacionVII7 :{ required: "Este campo es requerido" }, 
			FechaEjeMesVII7 :{ required: "Este campo es requerido" }, 
			FechaEjeDiaVII7 :{ required: "Este campo es requerido" }, 

			MedidasPreventivasVII8 :{ required: "Este campo es requerido" }, 
			ResponsableImplementacionVII8 :{ required: "Este campo es requerido" }, 
			FechaEjeMesVII8 :{ required: "Este campo es requerido" }, 
			FechaEjeDiaVII8 :{ required: "Este campo es requerido" }, 

			TipoIdentificacionVIII1 :{ required: "Este campo es requerido" }, 
			JefeInmediatoVIII1 :{ required: "Este campo es requerido" }, 
			CargoVIII1 :{ required: "Este campo es requerido" }, 
			NumeroIdentificacionVIII1 :{ required: "Este campo es requerido" }, 

			TipoIdentificacionVIII2 :{ required: "Este campo es requerido" }, 
			JefeInmediatoVIII2 :{ required: "Este campo es requerido" }, 
			CargoVIII2 :{ required: "Este campo es requerido" }, 
			NumeroIdentificacionVIII2 :{ required: "Este campo es requerido" }, 

			TipoIdentificacionVIII3 :{ required: "Este campo es requerido" }, 
			JefeInmediatoVIII3 :{ required: "Este campo es requerido" }, 
			CargoVIII3 :{ required: "Este campo es requerido" }, 
			NumeroIdentificacionVIII3 :{ required: "Este campo es requerido" }, 

			TipoIdentificacionVIII4 :{ required: "Este campo es requerido" }, 
			JefeInmediatoVIII4 :{ required: "Este campo es requerido" }, 
			CargoVIII4 :{ required: "Este campo es requerido" }, 
			NumeroIdentificacionVIII4 :{ required: "Este campo es requerido" }, 

			TipoIdentificacionVIII5 :{ required: "Este campo es requerido" }, 
			JefeInmediatoVIII5 :{ required: "Este campo es requerido" }, 
			CargoVIII5 :{ required: "Este campo es requerido" }, 
			NumeroIdentificacionVIII5 :{ required: "Este campo es requerido" }, 

			TipoIdentificacionVIII6 :{ required: "Este campo es requerido" }, 
			JefeInmediatoVIII6 :{ required: "Este campo es requerido" }, 
			CargoVIII6 :{ required: "Este campo es requerido" }, 
			NumeroIdentificacionVIII6 :{ required: "Este campo es requerido" }, 


			TipoIdentificacionVIII7 :{ required: "Este campo es requerido" }, 
			EspecialistaOcupacionalVIII :{ required: "Este campo es requerido" }, 
			LicenciaNumVIII1 :{ required: "Este campo es requerido" }, 
			LicenciaAnioVIII1 :{ required: "Este campo es requerido" }, 
			NumeroIdentificacionVIII7 :{ required: "Este campo es requerido" }, 


			TipoIdentificacionVIII8 :{ required: "Este campo es requerido" }, 
			RepresentanteArlVIII8 :{ required: "Este campo es requerido" }, 
			LicenciaNumeroVIII8 :{ required: "Este campo es requerido" }, 
			LicenciaAnioVIII8 :{ required: "Este campo es requerido" }, 
			NumeroIdentificacionVIII8 :{ required: "Este campo es requerido" }, 
			EmpresaRepresentaVIII8 :{ required: "Este campo es requerido" }, 
			NitVIII8 :{ required: "Este campo es requerido" }, 

			FechaRemisionIX :{ required: "Este campo es requerido" }, 
			NoFoliosIX :{ required: "Este campo es requerido" }, 
			TipoIdentificacionIX :{ required: "Este campo es requerido" }, 
			NombreApellidoIX :{ required: "Este campo es requerido" }, 
			CargoIX :{ required: "Este campo es requerido" }, 
			NumeroIdentificacionIX :{ required: "Este campo es requerido" }, 

			FechaRemisionARLIX :{ required: "Este campo es requerido" }, 
			FecRemisionTerritorialIX     :{ required: "Este campo es requerido" }, 
			DisponibleRemisionARLIX :{ required: "Este campo es requerido" }, 
			ResponsablesRemisionARLIX :{ required: "Este campo es requerido" }, 
			CargoARLIX :{ required: "Este campo es requerido" }, 

			TipoIdentificacionX :{ required: "Este campo es requerido" }, 
			ResponsableVerficiacionX :{ required: "Este campo es requerido" }, 
			CargoX :{ required: "Este campo es requerido" }, 
			NumeroIdentificacionX :{ required: "Este campo es requerido" }, 

			MedidasIntervencionX :{ required: "Este campo es requerido" }, 
			ObsevacionesX :{ required: "Este campo es requerido" }, 
			FechaVerficacionX :{ required: "Este campo es requerido" }, 


			TipoIdentificacionXI :{ required: "Este campo es requerido" }, 
			ResponsableVerficiacionXI :{ required: "Este campo es requerido" }, 
			CargoXI :{ required: "Este campo es requerido" }, 
			NumeroIdentificacionXI :{ required: "Este campo es requerido" }, 

			MedidasIntervencionXI :{ required: "Este campo es requerido" }, 
			ObsevacionesARLXI :{ required: "Este campo es requerido" }, 
			FechaVerficacionXI :{ required: "Este campo es requerido" } 
		}
	});
}		
			