//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG_SST.Recursos.Planificacion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanificacionMod {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanificacionMod() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SG_SST.Recursos.Planificacion.PlanificacionMod", typeof(PlanificacionMod).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar.
        /// </summary>
        public static string nombre_btn_modal_generar {
            get {
                return ResourceManager.GetString("nombre_btn_modal_generar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Peligro.
        /// </summary>
        public static string nombre_btn_modal_guardar_peligro {
            get {
                return ResourceManager.GetString("nombre_btn_modal_guardar_peligro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Metodología.
        /// </summary>
        public static string nombre_btn_panel_peligros_consultar {
            get {
                return ResourceManager.GetString("nombre_btn_panel_peligros_consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Metodología.
        /// </summary>
        public static string nombre_btn_panel_peligros_editar {
            get {
                return ResourceManager.GetString("nombre_btn_panel_peligros_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Metodología.
        /// </summary>
        public static string nombre_btn_panel_peligros_eliminar {
            get {
                return ResourceManager.GetString("nombre_btn_panel_peligros_eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Metodología.
        /// </summary>
        public static string nombre_btn_panel_peligros_seleccionar {
            get {
                return ResourceManager.GetString("nombre_btn_panel_peligros_seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción Requerida.
        /// </summary>
        public static string nombre_lbl_accion_requerida {
            get {
                return ResourceManager.GetString("nombre_lbl_accion_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable.
        /// </summary>
        public static string nombre_lbl_accion_responsable {
            get {
                return ResourceManager.GetString("nombre_lbl_accion_responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar firma digital.
        /// </summary>
        public static string nombre_lbl_cargar_firma {
            get {
                return ResourceManager.GetString("nombre_lbl_cargar_firma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de comprobación de eficacia de la acción.
        /// </summary>
        public static string nombre_lbl_fecha_comprobacion {
            get {
                return ResourceManager.GetString("nombre_lbl_fecha_comprobacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Finalización.
        /// </summary>
        public static string nombre_lbl_fecha_finalizacion {
            get {
                return ResourceManager.GetString("nombre_lbl_fecha_finalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodología.
        /// </summary>
        public static string nombre_lbl_modal_metodologia {
            get {
                return ResourceManager.GetString("nombre_lbl_modal_metodologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sede.
        /// </summary>
        public static string nombre_lbl_modal_sede {
            get {
                return ResourceManager.GetString("nombre_lbl_modal_sede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riesgo Controlado.
        /// </summary>
        public static string nombre_lbl_riesgo_controlado {
            get {
                return ResourceManager.GetString("nombre_lbl_riesgo_controlado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptabilidad del riesgo.
        /// </summary>
        public static string nombre_lbl_step_aceptabilidad_riesgo {
            get {
                return ResourceManager.GetString("nombre_lbl_step_aceptabilidad_riesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad.
        /// </summary>
        public static string nombre_lbl_step_actividad {
            get {
                return ResourceManager.GetString("nombre_lbl_step_actividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiental.
        /// </summary>
        public static string nombre_lbl_step_ambiental {
            get {
                return ResourceManager.GetString("nombre_lbl_step_ambiental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea Calificar el peligro como higiénico.
        /// </summary>
        public static string nombre_lbl_step_calificar_como_higienico {
            get {
                return ResourceManager.GetString("nombre_lbl_step_calificar_como_higienico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string nombre_lbl_step_cantidad {
            get {
                return ResourceManager.GetString("nombre_lbl_step_cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificación.
        /// </summary>
        public static string nombre_lbl_step_clasificacion {
            get {
                return ResourceManager.GetString("nombre_lbl_step_clasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string nombre_lbl_step_clientes {
            get {
                return ResourceManager.GetString("nombre_lbl_step_clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecuencia.
        /// </summary>
        public static string nombre_lbl_step_consecuencia {
            get {
                return ResourceManager.GetString("nombre_lbl_step_consecuencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecuencias Potenciales.
        /// </summary>
        public static string nombre_lbl_step_consecuencias_ptenciales {
            get {
                return ResourceManager.GetString("nombre_lbl_step_consecuencias_ptenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecuencias Reales.
        /// </summary>
        public static string nombre_lbl_step_consecuencias_reales {
            get {
                return ResourceManager.GetString("nombre_lbl_step_consecuencias_reales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles administrativos.
        /// </summary>
        public static string nombre_lbl_step_controles_administrativos {
            get {
                return ResourceManager.GetString("nombre_lbl_step_controles_administrativos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles de ingeniería.
        /// </summary>
        public static string nombre_lbl_step_controles_ingenieria {
            get {
                return ResourceManager.GetString("nombre_lbl_step_controles_ingenieria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cual.
        /// </summary>
        public static string nombre_lbl_step_cual {
            get {
                return ResourceManager.GetString("nombre_lbl_step_cual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cualitativo.
        /// </summary>
        public static string nombre_lbl_step_cualitativo {
            get {
                return ResourceManager.GetString("nombre_lbl_step_cualitativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuantitativo.
        /// </summary>
        public static string nombre_lbl_step_cuantitativo {
            get {
                return ResourceManager.GetString("nombre_lbl_step_cuantitativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string nombre_lbl_step_descripcion {
            get {
                return ResourceManager.GetString("nombre_lbl_step_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección de la sede.
        /// </summary>
        public static string nombre_lbl_step_direccion_sede {
            get {
                return ResourceManager.GetString("nombre_lbl_step_direccion_sede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Económica.
        /// </summary>
        public static string nombre_lbl_step_economica {
            get {
                return ResourceManager.GetString("nombre_lbl_step_economica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectos posibles.
        /// </summary>
        public static string nombre_lbl_step_efectos_posibles {
            get {
                return ResourceManager.GetString("nombre_lbl_step_efectos_posibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementos de protección personal.
        /// </summary>
        public static string nombre_lbl_step_elementos_proteccion {
            get {
                return ResourceManager.GetString("nombre_lbl_step_elementos_proteccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminación.
        /// </summary>
        public static string nombre_lbl_step_eliminacion {
            get {
                return ResourceManager.GetString("nombre_lbl_step_eliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimación del riesgo.
        /// </summary>
        public static string nombre_lbl_step_estimacion_riesgo {
            get {
                return ResourceManager.GetString("nombre_lbl_step_estimacion_riesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existencia de requisito legal.
        /// </summary>
        public static string nombre_lbl_step_existencia_legal {
            get {
                return ResourceManager.GetString("nombre_lbl_step_existencia_legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de evaluación.
        /// </summary>
        public static string nombre_lbl_step_fecha_evaluacion {
            get {
                return ResourceManager.GetString("nombre_lbl_step_fecha_evaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formación.
        /// </summary>
        public static string nombre_lbl_step_formacion {
            get {
                return ResourceManager.GetString("nombre_lbl_step_formacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuente Generadora de peligro.
        /// </summary>
        public static string nombre_lbl_step_fuente_peligro {
            get {
                return ResourceManager.GetString("nombre_lbl_step_fuente_peligro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuente.
        /// </summary>
        public static string nombre_lbl_step_fuentes {
            get {
                return ResourceManager.GetString("nombre_lbl_step_fuentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas Exposición día.
        /// </summary>
        public static string nombre_lbl_step_horas_exposicion {
            get {
                return ResourceManager.GetString("nombre_lbl_step_horas_exposicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación empleador / contratante.
        /// </summary>
        public static string nombre_lbl_step_identificacion_empleador {
            get {
                return ResourceManager.GetString("nombre_lbl_step_identificacion_empleador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen de la empresa.
        /// </summary>
        public static string nombre_lbl_step_imagen_empresa {
            get {
                return ResourceManager.GetString("nombre_lbl_step_imagen_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        public static string nombre_lbl_step_informacion {
            get {
                return ResourceManager.GetString("nombre_lbl_step_informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretación del nivel de probabilidad.
        /// </summary>
        public static string nombre_lbl_step_interpretacion_probabilidad {
            get {
                return ResourceManager.GetString("nombre_lbl_step_interpretacion_probabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretacion del nivel de riesgo.
        /// </summary>
        public static string nombre_lbl_step_interpretacion_riesgo {
            get {
                return ResourceManager.GetString("nombre_lbl_step_interpretacion_riesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medidas de Control.
        /// </summary>
        public static string nombre_lbl_step_medidas_de_control {
            get {
                return ResourceManager.GetString("nombre_lbl_step_medidas_de_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medio.
        /// </summary>
        public static string nombre_lbl_step_medio {
            get {
                return ResourceManager.GetString("nombre_lbl_step_medio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel de consecuencia.
        /// </summary>
        public static string nombre_lbl_step_nivel_consecuencia {
            get {
                return ResourceManager.GetString("nombre_lbl_step_nivel_consecuencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel de deficiencia.
        /// </summary>
        public static string nombre_lbl_step_nivel_deficiencia {
            get {
                return ResourceManager.GetString("nombre_lbl_step_nivel_deficiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel de exposición.
        /// </summary>
        public static string nombre_lbl_step_nivel_exposicion {
            get {
                return ResourceManager.GetString("nombre_lbl_step_nivel_exposicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel de probabilidad.
        /// </summary>
        public static string nombre_lbl_step_nivel_probabilidad {
            get {
                return ResourceManager.GetString("nombre_lbl_step_nivel_probabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel de riesgo.
        /// </summary>
        public static string nombre_lbl_step_nivel_riesgo {
            get {
                return ResourceManager.GetString("nombre_lbl_step_nivel_riesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Responsable.
        /// </summary>
        public static string nombre_lbl_step_nombre_profesional {
            get {
                return ResourceManager.GetString("nombre_lbl_step_nombre_profesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Documento.
        /// </summary>
        public static string nombre_lbl_step_numero_documento {
            get {
                return ResourceManager.GetString("nombre_lbl_step_numero_documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de expuestos.
        /// </summary>
        public static string nombre_lbl_step_numero_expuestos {
            get {
                return ResourceManager.GetString("nombre_lbl_step_numero_expuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Licencia SST.
        /// </summary>
        public static string nombre_lbl_step_numero_licencia {
            get {
                return ResourceManager.GetString("nombre_lbl_step_numero_licencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de trabajadores.
        /// </summary>
        public static string nombre_lbl_step_numero_trabajadores {
            get {
                return ResourceManager.GetString("nombre_lbl_step_numero_trabajadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peor consecuencia.
        /// </summary>
        public static string nombre_lbl_step_peor_consecuencia {
            get {
                return ResourceManager.GetString("nombre_lbl_step_peor_consecuencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string nombre_lbl_step_persona {
            get {
                return ResourceManager.GetString("nombre_lbl_step_persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probabilidad.
        /// </summary>
        public static string nombre_lbl_step_probabilidad {
            get {
                return ResourceManager.GetString("nombre_lbl_step_probabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimientos de trabajo.
        /// </summary>
        public static string nombre_lbl_step_procedimientos_trabajo {
            get {
                return ResourceManager.GetString("nombre_lbl_step_procedimientos_trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso.
        /// </summary>
        public static string nombre_lbl_step_proceso {
            get {
                return ResourceManager.GetString("nombre_lbl_step_proceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón Social.
        /// </summary>
        public static string nombre_lbl_step_razon_social {
            get {
                return ResourceManager.GetString("nombre_lbl_step_razon_social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rutinaria.
        /// </summary>
        public static string nombre_lbl_step_rutina {
            get {
                return ResourceManager.GetString("nombre_lbl_step_rutina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustitución.
        /// </summary>
        public static string nombre_lbl_step_sustitucion {
            get {
                return ResourceManager.GetString("nombre_lbl_step_sustitucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea.
        /// </summary>
        public static string nombre_lbl_step_tarea {
            get {
                return ResourceManager.GetString("nombre_lbl_step_tarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Riesgo.
        /// </summary>
        public static string nombre_lbl_step_valor_riesgo {
            get {
                return ResourceManager.GetString("nombre_lbl_step_valor_riesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona ó lugar.
        /// </summary>
        public static string nombre_lbl_step_zona_lugar {
            get {
                return ResourceManager.GetString("nombre_lbl_step_zona_lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Generales.
        /// </summary>
        public static string nombre_step_datos_generales {
            get {
                return ResourceManager.GetString("nombre_step_datos_generales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determinación de Controles.
        /// </summary>
        public static string nombre_step_determinacion_controles {
            get {
                return ResourceManager.GetString("nombre_step_determinacion_controles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluación y Valoración.
        /// </summary>
        public static string nombre_step_evaluacion_valoracion {
            get {
                return ResourceManager.GetString("nombre_step_evaluacion_valoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación.
        /// </summary>
        public static string nombre_step_identificacion {
            get {
                return ResourceManager.GetString("nombre_step_identificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Expuestos.
        /// </summary>
        public static string nombre_step_numero_de_expuestos {
            get {
                return ResourceManager.GetString("nombre_step_numero_de_expuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Expuestos.
        /// </summary>
        public static string nombre_step_numero_expuesto {
            get {
                return ResourceManager.GetString("nombre_step_numero_expuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervención de Riesgos no Aceptables.
        /// </summary>
        public static string nombre_step_riesgos_no_aceptables {
            get {
                return ResourceManager.GetString("nombre_step_riesgos_no_aceptables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de acción de Riesgos no Controlados.
        /// </summary>
        public static string nombre_step_riesgos_no_controlados {
            get {
                return ResourceManager.GetString("nombre_step_riesgos_no_controlados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individuo.
        /// </summary>
        public static string nombre_step_trabajador {
            get {
                return ResourceManager.GetString("nombre_step_trabajador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles Existentes.
        /// </summary>
        public static string titulo_lbl_step_controles_existentes {
            get {
                return ResourceManager.GetString("titulo_lbl_step_controles_existentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criterios para establecer controles.
        /// </summary>
        public static string titulo_lbl_step_criterios_controles {
            get {
                return ResourceManager.GetString("titulo_lbl_step_criterios_controles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medidas de Intervención.
        /// </summary>
        public static string titulo_lbl_step_medidas_intervencion {
            get {
                return ResourceManager.GetString("titulo_lbl_step_medidas_intervencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peligro.
        /// </summary>
        public static string titulo_lbl_step_peligro {
            get {
                return ResourceManager.GetString("titulo_lbl_step_peligro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTIFICACIÓN PELIGROS, EVALUACIÓN Y VALORACIÓN RIESGOS.
        /// </summary>
        public static string titulo_panel_identificacion_peligros {
            get {
                return ResourceManager.GetString("titulo_panel_identificacion_peligros", resourceCulture);
            }
        }
    }
}
