USE SGSST;  
GO  


DELETE FROM Tbl_BateriaCuestionario;
DELETE FROM Tbl_BateriaDimension;
DELETE FROM Tbl_PlantillasCorreosSistema WHERE NombrePlantilla='NotificacionBateria';

DELETE FROM Tbl_Bateria

DBCC CHECKIDENT (Tbl_Bateria, RESEED,0);
DBCC CHECKIDENT (Tbl_BateriaCuestionario, RESEED,0);
DBCC CHECKIDENT (Tbl_BateriaDimension, RESEED,0);


DBCC CHECKIDENT (Tbl_Bateria, RESEED,0);
DBCC CHECKIDENT (Tbl_BateriaCuestionario, RESEED,0);
DBCC CHECKIDENT (Tbl_BateriaDimension, RESEED,0);


INSERT INTO Tbl_PlantillasCorreosSistema([NombrePlantilla],[Plantilla]) VALUES ('NotificacionBateria','<p>&nbsp;</p><center><table id="bodyTable" style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; margin: 0; padding: 0; background-color: #f2f2f2; width: 100%!important; height: 100%!important;" border="0" width="100%" cellspacing="0" cellpadding="0" align="center" bgcolor="#f2f2f2"><tbody><tr><td id="bodyCell" style="mso-table-lspace: 0; mso-table-rspace: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; margin: 0; padding: 0; width: 100%!important; height: 100%!important;" align="center" valign="top"><table id="emailContainer" style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" border="0" width="600" cellspacing="0" cellpadding="0"><tbody><tr><td id="emailPreheaderContainer" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" align="center" valign="top"><table id="emailPreheader" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; width: 100%; background-color: #ecf5ff; border-bottom: 1px #dceaf5 solid;" border="0" width="100%" cellspacing="0" cellpadding="0" align="center" bgcolor="#ecf5ff"><tbody><tr><td style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding: 10px;" align="center" valign="top">&nbsp;</td></tr></tbody></table></td></tr><tr><td id="emailBodyContainer" style="mso-table-lspace: 0; mso-table-rspace: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" align="center" valign="top" width="100%"><table id="emailBody" style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background-color: #ffffff;" border="0" width="100%" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff"><tbody><tr><td class="bodyContainer" style="mso-table-lspace: 0; mso-table-rspace: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;" align="center" valign="top" width="600"><div id="divContentHtml" style="padding-right:10px"><table style="width: 600px; color: black; font-family: Arial, Helvetica, sans-serif; font-size: 10px;" cellspacing="0" cellpadding="0"><tbody><tr><td style="padding-left: 60px;" colspan="3"><img src="[[RutaHttpSitio]]Images/banercorreo.jpg" alt="" width="480" align="middle" border="0" /></td></tr><tr><td width="60">&nbsp;</td><td width="480"><table style="width: 100%; color: black; font-family: Arial, Helvetica, sans-serif; font-size: 10px;" cellspacing="0" cellpadding="0"><tbody><tr><td>Bogot&aacute;, D.C., [[DATE]]</td></tr><tr><td>&nbsp;</td></tr><tr><td Style="text-align:justify;max-width:480px;">[[CuerpoMensaje]]</td></tr><tr><td>&nbsp;</td></tr><tr><td Style="text-align:justify;max-width:480px;">Puede acceder a la encuesta mediante el siguiente link <a href="[[LinkHttpSitio]]">[[LinkHttpSitio]] </a></td></tr><tr><td>&nbsp;</td></tr><tr><td Style="text-align:justify;max-width:480px;">Haga clic en el anterior link para acceder a la aplicaci&oacute;n de la encuesta. Si no puede acceder, por favor copiar el link y pegar en el navegador. </td></tr><tr><td>&nbsp;</td></tr></tbody></table></td></tr></tbody></table></div></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></center>');

INSERT INTO Tbl_Bateria(Nombre,Descripción,Fecha_publicacion,TiposAplicacion,ModalidadesAplicacion,Poblacion,Objetivo,Baremacion,TipoInstrumento,NumeroItems,DuracionAplicacion,Materiales)
VALUES ('Cuestionario de Factores de Riesgo Psicosocial Intralaboral FORMA A', 'Batería para la evaluación de factores de riesgo psicosocial (intralaboral y extralaboral).', 'Julio de 2010','Ministerio de la Protección Social  Pontificia Universidad Javeriana, Subcentro de Seguridad Social y Riesgos Profesionales', '','', '','', '','', '','');
INSERT INTO Tbl_Bateria(Nombre,Descripción,Fecha_publicacion,TiposAplicacion,ModalidadesAplicacion,Poblacion,Objetivo,Baremacion,TipoInstrumento,NumeroItems,DuracionAplicacion,Materiales)
VALUES ('Cuestionario de Factores de Riesgo Psicosocial Intralaboral FORMA B', 'Batería para la evaluación de factores de riesgo psicosocial (intralaboral y extralaboral).', 'Julio de 2010','Ministerio de la Protección Social  Pontificia Universidad Javeriana, Subcentro de Seguridad Social y Riesgos Profesionales', '','', '','', '','', '','');
INSERT INTO Tbl_Bateria(Nombre,Descripción,Fecha_publicacion,TiposAplicacion,ModalidadesAplicacion,Poblacion,Objetivo,Baremacion,TipoInstrumento,NumeroItems,DuracionAplicacion,Materiales)
VALUES ('Cuestionario de Factores de Riesgo Psicosocial Extralaboral', 'Batería para la evaluación de factores de riesgo psicosocial (intralaboral y extralaboral).', 'Julio de 2010','Ministerio de la Protección Social  Pontificia Universidad Javeriana, Subcentro de Seguridad Social y Riesgos Profesionales', '','', '','', '','', '','');
INSERT INTO Tbl_Bateria(Nombre,Descripción,Fecha_publicacion,TiposAplicacion,ModalidadesAplicacion,Poblacion,Objetivo,Baremacion,TipoInstrumento,NumeroItems,DuracionAplicacion,Materiales)
VALUES ('Cuestionario de Factores de Estrés', 'Batería para la evaluación de factores de riesgo psicosocial (intralaboral y extralaboral).', 'Julio de 2010','Ministerio de la Protección Social  Pontificia Universidad Javeriana, Subcentro de Seguridad Social y Riesgos Profesionales', '','', '','', '','', '','');


INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Características del liderazgo','',1, '52');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Relaciones sociales en el trabajo','',1,'56');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Retroalimentación del desempeño','',1,'20');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Relación con los colaboradores','',1,'36');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Claridad de rol','',1,'28');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Capacitación','',1,'12');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Participación y manejo del cambio','',1,'16');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Oportunidades para el uso y desarrollo de habilidades y conocimientos','',1,'16');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Control y autonomía sobre el trabajo','',1,'12');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Demandas ambientales y de esfuerzo físico','',1,'48');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Demandas emocionales','',1,'36');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Demandas cuantitativas','',1,'24');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Influencia del trabajo sobre el entorno extralaboral','',1,'16');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Exigencias de responsabilidad del cargo','',1,'24');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Demandas de carga mental','',1,'20');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Consistencia del rol','',1,'20');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Demandas de la jornada de trabajo','',1,'12');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Recompensas derivadas de la pertenencia a la organización y del trabajo que se realiza','',1,'20');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Reconocimiento y compensación','',1,'24');

INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Características del liderazgo','',2,'52');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Relaciones sociales en el trabajo','',2,'48');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Retroalimentación del desempeño','',2,'20');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Claridad de rol','',2,'20');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Capacitación','',2,'12');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Participación y manejo del cambio','',2,12);
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Oportunidades para el uso y desarrollo de habilidades y conocimientos','',2,'16');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Control y autonomía sobre el trabajo','',2,'12');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Demandas ambientales y de esfuerzo físico','',2,'48');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Demandas emocionales','',2,'36');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Demandas cuantitativas','',2,'12');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Influencia del trabajo sobre el entorno extralaboral','',2,'16');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Demandas de carga mental','',2,'20');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Demandas de la jornada de trabajo','',2,'24');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Recompensas derivadas de la pertenencia a la organización y del trabajo que se realiza','',2,'16');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Reconocimiento y compensación','',2,'24');

INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Tiempo fuera del trabajo','',3,'16');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Relaciones familiares','',3,'12');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Comunicación y relaciones interpersonales','',3,'20');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Situación económica del grupo familiar','',3,'12');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Características de la vivienda y de su entorno','',3,'36');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Influencia del entorno extralaboral sobre el trabajo','',3,'12');
INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Desplazamiento vivienda  trabajo  vivienda','',3,'16');


INSERT INTO Tbl_BateriaDimension(Nombre,Descripcion,Fk_Id_Bateria,FactorTransformacion) VALUES ('Unico','',4,'61.16');


INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El ruido en el lugar donde trabajo es molesto',10,1,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En el lugar donde trabajo hace mucho frío',10,2,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En el lugar donde trabajo hace mucho calor',10,3,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El aire en el lugar donde trabajo es fresco y agradable',10,4,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('La luz del sitio donde trabajo es agradable',10,5,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El espacio donde trabajo es cómodo',10,6,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo me preocupa estar expuesto a sustancias químicas que afecten mi salud',10,7,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige hacer mucho esfuerzo físico',10,8,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Los equipos o herramientas con los que trabajo son cómodos',10,9,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo me preocupa estar expuesto a microbios, animales o plantas que afecten mi salud',10,10,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me preocupa accidentarme en mi trabajo',10,11,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El lugar donde trabajo es limpio y ordenado',10,12,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Por la cantidad de trabajo que tengo debo quedarme tiempo adicional',12,13,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me alcanza el tiempo de trabajo para tener al día mis deberes',12,14,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Por la cantidad de trabajo que tengo debo trabajar sin parar',12,15,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige hacer mucho esfuerzo mental',15,16,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige estar muy concentrado',15,17,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige memorizar mucha información',15,18,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo tengo que tomar decisiones difíciles muy rápido',14,19,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige atender a muchos asuntos al mismo tiempo',15,20,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo requiere que me fije en pequeños detalles',15,21,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo respondo por cosas de mucho valor',14,22,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo respondo por dinero de la empresa',14,23,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Como parte de mis funciones debo responder por la seguridad de otros',14,24,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Respondo ante mi jefe por los resultados de toda mi área de trabajo',14,25,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige cuidar la salud de otras personas',14,26,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En el trabajo me dan órdenes contradictorias',16,27,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo me piden hacer cosas innecesarias',16,28,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo se presentan situaciones en las que debo pasar por alto normas o procedimientos',16,29,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo tengo que hacer cosas que se podrían hacer de una forma más práctica',16,30,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Trabajo en horario de noche',17,31,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo es posible tomar pausas para descansar',12,32,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige laborar en días de descanso, festivos o fines de semana',17,33,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo puedo tomar fines de semana o días de descanso al mes',17,34,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Cuando estoy en casa sigo pensando en el trabajo',13,35,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Discuto con mi familia o amigos por causa de mi trabajo',13,36,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Debo atender asuntos de trabajo cuando estoy en casa',13,37,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Por mi trabajo el tiempo que paso con mi familia y amigos es muy poco',13,38,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me permite desarrollar mis habilidades',8,39,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me permite aplicar mis conocimientos',8,40,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me permite aprender nuevas cosas',8,41,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me asignan el trabajo teniendo en cuenta mis capacidades.',8,42,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Puedo tomar pausas cuando las necesito',12,43,4,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Puedo decidir cuánto trabajo hago en el día',9,44,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Puedo decidir la velocidad a la que trabajo',9,45,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Puedo cambiar el orden de las actividades en mi trabajo',9,46,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Puedo parar un momento mi trabajo para atender algún asunto personal',12,47,4,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Los cambios en mi trabajo han sido beneficiosos',7,48,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me explican claramente los cambios que ocurren en mi trabajo',7,49,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Puedo dar sugerencias sobre los cambios que ocurren en mi trabajo',7,50,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Cuando se presentan cambios en mi trabajo se tienen en cuenta mis ideas y sugerencias',7,51,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Los cambios que se presentan en mi trabajo dificultan mi labor',16,52,4,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me informan con claridad cuáles son mis funciones',5,53,5,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me informan cuáles son las decisiones que puedo tomar en mi trabajo',5,54,5,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me explican claramente los resultados que debo lograr en mi trabajo',5,55,5,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me explican claramente el efecto de mi trabajo en la empresa',5,56,5,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me explican claramente los objetivos de mi trabajo',5,57,5,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me informan claramente quien me puede orientar para hacer mi trabajo',5,58,5,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me informan claramente con quien puedo resolver los asuntos de trabajo',5,59,5,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('La empresa me permite asistir a capacitaciones relacionadas con mi trabajo',6,60,5,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Recibo capacitación útil para hacer mi trabajo',6,61,5,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Recibo capacitación que me ayuda a hacer mejor mi trabajo',6,62,5,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe me da instrucciones claras',1,63,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe ayuda a organizar mejor el trabajo',1,64,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe tiene en cuenta mis puntos de vista y opiniones',1,65,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe me anima para hacer mejor mi trabajo',1,66,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe distribuye las tareas de forma que me facilita el trabajo',1,67,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe me comunica a tiempo la información relacionada con el trabajo',1,68,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('La orientación que me da mi jefe me ayuda a hacer mejor el trabajo',1,69,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe me ayuda a progresar en el trabajo',1,70,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe me ayuda a sentirme bien en el trabajo',1,71,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe ayuda a solucionar los problemas que se presentan en el trabajo',1,72,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Siento que puedo confiar en mi jefe',1,73,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe me escucha cuando tengo problemas de trabajo',1,74,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe me brinda su apoyo cuando lo necesito',1,75,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me agrada el ambiente de mi grupo de trabajo',2,76,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi grupo de trabajo me tratan de forma respetuosa',2,77,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Siento que puedo confiar en mis compañeros de trabajo',2,78,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me siento a gusto con mis compañeros de trabajo',2,79,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi grupo de trabajo algunas personas me maltratan',2,80,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Entre compañeros solucionamos los problemas de forma respetuosa',2,81,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Hay integración en mi grupo de trabajo',2,82,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi grupo de trabajo es muy unido',2,83,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Las personas en mi trabajo me hacen sentir parte del grupo',2,84,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Cuando tenemos que realizar trabajo de grupo los compañeros colaboran',2,85,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Es fácil poner de acuerdo al grupo para hacer el trabajo',2,86,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mis compañeros de trabajo me ayudan cuando tengo dificultades',2,87,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo las personas nos apoyamos unos a otros',2,88,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Algunos compañeros de trabajo me escuchan cuando tengo problemas',2,89,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me informan sobre lo que hago bien en mi trabajo',3,90,8,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me informan sobre lo que debo mejorar en mi trabajo',3,91,8,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('La información que recibo sobre mi rendimiento en el trabajo es clara',3,92,8,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('La forma como evalúan mi trabajo en la empresa me ayuda a mejorar',3,93,8,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me informan a tiempo sobre lo que debo mejorar en el trabajo',3,94,8,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En la empresa confían en mi trabajo',18,95,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En la empresa me pagan a tiempo mi salario',19,96,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El pago que recibo es el que me ofreció la empresa',19,97,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El pago que recibo es el que merezco por el trabajo que realizo',19,98,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo tengo posibilidades de progresar',19,99,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Las personas que hacen bien el trabajo pueden progresar en la empresa',19,100,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('La empresa se preocupa por el bienestar de los trabajadores',19,101,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo en la empresa es estable',18,102,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El trabajo que hago me hace sentir bien',18,103,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Siento orgullo de trabajar en esta empresa',18,104,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Hablo bien de la empresa con otras personas',18,105,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Atiendo clientes o usuarios muy enojados',11,106,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Atiendo clientes o usuarios muy preocupados',11,107,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Atiendo clientes o usuarios muy tristes',11,108,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige atender personas muy enfermas',11,109,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige atender personas muy necesitadas de ayuda',11,110,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Atiendo clientes o usuarios que me maltratan',11,111,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Para hacer mi trabajo debo demostrar sentimientos distintos a los míos',11,112,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige atender situaciones de violencia',11,113,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige atender situaciones muy tristes o dolorosas',11,114,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Tengo colaboradores que comunican tarde los asuntos de trabajo',4,115,10,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Tengo colaboradores que tienen comportamientos irrespetuosos',4,116,10,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Tengo colaboradores que dificultan la organización del trabajo',4,117,10,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Tengo colaboradores que guardan silencio cuando les piden opiniones',4,118,10,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Tengo colaboradores que dificultan el logro de los resultados del trabajo',4,119,10,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Tengo colaboradores que expresan de forma irrespetuosa sus desacuerdos',4,120,10,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Tengo colaboradores que cooperan poco cuando se necesita',4,121,10,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Tengo colaboradores que me preocupan por su desempeño',4,122,10,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Tengo colaboradores que ignoran las sugerencias para mejorar su trabajo',4,123,10,1);



INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El ruido en el lugar donde trabajo es molesto',28,1,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En el lugar donde trabajo hace mucho frío',28,2,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En el lugar donde trabajo hace mucho calor',28,3,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El aire en el lugar donde trabajo es fresco y agradable',28,4,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('La luz del sitio donde trabajo es agradable',28,5,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El espacio donde trabajo es cómodo',28,6,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo me preocupa estar expuesto a sustancias químicas que afecten mi salud',28,7,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige hacer mucho esfuerzo físico',28,8,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Los equipos o herramientas con los que trabajo son cómodos',28,9,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo me preocupa estar expuesto a microbios, animales o plantas que afecten mi salud',28,10,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me preocupa accidentarme en mi trabajo',28,11,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El lugar donde trabajo es limpio y ordenado',28,12,1,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Por la cantidad de trabajo que tengo debo quedarme tiempo adicional',30,13,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me alcanza el tiempo de trabajo para tener al día mis deberes',30,14,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Por la cantidad de trabajo que tengo debo trabajar sin parar',30,15,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige hacer mucho esfuerzo mental',32,16,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige estar muy concentrado',32,17,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige memorizar mucha información',32,18,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo tengo que hacer cálculos matemáticos',32,19,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo requiere que me fije en pequeños detalles',32,20,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Trabajo en horario de noche',33,21,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo es posible tomar pausas para descansar',33,22,2,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige laborar en días de descanso, festivos o fines de semana',33,23,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo puedo tomar fines de semana o días de descanso al mes',33,24,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Cuando estoy en casa sigo pensando en el trabajo',31,25,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Discuto con mi familia o amigos por causa de mi trabajo',31,26,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Debo atender asuntos de trabajo cuando estoy en casa',31,27,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Por mi trabajo el tiempo que paso con mi familia y amigos es muy poco',31,28,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo puedo hacer cosas nuevas',26,29,3,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me permite desarrollar mis habilidades',26,30,3,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me permite aplicar mis conocimientos',26,31,3,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me permite aprender nuevas cosas',26,32,3,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Puedo tomar pausas cuando las necesito',33,33,3,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Puedo decidir cuánto trabajo hago en el día',27,34,3,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Puedo decidir la velocidad a la que trabajo',27,35,3,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Puedo cambiar el orden de las actividades en mi trabajo',27,36,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Puedo parar un momento mi trabajo para atender algún asunto personal',33,37,4,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me explican claramente los cambios que ocurren en mi trabajo',25,38,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Puedo dar sugerencias sobre los cambios que ocurren en mi trabajo',25,39,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Cuando se presentan cambios en mi trabajo se tienen en cuenta mis ideas y sugerencias',25,40,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me informan con claridad cuáles son mis funciones',23,41,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me informan cuáles son las decisiones que puedo tomar en mi trabajo',23,42,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me explican claramente los resultados que debo lograr en mi trabajo',23,43,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me explican claramente los objetivos de mi trabajo',23,44,4,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me informan claramente con quien puedo resolver los asuntos de trabajo',23,45,5,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('La empresa me permite asistir a capacitaciones relacionadas con mi trabajo',24,46,5,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Recibo capacitación útil para hacer mi trabajo',24,47,5,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Recibo capacitación que me ayuda a hacer mejor mi trabajo',24,48,5,2);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe ayuda a organizar mejor el trabajo',20,49,5,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe tiene en cuenta mis puntos de vista y opiniones',20,50,5,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe me anima para hacer mejor mi trabajo',20,51,5,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe distribuye las tareas de forma que me facilita el trabajo',20,52,5,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe me comunica a tiempo la información relacionada con el trabajo',20,53,5,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('La orientación que me da mi jefe me ayuda a hacer mejor el trabajo',20,54,5,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe me ayuda a progresar en el trabajo',20,55,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe me ayuda a sentirme bien en el trabajo',20,56,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe ayuda a solucionar los problemas que se presentan en el trabajo',20,57,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe me trata con respeto',20,58,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Siento que puedo confiar en mi jefe',20,59,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe me escucha cuando tengo problemas de trabajo',20,60,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi jefe me brinda su apoyo cuando lo necesito',20,61,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me agrada el ambiente de mi grupo de trabajo',21,62,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi grupo de trabajo me tratan de forma respetuosa',21,63,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Siento que puedo confiar en mis compañeros de trabajo',21,64,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me siento a gusto con mis compañeros de trabajo',21,65,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi grupo de trabajo algunas personas me maltratan',21,66,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Entre compañeros solucionamos los problemas de forma respetuosa',21,67,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi grupo de trabajo es muy unido',21,68,6,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Cuando tenemos que realizar trabajo de grupo los compañeros colaboran',21,69,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Es fácil poner de acuerdo al grupo para hacer el trabajo',21,70,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mis compañeros de trabajo me ayudan cuando tengo dificultades',21,71,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo las personas nos apoyamos unos a otros',21,72,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Algunos compañeros de trabajo me escuchan cuando tengo problemas',21,73,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me informan sobre lo que hago bien en mi trabajo',22,74,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me informan sobre lo que debo mejorar en mi trabajo',22,75,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('La información que recibo sobre mi rendimiento en el trabajo es clara',22,76,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('La forma como evalúan mi trabajo en la empresa me ayuda a mejorar',22,77,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me informan a tiempo sobre lo que debo mejorar en el trabajo',22,78,7,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En la empresa me pagan a tiempo mi salario',35,79,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El pago que recibo es el que me ofreció la empresa',35,80,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El pago que recibo es el que merezco por el trabajo que realizo',35,81,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi trabajo tengo posibilidades de progresar',35,82,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Las personas que hacen bien el trabajo pueden progresar en la empresa',35,83,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('La empresa se preocupa por el bienestar de los trabajadores',35,84,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo en la empresa es estable',34,85,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El trabajo que hago me hace sentir bien',34,86,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Siento orgullo de trabajar en esta empresa',34,87,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Hablo bien de la empresa con otras personas',34,88,8,4);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Atiendo clientes o usuarios muy enojados',29,89,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Atiendo clientes o usuarios muy preocupados',29,90,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Atiendo clientes o usuarios muy tristes',29,91,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige atender personas muy enfermas',29,92,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige atender personas muy necesitadas de ayuda',29,93,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Atiendo clientes o usuarios que me maltratan',29,94,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige atender situaciones de violencia',29,95,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mi trabajo me exige atender situaciones muy tristes o dolorosas',29,96,9,3);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Puedo expresar tristeza o enojo frente a las personas que atiendo',29,97,9,3);



INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Es fácil trasportarme entre mi casa y el trabajo',42,1,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Tengo que tomar varios medios de transporte para llegar a mi lugar de trabajo',42,2,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Paso mucho tiempo viajando de ida y regreso al trabajo',42,3,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me trasporto cómodamente entre mi casa y el trabajo',42,4,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('La zona donde vivo es segura',40,5,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En la zona donde vivo se presentan hurtos y mucha delincuencia',40,6,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Desde donde vivo me es fácil llegar al centro médico donde me atienden',40,7,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Cerca a mi vivienda las vías están en buenas condiciones',40,8,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Cerca a mi vivienda encuentro fácilmente transporte',40,9,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Las condiciones de mi vivienda son buenas',40,10,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi vivienda hay servicios de agua y luz',40,11,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Las condiciones de mi vivienda me permiten descansar cuando lo requiero',40,12,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Las condiciones de mi vivienda me permiten sentirme cómodo',40,13,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Me queda tiempo para actividades de recreación',36,14,2,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Fuera del trabajo tengo tiempo suficiente para descansar',36,15,2,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Tengo tiempo para atender mis asuntos personales y del hogar',36,16,2,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Tengo tiempo par a compartir con mi familia o amigos',36,17,2,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Tengo buena comunicación con las personas cercanas',38,18,2,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Las relaciones con mis amigos son buenas',38,19,2,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Converso con personas cercanas sobre diferentes temas',38,20,2,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mis amigos están dispuestos a escucharme cuando tengo problemas',38,21,2,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Cuento con el apoyo de mi familia cuando tengo problemas',37,22,2,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Puedo hablar con personas cercanas sobre las cosas que me pasan',38,23,2,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mis problemas personales o familiares afectan mi trabajo',41,24,2,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('La relación con mi familia cercana es cordial',37,25,2,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mis problemas personales o familiares me quitan la energía que necesito para trabajar',41,26,2,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Los problemas con mis familiares los resolvemos de manera amistosa',37,27,2,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Mis problemas personales o familiares afectan mis relaciones en el trabajo',41,28,3,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('El dinero que ganamos en el hogar alcanza para cubrir los gastos básicos',39,29,3,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Tengo otros compromisos económicos que afectan mucho el presupuesto familiar',39,30,3,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('En mi hogar tenemos deudas difíciles de pagar',39,31,3,1);




INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Dolores en el cuello y espalda o tensión muscular .',43,1,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Problemas gastrointestinales, úlcera péptica, acidez, problemas digestivos o del colon.',43,2,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Problemas respiratorios.',43,3,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Dolor de cabeza.',43,4,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Trastornos del sueño como somnolencia durante el día o desvelo en la noche.',43,5,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Palpitaciones en el pecho o problemas cardíacos .',43,6,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Cambios fuertes del apetito.',43,7,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Problemas relacionados con la función de los órganos genitales (impotencia, frigidez).',43,8,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Dificultad en las relaciones familiares.',43,9,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Dificultad para permanecer quieto o dificultad para iniciar actividades.',43,10,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Dificultad en las relaciones con otras personas .',43,11,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Sensación de aislamiento y desinterés.',43,12,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Sentimiento de sobrecarga de trabajo.',43,13,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Dificultad para concentrarse, olvidos frecuentes.',43,14,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Aumento en el número de accidentes de trabajo .',43,15,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Sentimiento de frustración, de no haber hecho lo que se quería en la vida.',43,16,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES (' Cansancio, tedio o desgano.',43,17,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Disminución del rendimiento en el trabajo o poca creatividad .',43,18,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Deseo de no asistir al trabajo.',43,19,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Bajo compromiso o poco interés con lo que se hace .',43,20,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Dificultad para tomar decisiones.',43,21,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Deseo de cambiar de empleo.',43,22,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Sentimiento de soledad y miedo.',43,23,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Sentimiento de irritabilidad, actitudes y pensamientos negativos.',43,24,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Sentimiento de angustia, preocupación o tristeza.',43,25,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Consumo de drogas para aliviar la tensión o los nervios .',43,26,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Sentimientos de que "no vale nada", o " no sirve para nada" .',43,27,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Consumo de bebidas alcohólicas o café o cigarrillo .',43,28,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Sentimiento de que está perdiendo la razón.',43,29,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Comportamientos rígidos, obstinación o terquedad .',43,30,1,1);
INSERT INTO Tbl_BateriaCuestionario(Pregunta, Fk_Id_BateriaDimension,Orden,Pagina,Dominio) VALUES ('Sensación de no poder manejar los problemas de la vida.',43,31,1,1);


