UPDATE Tbl_Criterios SET Descripcion = 'El diseño del Sistema de Gestión de Seguridad y Salud en el Trabajo, para empresas de diez (10) o menos trabajadores clasificadas en Riesgo I, II, III, podrá ser realizado por técnicos o tecnólogos en seguridad y Salud en el Trabajo o en alguna de sus áreas, con licencia vigente en Salud Ocupacional o Seguridad y Salud en el Trabajo que acrediten mínimo dos (2) años de experiencia en el desarrollo de actividades de Seguridad y Salud en el Trabajo y que acrediten la aprobación del curso de capacitación virtual de cincuenta (50) horas.
Para empresas de diez (10) o menos trabaja dores clasificadas en Riesgo IV y V, podrá ser realizado por un Profesional en Salud Ocupacional o Seguridad y Salud en el Trabajo, profesional con posgrado en Seguridad y Salud en el Trabajo, con licencia en Salud Ocupacional o Seguridad y Salud en el Trabajo vigente y que acrediten la aprobación del curso de capacitación virtual de cincuenta (50) horas.
La persona que diseñe, ejecute e implemente el Sistema de Gestión de Seguridad y Salud en el Trabajo tenga la formación y cursos solicitada en los artículos 5 y 6 de la presente resolución.', Marco_Legal = 'Decreto 1607/2002 Decreto 1072/2015, Artículo. 2.2.4.6.8 numerales 2 y 10. Resolución 4502/2012 Decreto 1295/1994, Artículo. 26. Artículos 5 y 6 de la presente resolución', Modo_Verificacion = 'Solicitar el documento en el que consta la designación del responsable del Sistema de Gestión de Seguridad y Salud en el Trabajo, con la respectiva asignación de responsabilidades y solicitar el certificado correspondiente, que acredite la formación de acuerdo con lo establecido en el presente criterio.
Se solicita el título de formación de técnico, tecnólogo, profesional, especialista o maestría en Seguridad y Salud en el Trabajo. Se verifica la licencia en Seguridad y Salud en el Trabajo vigente.
Se constata la existencia del certificado de aprobación del curso virtual de cincuenta (50) horas en Seguridad y Salud en el Trabajo. A quien no tenga licencia se le solicita que cumpla los requisitos de formación y cursos solicitada en los artículos 5 y 6 de la presente resolución.' WHERE Pk_Id_Criterio = 1
UPDATE Tbl_Criterios SET Descripcion = 'La empresa asignó y documentó las responsabilidades específicas en el Sistema de Gestión de Seguridad y Salud en el Trabajo a todos los niveles de la organización, para la implementación y mejora continua del Sistema de Gestión de Seguridad y Salud en el Trabajo.', Marco_Legal = 'Decreto 1072/2015 Artículo 2.2.4.6.8 numeral 2, Artículo 2.2.4.6.12 numeral 2', Modo_Verificacion = 'Solicitar el soporte que contenga la asignación y documentación de las responsabilidades en Seguridad y Salud en el Trabajo.' WHERE Pk_Id_Criterio = 2
UPDATE Tbl_Criterios SET Descripcion = 'La empresa define y asigna los recursos financieros, humanos, técnicos y tecnológicos, requeridos para la implementación, mantenimiento y continuidad del Sistema de Gestión de Seguridad y Salud en el Trabajo.', Marco_Legal = 'Decreto 1072/2015, Artículo 2.2.4.6.8. numeral 4, Artículo 2.2.4.6.17 numeral 2.5.', Modo_Verificacion = 'Constatar la existencia de evidencias físicas y/o documentales que demuestren la definición y asignación de los recursos financieros, humanos, técnicos y de otra índole para la implementación, mantenimiento y continuidad del Sistema de Gestión de Seguridad y Salud en el Trabajo, evidenciando la asignación de recursos con base en el plan de trabajo anual.' WHERE Pk_Id_Criterio = 3
UPDATE Tbl_Criterios SET Descripcion = 'Todos los trabajadores, independientemente de su forma de vinculación o contratación están afiliados al Sistema General de Riesgos Laborales y el pago de los aportes se realiza conforme a la normativa y en la respectiva clase de riesgo.', Marco_Legal = 'Decreto 2090/2003 Artículo 5. Ley 1562/2012 Artículos 2, 6 y 7. Decreto 1295/1994 Artículos 4, 16, 21 y 23. Decreto 1072/2015 Artículos:2.2.4.2.2.5. 2.2.4.2.2.6. 2.2.4.2.2.13. 2.2.4.2.3.4. 2.2.4.2.4.3. 2.2.4.3.7. 2.2.4.6.28. numeral 3. 2.2.1.6.1.3. 2.2.1.6.1.4. 2.2.1.6.4.6. 2.2.1.6.4.7. Ley 1150/2007 Artículo 23.', Modo_Verificacion = 'Solicitar una lista de los trabajadores vinculados laboralmente a la fecha y comparar con la planilla de pago de aportes a la seguridad social de los cuatro (4) meses anteriores a la fecha de verificación. Realizar el siguiente muestreo:
De uno (1) a diez (10) trabajadores verificar el 100%.
Entre once (11) y cincuenta (50) trabajadores verificar el 20%.
Entre cincuenta y uno (51) y doscientos (200) trabajadores verificar el 10%
Mayores a doscientos un (201) trabajadores verificar el registro de 30 trabajadores.
Solicitar una lista de los trabajadores vinculados por prestación de servicios a la fecha y comparar con la última planilla de pago de aportes a la seguridad social suministrada por los contratistas. Tomar:
De uno (1) a diez (10) trabajadores verificar el 100%.
Entre once (11) y cincuenta (50) trabajadores verificar el 20%.
Entre cincuenta y un (51) y doscientos (200) trabajadores verificar el 10%
Mayores a doscientos un (201) trabajadores verificar el registro de 30 trabajadores.
De la muestra seleccionada verifique la afiliación al Sistema General de Seguridad Social.
En los casos excepcionales de trabajadores independientes que se afilien a través de agremiaciones verificar que corresponda a una agremiación autorizada por el Ministerio de Salud y Protección Social, conforme al listado publicado en la página web del Ministerio del Trabajo o del Ministerio de Salud y Protección Social.' WHERE Pk_Id_Criterio = 4
UPDATE Tbl_Criterios SET Descripcion = 'Si aplica, se tienen plenamente identificados los trabajadores que se dediquen en forma permanente al ejercicio de las actividades de alto riesgo establecidas en el Decreto 2090 de 2003 o de las normas que lo adicionen, modifiquen o complementen y se les está cotizando el monto establecido en la norma al Sistema de Pensiones.
Verificar si la empresa con la asistencia de la Administradora de Riesgos Laborales está cumpliendo con lo establecido en la presente resolución para actividades de alto riesgo.', Marco_Legal = 'Decreto 2090 de 2003', Modo_Verificacion = 'Si aplica, se tienen plenamente identificados los trabajadores que se dediquen en forma permanente al ejercicio de las actividades de alto riesgo establecidas en el Decreto 2090 de 2003 o de las normas que lo adicionen, modifiquen o complementen y se les está cotizando el monto establecido en la norma al Sistema de Pensiones.' WHERE Pk_Id_Criterio = 5
UPDATE Tbl_Criterios SET Descripcion = 'La empresa cuenta, de acuerdo con el número de trabajadores con:
Vigía en Seguridad y Salud en el Trabajo para empresas de menos de diez (10) de trabajadores.
Comité Paritario en Seguridad y Salud en el Trabajo para empresas de diez (10) o más trabajadores', Marco_Legal = 'Resolución 2013/1986 Arts. 2, 3 y 11. Resolución 1401/2007 Artículo 4 numeral 5 y Artículo 7. Decreto 1295/1994 Artículo 35 literal c), Artículo 63. Decreto 1072/2015 Artículos:
2.2.4.1.6. 2.2.4.6.2. parágrafo 2, 2.2.4.6.8. numeral 9, 2.2.4.6.11. parágrafo 1, 2.2.4.6.12. numeral 10, 2.2.4.6.32. parágrafo 2, 2.2.4.6.34. numeral 4', Modo_Verificacion = 'Solicitar el acta mediante la cual se designa el Vigía de Seguridad y Salud en el Trabajo o solicitar los soportes de la convocatoria, elección, conformación del Comité Paritario de Seguridad y Salud en el Trabajo y el acta de constitución.
Constatar si es igual el número de representantes del empleador y de los trabajadores y revisar si el acta de conformación se encuentra vigente, para el caso en que proceda la constitución del Comité.
Solicitar las actas de reunión mensuales del último año del Comité Paritario o los soportes de las gestiones adelantadas por el Vigía de Seguridad y Salud en el Trabajo, y verificar el cumplimiento de sus funciones.' WHERE Pk_Id_Criterio = 6
UPDATE Tbl_Criterios SET Descripcion = 'El Vigía en Seguridad y Salud en el Trabajo y los miembros del Comité Paritario en Seguridad y Salud en el Trabajo y sus respectivos miembros (Principales y Suplentes) se encuentran capacitados para poder cumplir las responsabilidades que les asigna la ley.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.2. parágrafo 2, 2.2.4.6.8. numeral 9, 2.2.4.6.11. parágrafo 1, 2.2.4.6.12. numeral 10, 2.2.4.6.32. parágrafo 2, 2.2.4.6.34. numeral 4', Modo_Verificacion = 'Solicitar registros que constaten la capacitación y evaluación tanto para el Vigía en Seguridad
y Salud en el Trabajo o para los miembros del Comité Paritario en Seguridad y Salud en el Trabajo según aplique que estén vigentes.' WHERE Pk_Id_Criterio = 7
UPDATE Tbl_Criterios SET Descripcion = 'La empresa conformó el Comité de Convivencia Laboral y este funciona de acuerdo con la normatividad vigente.', Marco_Legal = 'Resolución 652/2012 Arts. 1, 2, 6, 7 y 8. Resolución1356/2012 Artículo 1, 2 y 3', Modo_Verificacion = 'Solicitar el documento de conformación del Comité de Convivencia Laboral y verificar que esté conformado de acuerdo a la normativa y que su período de conformación se encuentra vigente.
Solicitar las actas de las reuniones (como mínimo una reunión cada tres meses) y los informes de Gestión del Comité de Convivencia Laboral, verificando el desarrollo de sus funciones.' WHERE Pk_Id_Criterio = 8
UPDATE Tbl_Criterios SET Descripcion = 'Se cuenta con un programa de capacitación anual en promoción y prevención, que incluye los peligros/riesgos prioritarios, extensivo a todos los niveles de la organización y el mismo se ejecuta.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.11, 2.2.4.6.12 numeral 6', Modo_Verificacion = 'Solicitar el programa de capacitación anual y la matriz de identificación de peligros y verificar que el mismo esté dirigido a los peligros ya identificados, con la evaluación y control del riesgo, y/o necesidades en Seguridad y Salud en el Trabajo, y verificar las evidencias de su cumplimiento.
Verificar si el Comité Paritario en Seguridad y Salud en el Trabajo o Vigía en Seguridad y Salud en el Trabajo participó en la revisión anual del plan de capacitación.' WHERE Pk_Id_Criterio = 9
UPDATE Tbl_Criterios SET Descripcion = 'Todos los trabajadores, independientemente de su forma de vinculación y/o contratación y de manera previa al inicio de sus labores, reciben capacitación, inducción y reinducción en aspectos generales y específicos de las actividades por realizar que incluya entre otros, la identificación de peligros y control de los riesgos en su trabajo, y la prevención de accidentes de trabajo y enfermedades laborales.
Asi mismo, se proporcionan las capacitaciones en Seguridad y Salud en el Trabajo de acuerdo con las necesidades identificadas.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.8. numeral 8, 2.2.4.6.11. parágrafo 2, 2.2.4.6.12. numeral 6, 2.2.4.6.13. numeral 4, 2.2.4.6.28. numeral 4. 2.2.4.2.4.2. Resolución 2400/1979 Artículo 2. literal g).', Modo_Verificacion = 'Solicitar la lista de trabajadores, independientemente de su forma de vinculación y/o contratación y verificar los soportes documentales que den cuenta de la capacitación y de su evaluación, de la inducción y reinducción de conformidad con el criterio. La referencia es el Plan de capacitación, su cumplimento y la cobertura de los trabajadores objeto de cada tema.
Para realizar la verificación tener en cuenta:
De uno (1) a diez (10) trabajadores verificar el 100%
Entre once (11) y cincuenta (50) trabajadores verificar el 20%
Entre cincuenta y uno (51) y doscientos (200) trabajadores verificar el 10% Mayores a doscientos un (201) trabajadores verificar el registro de 30 trabajadores.' WHERE Pk_Id_Criterio = 10
UPDATE Tbl_Criterios SET Descripcion = 'Los responsables del Sistema de Gestión de Seguridad y Salud en el Trabajo cuentan con el certificado de aprobación del curso de capacitación virtual de cincuenta (50) horas definido por el Ministerio del Trabajo', Marco_Legal = 'Decreto 1072/2015 Artículo. 2.2.4.6.35', Modo_Verificacion = 'Solicitar el certificado de aprobación del curso de capacitación virtual de cincuenta (50) horas definido por el Ministerio de Trabajo, expedido a nombre del responsable del Sistema de Gestión de Seguridad y Salud en el Trabajo' WHERE Pk_Id_Criterio = 11
UPDATE Tbl_Criterios SET Descripcion = 'En el Sistema de Gestión de Seguridad y Salud en el Trabajo (SG-SST) se establece por escrito la Política de Seguridad y Salud en el Trabajo, es comunicada al Comité Paritario de Seguridad y Salud en el Trabajo o al Vigía de Seguridad y Salud en el Trabajo. La Política es fechada y firmada por el representante legal, expresa el compromiso de la alta dirección, el alcance sobre todos los centros de trabajo y todos sus trabajadores independientemente de su forma vinculación y/o contratación, es revisada, como mínimo una vez al año, hace parte de las políticas de gestión de la empresa, se encuentra difundida y accesible para todos los niveles de la organización.
Incluye como mínimo el compromiso con:
La identificación de los peligros, evaluación y valoración de los riesgos y establece los respectivos controles.
Proteger la seguridad y salud de todos los trabajadores, mediante la mejora continua
El cumplimiento de la normativa vigente aplicable en materia de riesgos laborales.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.5. 2.2.4.6.6. 2.2.4.6.7. 2.2.4.6.8. Numeral 1', Modo_Verificacion = 'Solicitar la política del Sistema de Gestión de Seguridad y Salud en el Trabajo (SG-SST), de la empresa y confirmar que cumpla con los aspectos contenidos en el criterio. Validar para la revisión anual de la política como mínimo: Fecha de emisión, firmada por el representante legal actual, que estén incluidos los requisitos normativos actuales o directrices de la empresa.
Entrevistar a los miembros del Comité Paritario de Seguridad y Salud en el Trabajo o Vigía de Seguridad y Salud en el Trabajo para indagar el entendimiento de la política en Seguridad y Salud en el Trabajo. Como referencia preguntar:
Si conocen los peligros, evaluación y valoración de los riesgos y se establecen los respectivos controles.
Si se realizan actividades de Promoción y Prevención.
Si la empresa aplica la normativa legal vigente en materia de riesgos laborales.' WHERE Pk_Id_Criterio = 12
UPDATE Tbl_Criterios SET Descripcion = 'Están definidos los objetivos del Sistema de Gestión de Seguridad y Salud en el Trabajo y ellos se expresan de conformidad con la política de Seguridad y Salud en el Trabajo, son claros, medibles, cuantificables y tienen metas, coherentes con el plan de trabajo anual, compatibles con la normativa vigente, se encuentran documentados, son comunicados a los trabajadores, son revisados y evaluados mínimo una vez al año, actualizados de ser necesario, están acordes a las prioridades definidas y se encuentran firmados por el empleador.', Marco_Legal = 'Decreto 1072/2015, Artículos: 2.2.4.6.12. numeral 1, 2.2.4.6.17. numeral 2.2 2.2.4.6.18.', Modo_Verificacion = 'Revisar si los objetivos se encuentran definidos, cumplen con las condiciones mencionadas en el criterio y existen evidencias del proceso de difusión.' WHERE Pk_Id_Criterio = 13
UPDATE Tbl_Criterios SET Descripcion = 'La empresa realizó la evaluación inicial del Sistema de Gestión de Seguridad y Salud en el Trabajo, identificando las prioridades para establecer el plan de trabajo anual o para la actualización del existente y fue realizada por el responsable del Sistema de Gestión de Seguridad y Salud en el Trabajo o si fue contratada, por la empresa con personal externo con licencia en Salud Ocupacional o Seguridad y Salud en el Trabajo o conforme, verificando que la persona que diseñe, ejecute e implemente el Sistema de Gestión de Seguridad y Salud en el Trabajo tenga la formación y cursos solicitada en los artículos 5 y 6 de la presente resolución.', Marco_Legal = 'Decreto 1072/2015 Artículo. 2.2.4.6.16. Resolución 4502/2012 Artículos 1 y 4', Modo_Verificacion = 'Solicitar la evaluación inicial del Sistema de Gestión de Seguridad y Salud en el Trabajo.
Mediante la matriz legal, matriz de peligros, identificación de amenazas, verificación de controles, reporte de peligros, lista de asistencia a capacitaciones, análisis de puestos de trabajo, exámenes médicos iniciales y periódicos y seguimiento de indicadores, entre otros.' WHERE Pk_Id_Criterio = 14
UPDATE Tbl_Criterios SET Descripcion = 'La empresa diseña y define un plan de trabajo anual para el cumplimiento del Sistema de Gestión de Seguridad y Salud en el Trabajo, el cual identifica los objetivos, metas, responsabilidades, recursos, cronograma de actividades y debe estar firmado por el empleador y el responsable del Sistema de Gestión de Seguridad y Salud en el Trabajo.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.8. numeral 7, 2.2.4.6.12. numeral 5, 2.2.4.6.17. numeral 2.3 y parágrafo 2, 2.2.4.6.20. numeral 3, 2.2.4.6.21. numeral 2, 2.2.4.6.22. numeral 3', Modo_Verificacion = 'Solicitar el plan de trabajo anual para alcanzar los objetivos propuestos en el Sistema de Gestión de Seguridad y Salud en el Trabajo, el cual identifica metas, responsabilidades, recursos, cronograma de actividades, firmado por el empleador y el responsable del Sistema de Gestión de Seguridad y Salud en el Trabajo. Verificar el cumplimiento del mismo. En caso de desviaciones en el cumplimiento, solicitar los planes de mejora para el logro del plan inicial.' WHERE Pk_Id_Criterio = 15
UPDATE Tbl_Criterios SET Descripcion = 'La empresa cuenta con un sistema de archivo o retención documental, para los registros y documentos que soportan el Sistema de Gestión de Seguridad y Salud en el Trabajo', Marco_Legal = 'Decreto 1072/2015 Artículo. 2.2.4.6.13. Archivo General de la Nación en el Acuerdo 48 del 2000, Acuerdo 49 del 2000, Acuerdo 50 del 2000 y la Ley 594 del 2000 (Ley General de Archivos para Colombia)', Modo_Verificacion = 'Constatar la existencia de un sistema de archivo o retención documental, para los registros y documentos que soportan el Sistema de Gestión de Seguridad y Salud en el Trabajo.
Verificar mediante muestreo que los registros y documentos sean legibles (entendible para el lector objeto), fácilmente identificables y accesibles (para todos los que estén vinculados con cada documento en particular), protegidos contra daño y pérdida.' WHERE Pk_Id_Criterio = 16
UPDATE Tbl_Criterios SET Descripcion = 'Quienes tengan responsabilidad sobre el Sistema de Gestión de Seguridad y Salud en el Trabajo rinden cuentas anualmente sobre su desempeño.', Marco_Legal = 'Decreto 1072/2015 Artículo. 2.2.4.6.8. numeral 3', Modo_Verificacion = 'Solicitar los registros documentales que evidencien la rendición de cuentas anual, al interior de la empresa.
Solicitar a la empresa los mecanismos de rendición de cuentas que haya definido y verificar que se haga y se cumplan con los criterios del requisito.
La rendición de cuentas debe incluir todos los niveles de la empresa ya que en cada uno de ellos hay responsabilidades sobre la Seguridad y Salud en el Trabajo' WHERE Pk_Id_Criterio = 17
UPDATE Tbl_Criterios SET Descripcion = 'La empresa define la matriz legal actualizada que contemple las normas del Sistema General de Riesgos Laborales aplicables a la empresa.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.8. numeral 5, 2.2.4.6.12. numeral 15, 2.2.4.6.17. numeral 1.1', Modo_Verificacion = 'Solicitar la matriz legal en la cual se contemple la legislación nacional vigente en materia de riesgos laborales.
Verificar que contenga:
Normas vigentes en riesgos laborales, aplicables a la empresa.
Normas técnicas de cumplimiento de acuerdo con los peligros / riesgos identificados en la empresa.
Normas vigentes de diferentes entidades que le aplique.' WHERE Pk_Id_Criterio = 18
UPDATE Tbl_Criterios SET Descripcion = 'La empresa dispone de mecanismos eficaces para recibir y responder las comunicaciones internas y externas relativas a la Seguridad y Salud en el Trabajo, como por ejemplo autoreporte de condiciones de trabajo y de salud por parte de los trabajadores o contratistas.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.14. 2.2.4.6.16. Parágrafo 3
2.2.4.6.28. numeral 2', Modo_Verificacion = 'Constatar la existencia de mecanismos de comunicación interna y externa que tiene la empresa en materia de Seguridad y Salud en el Trabajo y comprobar que las acciones que se desarrollaron para dar respuesta a las comunicaciones recibidas son eficaces.' WHERE Pk_Id_Criterio = 19
UPDATE Tbl_Criterios SET Descripcion = 'La empresa estableció un procedimiento para la identificación y evaluación de las especificaciones en Seguridad y Salud en el Trabajo, de las compras y adquisición de productos y servicios, como por ejemplo los elementos de protección personal.', Marco_Legal = 'Decreto 1072/2015 Artículo 2.2.4.6.27 Resolución 2400/1979 Artículos 177 y 178.', Modo_Verificacion = 'Verificar el cumplimiento del procedimiento para la identificación y evaluación de las especificaciones en Seguridad y Salud en el Trabajo de las compras o adquisición de productos y servicios, como por ejemplo los elementos de protección personal. Verificar la existencia de la matriz de elementos de protección personal.' WHERE Pk_Id_Criterio = 20
UPDATE Tbl_Criterios SET Descripcion = 'La empresa incluye los aspectos de Seguridad y Salud en el Trabajo en la evaluación y selección de proveedores y contratistas.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.4. parágrafo 2, 2.2.4.6.28. numeral 1', Modo_Verificacion = 'Constatar que para la selección y evaluación de proveedores y/o contratistas, se valida que dichos proveedores o contratistas tienen documentado e implementado el Sistema de Gestión de Seguridad y Salud en el Trabajo y que conocen los peligros/riesgos y la forma de controlarlos al ejecutar el servicio por realizar en la empresa dónde prestan el servicio.' WHERE Pk_Id_Criterio = 21
UPDATE Tbl_Criterios SET Descripcion = 'La empresa dispone de un procedimiento para evaluar el impacto sobre la Seguridad y Salud en el Trabajo que se pueda generar por cambios internos o externos.', Marco_Legal = 'Decreto 1072/2015 Artículo 2.2.4.6.26', Modo_Verificacion = 'Solicitar el documento para evaluar el impacto sobre la Seguridad y Salud en el Trabajo en cambios internos y externos que se presenten en la entidad.' WHERE Pk_Id_Criterio = 22
UPDATE Tbl_Criterios SET Descripcion = 'Hay como mínimo, la siguiente información actualizada de todos los trabajadores, del último año: la descripción socio demográfica de los trabajadores (edad, sexo, escolaridad, estado civil), la caracterización de sus condiciones de salud, la evaluación y análisis de las estadísticas sobre la salud de los trabajadores tanto de origen laboral como común, y los resultados de las evaluaciones médicas ocupacionales.', Marco_Legal = 'Resolución 2346/2007 Artículo 8. Artículo 15 Artículo. 18. Decreto 1072/2015 Artículos: 2.2.4.2.2.18 2.2.4.6.12. numeral 4 2.2.4.6.13 numerales 1 y 2, 2.2.4.6.16. numeral 7 y parágrafo 1.', Modo_Verificacion = 'Solicitar el documento consolidado que evidencie el cumplimiento de lo requerido en el criterio.' WHERE Pk_Id_Criterio = 23
UPDATE Tbl_Criterios SET Descripcion = 'Están definidas y se llevaron a cabo las actividades de medicina del trabajo, promoción y prevención, de conformidad con las prioridades que se identificaron en el diagnóstico de las condiciones de salud de los trabajadores y los peligros/riesgos de intervención prioritarios', Marco_Legal = 'Resolución 2346/2007 Artículo 18. Decreto 1072/2015 Artículos: 2.2.4.6.8. numeral 8, Art 2.2.4.6.12. numerales 4, 13 y 16 2.2.4.6.20. numeral 9 2.2.4.6.21. numeral 5, 2.2.4.6.24. Parágrafo 3', Modo_Verificacion = 'Solicitar las evidencias que constaten la definición y ejecución de las actividades de medicina del trabajo, promoción y prevención de conformidad con las prioridades que se identificaron con base a los resultados del diagnóstico de las condiciones de salud y los peligros/riesgos de intervención prioritarios.
Solicitar el programa de vigilancia epidemiológica de los trabajadores.' WHERE Pk_Id_Criterio = 24
UPDATE Tbl_Criterios SET Descripcion = 'Se informa al médico que realiza las evaluaciones ocupacionales los perfiles del cargo, con una descripción de las tareas y el medio en el cual se desarrollará la labor respectiva.', Marco_Legal = 'Resolución 2346/2007 Artículo 4.', Modo_Verificacion = 'Verificar que al médico que realiza las evaluaciones ocupacionales, se le remitieron los soportes documentales respecto de los perfiles del cargo, descripción de las tareas y el medio en el cual desarrollará la labor los trabajadores.' WHERE Pk_Id_Criterio = 25
UPDATE Tbl_Criterios SET Descripcion = 'Se realizan las evaluaciones médicas de acuerdo con la normativa y los peligros a los cuales se encuentre expuesto el trabajador.
Asimismo, se tiene definida la frecuencia de las evaluaciones médicas ocupacionales periódicas según tipo, magnitud, frecuencia de exposición a cada peligro, el estado de salud del trabajador, las recomendaciones de los sistemas de vigilancia epidemiológica y la legislación vigente.
Los resultados de las evaluaciones médicas ocupacionales serán comunicados por escrito al trabajador y constarán en su historia médica.', Marco_Legal = 'Resolución 2346/2007 Artículo 5. Decreto 1072/2015 Artículos: 2.2.4.6.12. numeral 4 y 13. 2.2.4.6.24. parágrafo 3 Resolución 957/2005 Comunidad Andina de Naciones Artículo. 17', Modo_Verificacion = 'Solicitar los conceptos de aptitud que demuestren la realización de las evaluaciones médicas.
Solicitar el documento o registro que evidencie la definición de la frecuencia de las evaluaciones médicas periódicas.
Solicitar el documento que evidencie la comunicación por escrito al trabajador de los resultados de las evaluaciones médicas ocupacionales.' WHERE Pk_Id_Criterio = 26
UPDATE Tbl_Criterios SET Descripcion = 'La empresa debe tener la custodia de las historias clínicas a cargo de una institución prestadora de servicios en Seguridad y Salud en el Trabajo o del médico que practica los exámenes laborales en la empresa.', Marco_Legal = 'Resolución 2346/2007 Artículos 16 y 17 modificado por la Resolución 1918/2009 Artículo 2 Decreto 1072/2015 Artículo 2.2.4.6.13 numerales 1 y 2', Modo_Verificacion = 'Evidenciar los soportes que demuestren que la custodia de las historias clínicas esté a cargo de una institución prestadora de servicios en Seguridad y Salud en el Trabajo o del médico que practica los exámenes laborales en la empresa.' WHERE Pk_Id_Criterio = 27
UPDATE Tbl_Criterios SET Descripcion = 'La empresa acata las restricciones y recomendaciones médico-laborales por parte de la Empresa Promotora de Salud (EPS) o Administradora de Riesgos Laborales (ARL) prescritas a los trabajadores para la realización de sus funciones.
Asimismo, y de ser necesario, se adecua el puesto de trabajo, se reubica al trabajador o realiza la readaptación laboral.
Se anexa soportes de entrega a quienes califican en primera oportunidad y/o a las Juntas de Calificación de Invalidez los documentos que son responsabilidad del empleador que trata la norma para la calificación de origen y porcentaje de la pérdida de la capacidad laboral.', Marco_Legal = 'Decreto 2177/1989 Artículo. 16 Ley 776/2002 Artículos 4 y 8 Resolución 2844/ 2007 Artículo 1, parágrafo. Resolución 1013/ 2008 Artículo 1, parágrafo. Manual de procedimientos para la rehabilitación y reincorporación ocupacional. Decreto 1072/2015 Artículo 2.2.5.1.28.', Modo_Verificacion = 'Solicitar documento de recomendaciones y restricciones a trabajadores y revisar que la empresa ha acatado todas las recomendaciones y restricciones médico-laborales prescritas a to-
dos los trabajadores y ha realizado las acciones que se requieran en materia de reubicación o readaptación.
Solicitar documento de soporte de recibido por parte de quienes califican en primera oportunidad y/o a las Juntas de Calificación de Invalidez.' WHERE Pk_Id_Criterio = 28
UPDATE Tbl_Criterios SET Descripcion = 'Hay un programa para promover entre los trabajadores estilos de vida y entorno saludable, incluyendo campañas específicas tendientes a la prevención y el control de la farmacodependencia, el alcoholismo y el tabaquismo, entre otros.', Marco_Legal = 'Decreto 1295/1994 Artículo 35 numeral d) Ley 1562/2012 Artículo 11 literal f) Resolución 1075/1992 Artículo 1 Ley 1355 de 14 de octubre de 2009, Artículo 5 parágrafo.', Modo_Verificacion = 'Solicitar el programa respectivo y los documentos y registros que evidencien el cumplimiento del mismo.' WHERE Pk_Id_Criterio = 29
UPDATE Tbl_Criterios SET Descripcion = 'En la sede hay suministro permanente de agua potable, servicios sanitarios y mecanismos para disponer excretas y basuras.', Marco_Legal = 'Ley 9 /1979 Artículo. 10, 36, 129 y 285 Resolución 2400/1979 Artículo 24, 42', Modo_Verificacion = 'Mediante observación directa, verificar si se cumple lo que se exige en el criterio, dejando prueba fotográfica o fílmica al respecto.' WHERE Pk_Id_Criterio = 30
UPDATE Tbl_Criterios SET Descripcion = 'La empresa elimina los residuos sólidos, líquidos o gaseosos que se producen, así como los residuos peligros de forma que no se ponga en riesgo a los trabajadores.', Marco_Legal = 'Ley 9 /1979 Artículos 10, 22 y 129', Modo_Verificacion = 'Mediante observación directa, constatar las evidencias en las que se dé cuenta de los procesos de eliminación de residuos conforme al criterio y solicitar contrato de empresa que elimina y dispone de los residuos peligrosos.' WHERE Pk_Id_Criterio = 31
UPDATE Tbl_Criterios SET Descripcion = 'La empresa reporta a la Administradora de Riesgos Laborales (ARL), a la Entidad Promotora de Salud (EPS) todos los accidentes y las enfermedades laborales diagnosticadas. Asimismo, reportará a la Dirección Territorial el accidente grave y mortal, como las enfermedades diagnosticadas como laborales.
Estos reportes se realizarán dentro de los dos (2) días hábiles siguientes al evento o recibo del diagnóstico de la enfermedad.', Marco_Legal = 'Resolución 1401/2007 Artículo 14 Decreto Ley 19/2012 Artículo 140 Decreto 1295/1994 Artículo 21 literal e) y Artículo 62 Resolución 156/2005 Resolución 2851/2015 Artículo 1 Decreto 1072/2015 Artículos: 2.2.4.6.12. numeral 11, 2.24.6.21 numeral 9, 2.2.4.2.4.5 2.2.4.1.7', Modo_Verificacion = 'Indagar con los trabajadores, si se han presentado accidentes de trabajo o enfermedades laborales (en caso afirmativo, tomar los datos de nombre y número de cédula y solicitar el reporte). Igualmente realizar un muestreo del reporte de registro de accidente de trabajo (Furat) y el registro de enfermedades laborales (Furel) respectivo, verificando si el reporte a las Ad-
ministradoras de Riesgos Laborales, Empresas Promotoras de Salud y Dirección Territorial se hizo dentro de los dos (2) días hábiles siguientes al evento o recibo del diagnóstico de la enfermedad.' WHERE Pk_Id_Criterio = 32
UPDATE Tbl_Criterios SET Descripcion = 'La empresa investiga todos los accidentes e incidentes de trabajo y las enfermedades cuando sean diagnosticadas como laborales, determinando las causas básicas e inmediatas y la posibilidad de que se presenten nuevos casos.', Marco_Legal = 'Resolución 1401/2007 Artículo 4 numerales 2, 3 y 4, Artículo 7. Artículo 14 Decreto 1072/2015 Artículos: 2.2.4.1.6 2.2.4.6.21. numeral 9, 2.2.4.6.32.', Modo_Verificacion = 'Verificar por medio de un muestreo si se investigan los accidentes e incidentes de trabajo y las enfermedades laborales y si se definieron acciones para otros trabajadores potencialmente expuestos.
Constatar que la investigación se haya realizado dentro de los quince (15) días siguientes a su ocurrencia a través del equipo investigador y evidenciar que se hayan remitido los informes de las investigaciones de accidente de trabajo grave o mortal o una enfermedad laboral mortal.
En caso de haber accidente grave o se produzca la muerte verificar la participación de un profesional con licencia Salud Ocupacional o en Seguridad y Salud en el Trabajo en la investigación (propio o contratado), así como del Comité Paritario o Vigía de Seguridad y Salud en el Trabajo.' WHERE Pk_Id_Criterio = 33
UPDATE Tbl_Criterios SET Descripcion = 'Hay un registro estadístico de los incidentes y de los accidentes de trabajo, así como de las enfermedades laborales que ocurren; se analiza este registro y las conclusiones derivadas del estudio son usadas para el mejoramiento del Sistema de Gestión de Seguridad y Salud en el Trabajo.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.16. numeral 7, 2.2.4.6.21. numeral 10, 2.2.4.6.22. numeral 8. Decreto 1295/1994 Artículo 61', Modo_Verificacion = 'Solicitar el registro estadístico actualizado de lo corrido del año y el año inmediatamente anterior al de la visita, así como la evidencia que contiene el análisis y las conclusiones derivadas del estudio que son usadas para el mejoramiento del SG-SST.' WHERE Pk_Id_Criterio = 34
UPDATE Tbl_Criterios SET Descripcion = 'La empresa mide la severidad de los accidentes de trabajo como mínimo una vez al año y realiza la clasificación del origen del peligro/riesgo que los generó (físicos, químicos, biológicos, de seguridad, públicos, psicosociales, entre otros).', Marco_Legal = 'Resolución 1401/2007 Artículo 4 Decreto 1072/2015 Artículo 2.2.4.6.2 nums. 7, 18 y 34', Modo_Verificacion = 'Solicitar los resultados de la medición para lo corrido del año y/o el año inmediatamente anterior y constatar el comportamiento de la severidad y la relación del evento con los peligros/riesgos.' WHERE Pk_Id_Criterio = 35
UPDATE Tbl_Criterios SET Descripcion = 'La empresa mide la frecuencia de los accidentes e incidentes de trabajo y enfermedad laboral como mínimo una vez al año y realiza la clasificación del origen del peligro/riesgo que los generó (físicos, de químicos, biológicos, seguridad, públicos, psicosociales, entre otros.)', Marco_Legal = 'Resolución 1401/2007 Artículo 4 Decreto 1072/2015 Artículos: 2.2.4.6.21. numeral 10', Modo_Verificacion = 'Solicitar los resultados de la medición para lo corrido del año y/o el año inmediatamente anterior y constatar el comportamiento de la frecuencia de los accidentes y la relación del evento con los peligros/riesgos.' WHERE Pk_Id_Criterio = 36
UPDATE Tbl_Criterios SET Descripcion = 'La empresa mide la mortalidad por accidentes de trabajo y enfermedades laborales como mínimo una vez al año y realiza la clasificación del origen del peligro/riesgo que los generó (físicos, químicos, biológicos, de seguridad, públicos, psicosociales, entre otros)', Marco_Legal = 'Resolución 1401/2007 Artículo 4 Decreto 1072/2015 Artículos: 2.2.4.6.21 numeral 10', Modo_Verificacion = 'Solicitar los resultados de la medición para lo corrido' WHERE Pk_Id_Criterio = 37
UPDATE Tbl_Criterios SET Descripcion = 'La empresa mide la prevalencia de la enfermedad laboral como mínimo una vez al año y realiza la clasificación del origen del peligro/riesgo que la generó (físico, químico, biológico, ergonómico o biomecánico, psicosocial, entre otros)', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.21. numeral 10', Modo_Verificacion = 'Solicitar los resultados de la medición para lo corrido del año y/o el año inmediatamente anterior y constatar el comportamiento de la prevalencia de las enfermedades laborales y la relación del evento con los peligros/riesgos.' WHERE Pk_Id_Criterio = 38
UPDATE Tbl_Criterios SET Descripcion = 'La empresa mide la incidencia de la enfermedad laboral como mínimo una vez al año y realiza la clasificación del origen del peligro/riesgo que la generó (físicos, químicos, biológicos, ergonómicos o biomecánicos, psicosociales, entre otros)', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.21 numeral 10', Modo_Verificacion = 'Solicitar los resultados de la medición para lo corrido del año y/o el año inmediatamente anterior y constatar el comportamiento de la incidencia de las enfermedades laborales y la relación del evento con los peligros/riesgos.' WHERE Pk_Id_Criterio = 39
UPDATE Tbl_Criterios SET Descripcion = 'La empresa mide el ausentismo por enfermedad laboral y común y por accidente de trabajo, como mínimo una vez al año y realiza la clasificación del origen del peligro/riesgo que lo generó (físicos, ergonómicos, o biomecánicos, químicos, de seguridad, públicos, psicosociales, entre otros)', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.21 numeral 10', Modo_Verificacion = 'Solicitar los resultados de la medición para lo corrido del año y/o el año inmediatamente anterior y constatar el comportamiento del ausentismo y la relación del evento con los peligros/riesgos.' WHERE Pk_Id_Criterio = 40
UPDATE Tbl_Criterios SET Descripcion = 'La empresa tiene definida y aplica una metodología para la identificación de peligros y evaluación y valoración de los riesgos de origen físico, ergonómico o biomecánico, biológico,
químico, de seguridad, público, psicosocial, entre otros, con alcance sobre todos los procesos, actividades rutinarias y no rutinarias, maquinaria y equipos en todos los centros de trabajo y en todos los trabajadores independientemente de su forma de vinculación y/o contratación.
Identificar con base en la valoración de los riesgos, aquellos que son prioritarios.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.15., 2.2.4.6.16. numeral 2.', Modo_Verificacion = 'Verificar que se realiza la identificación de peligros, evaluación y valoración de los riesgos conforme a la metodología definida de acuerdo con el criterio y con la participación de los trabajadores, seleccionando de manera aleatoria algunas de las actividades identificadas.
Confrontar mediante observación directa durante el recorrido a las instalaciones de la empresa la identificación de peligros.' WHERE Pk_Id_Criterio = 41
UPDATE Tbl_Criterios SET Descripcion = 'La identificación de peligros, evaluación y valoración del riesgo se desarrolló con la participación de trabajadores de todos los niveles de la empresa y es actualizada como mínimo una vez al año y cada vez que ocurra un accidente de trabajo mortal o un evento catastrófico en la empresa o cuando se presenten cambios en los procesos, en las instalaciones, o maquinaria o equipos.', Marco_Legal = 'Decreto 1072/2015 Artículo. 2.2.4.6.15. Parágrafo 1 2.2.4.6.23', Modo_Verificacion = 'Verificar que estén identificados los peligros, evaluados y valorados los riesgos, con la participación de los trabajadores.
Solicitar si hay eventos mortales o catastróficos y validar que el peligro asociado al evento esté identificado, evaluado y valorado.
En caso de que se encuentren valoraciones no tolerables, verificar la implementación de las acciones de intervención y control, de forma inmediata para continuar con la tarea.' WHERE Pk_Id_Criterio = 42
UPDATE Tbl_Criterios SET Descripcion = 'La empresa donde se procese, manipule o trabaje con agentes o sustancias catalogadas como carcinógenas o con toxicidad aguda, causantes de enfermedades, incluidas en la tabla de enfermedades laborales, prioriza los riesgos asociados a estas sustancias o agentes y realiza acciones de prevención e intervención al respecto.', Marco_Legal = 'Ley 1562/2012 Artículo 9 Decreto 1072/2015 Artículo 2.2.4.6.15. parágrafo 2.', Modo_Verificacion = 'Revisar la lista de materias primas e insumos, productos intermedios o finales, subproductos y desechos y verificar si estas son o están compuestas por agentes o sustancias catalogadas como carcinógenas en el grupo 1 de la clasificación de la Agencia Internacional de Investigación sobre el Cáncer (International Agency for Research on Cancer, IARC) o con toxicidad aguda según los criterios del Sistema Globalmente Armonizado (categorías I y II).
Se debe verificar que los riesgos asociados a estas sustancias o agentes carcinógenos o con toxicidad aguda son priorizados y se realizan acciones de prevención e intervención.
Asimismo, se debe verificar la existencia de áreas destinadas para el almacenamiento de las materias primas e insumos y sustancias catalogadas como carcinógenas o con toxicidad aguda.' WHERE Pk_Id_Criterio = 43
UPDATE Tbl_Criterios SET Descripcion = 'Se realizan mediciones ambientales de los riesgos prioritarios, provenientes de peligros químicos, físicos y/o biológicos.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.15. Resolución 2400/1979 Título III', Modo_Verificacion = 'Verificar los soportes documentales de las mediciones ambientales realizadas y la remisión de estos resultados al Comité Paritario en Seguridad y Salud en el Trabajo o al Vigía de Seguridad y Salud en el Trabajo.' WHERE Pk_Id_Criterio = 44
UPDATE Tbl_Criterios SET Descripcion = 'Se implementan las medidas de prevención y control con base en el resultado de la identificación de peligros, la evaluación y valoración de los riesgos (físicos, ergonómicos, biológicos, químicos, de seguridad, públicos, psicosociales, entre otros), incluidos los prioritarios y éstas se ejecutan acorde con el esquema de jerarquización, de ser factible priorizar la intervención en la fuente y en el medio.', Marco_Legal = 'Decreto 1072/2015 Artículos 2.2.4.6.15, 2.2.4.6.24 Resolución 2400/1979 Capítulo I al VII Artículos del 63 al 152 Ley 9/1979 Artículos 105 al 109.', Modo_Verificacion = 'Verificar la implementación de las medidas de prevención y control, de acuerdo al esquema de jerarquización y de conformidad con la identificación de los peligros, la evaluación y valoración de los riesgos (físicos, ergonómicos, biológicos, químicos, de seguridad, públicos, psicosociales, entre otros), realizada.
Verificar que estas medidas se encuentran programadas en el plan anual de trabajo. Constatar que se dio preponderancia a las medidas de prevención y control, respecto de los peligros/riesgos prioritarios.' WHERE Pk_Id_Criterio = 45
UPDATE Tbl_Criterios SET Descripcion = 'Se verifica la aplicación por parte de los trabajadores de las medidas de prevención y control de los peligros /riesgos (físicos, ergonómicos, biológicos, químicos, de seguridad, públicos, psicosociales, entre otros).', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.10, 2.2.4.6.24. parágrafo 1, 2.2.4.6.28 numeral 6 Resolución 2400/1979 Artículo 3, capítulos I al VII del Título III Artículos del 63 al 152 Ley 9/1979 Artículos del 105 al 109', Modo_Verificacion = 'Solicitar los soportes documentales implementados por la empresa donde se verifica el cumplimiento de las responsabilidades de los trabajadores frente a la aplicación de las medidas de prevención y control de los peligros/riesgos (físicos, ergonómicos, biológicos, químicos, de seguridad, públicos, psicosociales, entre otros).
Realizar visita a las instalaciones para verificar el cumplimiento de las medias de prevención y control por parte de los trabajadores de acuerdo con lo enunciado en los planes de prevención y control descritos.' WHERE Pk_Id_Criterio = 46
UPDATE Tbl_Criterios SET Descripcion = 'La empresa para los peligros identificados ha estructurado programa de prevención y protección de la seguridad y salud de las personas (incluye procedimientos, instructivos, fichas técnicas).', Marco_Legal = 'Decreto 1072/2015 Artículo 2.2.4.6.12 numerales 7 y 9', Modo_Verificacion = 'Solicitar los procedimientos, instructivos, fichas técnicas cuando aplique y protocolos de Seguridad y Salud en el Trabajo,' WHERE Pk_Id_Criterio = 47
UPDATE Tbl_Criterios SET Descripcion = 'Se realizan inspecciones sistemáticas a las instalaciones, maquinaria o equipos, incluidos los relacionados con la prevención y atención de emergencias; con la participación del Comité Paritario o Vigía de Seguridad y Salud en el Trabajo.', Marco_Legal = 'Decreto 1072/2015, Artículos: 2.2.4.6.12 numeral 14, 2.2.4.6.24 parágrafos 1 y 2, 2.2.4.6.25 numeral 12', Modo_Verificacion = 'Solicitar la evidencia de las inspecciones realizadas a las instalaciones, maquinaria y equipos, incluidos los relacionados con la prevención y atención de emergencias y verificar la participación del Comité Paritario o Vigía de Seguridad y Salud en el Trabajo.' WHERE Pk_Id_Criterio = 48
UPDATE Tbl_Criterios SET Descripcion = 'Se realiza el mantenimiento periódico de las instalaciones, equipos y herramientas, de acuerdo con los informes de las inspecciones o reportes de condiciones inseguras.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.12 numeral 14, 2.2.4.6.24 parágrafos 1 y 2, 2.2.4.6.25 numeral 12', Modo_Verificacion = 'Solicitar la evidencia del mantenimiento preventivo y/o correctivo en las instalaciones, equipos y herramientas de acuerdo con los manuales de uso de estos y los informes de las inspecciones o reportes de condiciones inseguras.' WHERE Pk_Id_Criterio = 49
UPDATE Tbl_Criterios SET Descripcion = 'Se les suministran a los trabajadores que lo requieran los Elementos de Protección Personal y se les reponen oportunamente conforme al desgaste y condiciones de uso de los mismos.
Se verifica que los contratistas y subcontratistas que tengan trabajadores realizando actividades en la empresa, en su proceso de producción o de prestación de servicios se les entrega los Elementos de Protección Personal y se hace reposición oportunamente conforme al desgaste y condiciones de uso de los mismos.
Se realiza la capacitación para el uso de los Elementos de Protección Personal', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.2.4.2. 2.2.4.2.2.16 2.2.4.6.12. numeral 8, 2.2.4.6.13. numeral 4, 2.2.4.6.24. Numeral 5 y parágrafo 1. Resolución 2400/1979 Artículo 2 literales f) y g), Artículos 176,177 y 178. Ley 9 /1979 Artículo del 122 al 124.', Modo_Verificacion = 'Solicitar los soportes que evidencien la entrega y reposición de los Elementos de Protección Personal a los trabajadores.
Asimismo, verificar los soportes que den cuenta del cumplimiento del criterio por parte de los contratistas y subcontratistas.
Verificar los soportes que evidencien la realización de la capacitación en el uso de los Elementos de Protección Personal.
Establecer si hay documentos escritos o pruebas de la entrega de los elementos de protección personal a los trabajadores.' WHERE Pk_Id_Criterio = 50
UPDATE Tbl_Criterios SET Descripcion = 'Se tiene un plan de prevención, preparación y respuesta ante emergencias que identifica las amenazas, evalúa y analiza la vulnerabilidad, incluye planos de las instalaciones que identifican áreas y salidas de emergencia, así como la señalización debida, simulacros como mínimo una vez al año y este es divulgado. Se tienen en cuenta todas las jornadas de trabajo en todos los centros de trabajo', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.12. numeral 12, 2.2.4.6.25. 2.2.4.6.28. numeral 4', Modo_Verificacion = 'Solicitar el plan de prevención, preparación y respuesta ante emergencias, constatar su divulgación.
Verificar si existen los planos de las instalaciones que identifican áreas y salidas de emergencia y verificar si existe la debida señalización de la empresa y los soportes que evidencien la realización de los simulacros.
Verificar la realización de simulacros y análisis del mismo, validar que las mejoras hayan sido tenidas en cuenta en el mejoramiento del plan.' WHERE Pk_Id_Criterio = 51
UPDATE Tbl_Criterios SET Descripcion = 'Se encuentra conformada, capacitada y dotada la brigada de prevención, preparación y respuesta ante emergencias, organizada según las necesidades y el tamaño de la empresa (primeros auxilios, contra incendios, evacuación, etc.).', Marco_Legal = 'Decreto 1072/2015 Artículo 2.2.4.6.25 numeral 11', Modo_Verificacion = 'Solicitar el documento de conformación de la brigada de prevención, preparación y respuesta ante emergencias y verificar los soportes de la capacitación y entrega de la dotación.' WHERE Pk_Id_Criterio = 52
UPDATE Tbl_Criterios SET Descripcion = 'El empleador tiene definidos los indicadores de estructura, proceso y resultado del Sistema de Gestión de Seguridad y Salud en el Trabajo.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.19., 2.2.4.6.20., 2.2.4.6.21., 2.2.4.6.22.', Modo_Verificacion = 'Solicitar los indicadores de estructura, proceso y resultado del Sistema de Gestión de Seguridad y Salud en el Trabajo que se encuentren alineados al plan estratégico de la empresa.' WHERE Pk_Id_Criterio = 53
UPDATE Tbl_Criterios SET Descripcion = 'El empleador debe realizar una auditoría anual, la cual será planificada con la participación del Comité Paritario o Vigía de Seguridad y Salud en el Trabajo.', Marco_Legal = 'Decreto 1072/2015 Artículo 2.2.4.6.29.', Modo_Verificacion = 'La empresa adelantará por lo menos una vez al año, un ciclo completo de auditorías internas al SG-SST, en donde su alcance deberá incluir todas las áreas.
Solicitar el programa de la auditoría, el alcance de la auditoría, la periodicidad, la metodología y la presentación de informes y verificar que se haya planificado con la participación del Comité Paritario o Vigía de Seguridad y Salud en el Trabajo.' WHERE Pk_Id_Criterio = 54
UPDATE Tbl_Criterios SET Descripcion = 'Alcance de la auditoría de cumplimiento del Sistema de Gestión de Seguridad y Salud en el Trabajo.', Marco_Legal = 'Decreto 1072/2015 Artículo 2.2.4.6.30', Modo_Verificacion = 'Se debe solicitar a la empresa los documentos, pruebas de la realización de actividades y obligaciones establecidas en los trece numerales del artículo 2.2.4.6.30 del Decreto 1072/2015' WHERE Pk_Id_Criterio = 55
UPDATE Tbl_Criterios SET Descripcion = 'La Alta Dirección revisa una vez al año el Sistema de Gestión de Seguridad y Salud en el Trabajo; sus resultados son comunicados al Comité Paritario de Seguridad y Salud en el Trabajo o al Vigía de Seguridad y Salud en el Trabajo y al responsable del Sistema de Gestión de Seguridad y Salud en el Trabajo.', Marco_Legal = 'Decreto 1072/2015 Artículo. 2.2.4.6.31', Modo_Verificacion = 'Solicitar el documento donde conste la revisión anual por la Alta Dirección, así como la comunicación de los resultados al Comité Paritario de Seguridad y Salud en el Trabajo o al Vigía
de Seguridad y Salud en el Trabajo y al responsable del Sistema de Gestión de Seguridad y Salud en el Trabajo.' WHERE Pk_Id_Criterio = 56
UPDATE Tbl_Criterios SET Descripcion = 'La empresa garantiza que se definan e implementen las acciones preventivas y/o correctivas necesarias con base en los resultados de la supervisión, inspecciones, la medición de los indicadores del Sistema de Gestión de Seguridad y Salud en el Trabajo entre otros, y las recomendaciones del COPASST o Vigía.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.33, 2.2.4.6.34', Modo_Verificacion = 'Solicitar la evidencia documental de la implementación de las acciones preventivas y/o correctivas provenientes de los resultados y/o recomendaciones, de conformidad con el criterio.' WHERE Pk_Id_Criterio = 57
UPDATE Tbl_Criterios SET Descripcion = 'Cuando después de la revisión por la Alta Dirección del Sistema de Gestión de Seguridad y Salud en el Trabajo se evidencia que las medidas de prevención y control relativas a los peligros y riesgos en Seguridad y Salud en el Trabajo son inadecuadas o pueden dejar de ser eficaces, la empresa toma las medidas correctivas, preventivas y/o de mejora para subsanar lo detectado.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.31. parágrafo, 2.2.4.6.33., 2.2.4.6.34.', Modo_Verificacion = 'Solicitar la evidencia documental de las acciones correctivas, preventivas y/o de mejora que se implementaron según lo detectado en la revisión por la Alta Dirección del Sistema de Gestión de Seguridad y Salud en el Trabajo.' WHERE Pk_Id_Criterio = 58
UPDATE Tbl_Criterios SET Descripcion = 'La empresa ejecuta las acciones preventivas, correctivas y de mejora que se plantean como resultado de la investigación de los accidentes y de los incidentes y la determinación de las causas básicas e inmediatas de las enfermedades laborales.', Marco_Legal = 'Decreto 1072/2015 Artículos: 2.2.4.6.21 numeral 6, 2.2.4.6.22 numeral 5, 2.2.4.6.33, 2.2.4.6.34 Resolución 1401/2007 Artículo 12', Modo_Verificacion = 'Solicitar la evidencia documental de las acciones preventivas, correctivas y/o de mejora planteadas como resultado de las investigaciones y verificar si han sido efectivas.' WHERE Pk_Id_Criterio = 59
UPDATE Tbl_Criterios SET Descripcion = 'Se implementan las medidas y acciones correctivas producto de requerimientos o recomendaciones de autoridades administrativas, así como de las Administradoras de Riesgos Laborales.', Marco_Legal = 'Ley 1562/2012 Artículo 13 Decreto 1072/2015 Artículo 2.2.4.11.7', Modo_Verificacion = 'Solicitar la evidencia documental de las acciones correctivas realizadas en respuesta a los requerimientos o recomendaciones de las autoridades administrativas, así como de las Administradoras de Riesgos Laborales.' WHERE Pk_Id_Criterio = 60