//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG_SST.GestposService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="paramObtenerLink", Namespace="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx")]
    [System.SerializableAttribute()]
    public partial class paramObtenerLink : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SG_SST.GestposService.modulo moduloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codi_usuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xml_paramsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SG_SST.GestposService.modulo modulo {
            get {
                return this.moduloField;
            }
            set {
                if ((this.moduloField.Equals(value) != true)) {
                    this.moduloField = value;
                    this.RaisePropertyChanged("modulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codi_usu {
            get {
                return this.codi_usuField;
            }
            set {
                if ((object.ReferenceEquals(this.codi_usuField, value) != true)) {
                    this.codi_usuField = value;
                    this.RaisePropertyChanged("codi_usu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xml_params {
            get {
                return this.xml_paramsField;
            }
            set {
                if ((object.ReferenceEquals(this.xml_paramsField, value) != true)) {
                    this.xml_paramsField = value;
                    this.RaisePropertyChanged("xml_params");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="modulo", Namespace="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx")]
    public enum modulo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        eval_plan_gestpos = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        furat_poscuida = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        furel_poscuida = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="rtaObtenerLink", Namespace="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx")]
    [System.SerializableAttribute()]
    public partial class rtaObtenerLink : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int validoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string url_sitioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int valido {
            get {
                return this.validoField;
            }
            set {
                if ((this.validoField.Equals(value) != true)) {
                    this.validoField = value;
                    this.RaisePropertyChanged("valido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string url_sitio {
            get {
                return this.url_sitioField;
            }
            set {
                if ((object.ReferenceEquals(this.url_sitioField, value) != true)) {
                    this.url_sitioField = value;
                    this.RaisePropertyChanged("url_sitio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="paramValidarLink", Namespace="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx")]
    [System.SerializableAttribute()]
    public partial class paramValidarLink : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xml_datosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string xml_datos {
            get {
                return this.xml_datosField;
            }
            set {
                if ((object.ReferenceEquals(this.xml_datosField, value) != true)) {
                    this.xml_datosField = value;
                    this.RaisePropertyChanged("xml_datos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="rtaValidarLink", Namespace="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx")]
    [System.SerializableAttribute()]
    public partial class rtaValidarLink : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int validoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xml_paramsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xml_configField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int valido {
            get {
                return this.validoField;
            }
            set {
                if ((this.validoField.Equals(value) != true)) {
                    this.validoField = value;
                    this.RaisePropertyChanged("valido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xml_params {
            get {
                return this.xml_paramsField;
            }
            set {
                if ((object.ReferenceEquals(this.xml_paramsField, value) != true)) {
                    this.xml_paramsField = value;
                    this.RaisePropertyChanged("xml_params");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string xml_config {
            get {
                return this.xml_configField;
            }
            set {
                if ((object.ReferenceEquals(this.xml_configField, value) != true)) {
                    this.xml_configField = value;
                    this.RaisePropertyChanged("xml_config");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx", ConfigurationName="GestposService.ws_loginSoap")]
    public interface ws_loginSoap {
        
        // CODEGEN: Generating message contract since element name param from namespace http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx/obtenerLink", ReplyAction="*")]
        SG_SST.GestposService.obtenerLinkResponse obtenerLink(SG_SST.GestposService.obtenerLinkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx/obtenerLink", ReplyAction="*")]
        System.Threading.Tasks.Task<SG_SST.GestposService.obtenerLinkResponse> obtenerLinkAsync(SG_SST.GestposService.obtenerLinkRequest request);
        
        // CODEGEN: Generating message contract since element name param from namespace http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx/validarLink", ReplyAction="*")]
        SG_SST.GestposService.validarLinkResponse validarLink(SG_SST.GestposService.validarLinkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx/validarLink", ReplyAction="*")]
        System.Threading.Tasks.Task<SG_SST.GestposService.validarLinkResponse> validarLinkAsync(SG_SST.GestposService.validarLinkRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerLinkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerLink", Namespace="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx", Order=0)]
        public SG_SST.GestposService.obtenerLinkRequestBody Body;
        
        public obtenerLinkRequest() {
        }
        
        public obtenerLinkRequest(SG_SST.GestposService.obtenerLinkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx")]
    public partial class obtenerLinkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SG_SST.GestposService.paramObtenerLink param;
        
        public obtenerLinkRequestBody() {
        }
        
        public obtenerLinkRequestBody(SG_SST.GestposService.paramObtenerLink param) {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerLinkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerLinkResponse", Namespace="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx", Order=0)]
        public SG_SST.GestposService.obtenerLinkResponseBody Body;
        
        public obtenerLinkResponse() {
        }
        
        public obtenerLinkResponse(SG_SST.GestposService.obtenerLinkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx")]
    public partial class obtenerLinkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SG_SST.GestposService.rtaObtenerLink obtenerLinkResult;
        
        public obtenerLinkResponseBody() {
        }
        
        public obtenerLinkResponseBody(SG_SST.GestposService.rtaObtenerLink obtenerLinkResult) {
            this.obtenerLinkResult = obtenerLinkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarLinkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarLink", Namespace="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx", Order=0)]
        public SG_SST.GestposService.validarLinkRequestBody Body;
        
        public validarLinkRequest() {
        }
        
        public validarLinkRequest(SG_SST.GestposService.validarLinkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx")]
    public partial class validarLinkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SG_SST.GestposService.paramValidarLink param;
        
        public validarLinkRequestBody() {
        }
        
        public validarLinkRequestBody(SG_SST.GestposService.paramValidarLink param) {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarLinkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarLinkResponse", Namespace="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx", Order=0)]
        public SG_SST.GestposService.validarLinkResponseBody Body;
        
        public validarLinkResponse() {
        }
        
        public validarLinkResponse(SG_SST.GestposService.validarLinkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.positivaenlinea.gov.co/ws_token/ws_login.asmx")]
    public partial class validarLinkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SG_SST.GestposService.rtaValidarLink validarLinkResult;
        
        public validarLinkResponseBody() {
        }
        
        public validarLinkResponseBody(SG_SST.GestposService.rtaValidarLink validarLinkResult) {
            this.validarLinkResult = validarLinkResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ws_loginSoapChannel : SG_SST.GestposService.ws_loginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ws_loginSoapClient : System.ServiceModel.ClientBase<SG_SST.GestposService.ws_loginSoap>, SG_SST.GestposService.ws_loginSoap {
        
        public ws_loginSoapClient() {
        }
        
        public ws_loginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ws_loginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_loginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_loginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SG_SST.GestposService.obtenerLinkResponse SG_SST.GestposService.ws_loginSoap.obtenerLink(SG_SST.GestposService.obtenerLinkRequest request) {
            return base.Channel.obtenerLink(request);
        }
        
        public SG_SST.GestposService.rtaObtenerLink obtenerLink(SG_SST.GestposService.paramObtenerLink param) {
            SG_SST.GestposService.obtenerLinkRequest inValue = new SG_SST.GestposService.obtenerLinkRequest();
            inValue.Body = new SG_SST.GestposService.obtenerLinkRequestBody();
            inValue.Body.param = param;
            SG_SST.GestposService.obtenerLinkResponse retVal = ((SG_SST.GestposService.ws_loginSoap)(this)).obtenerLink(inValue);
            return retVal.Body.obtenerLinkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SG_SST.GestposService.obtenerLinkResponse> SG_SST.GestposService.ws_loginSoap.obtenerLinkAsync(SG_SST.GestposService.obtenerLinkRequest request) {
            return base.Channel.obtenerLinkAsync(request);
        }
        
        public System.Threading.Tasks.Task<SG_SST.GestposService.obtenerLinkResponse> obtenerLinkAsync(SG_SST.GestposService.paramObtenerLink param) {
            SG_SST.GestposService.obtenerLinkRequest inValue = new SG_SST.GestposService.obtenerLinkRequest();
            inValue.Body = new SG_SST.GestposService.obtenerLinkRequestBody();
            inValue.Body.param = param;
            return ((SG_SST.GestposService.ws_loginSoap)(this)).obtenerLinkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SG_SST.GestposService.validarLinkResponse SG_SST.GestposService.ws_loginSoap.validarLink(SG_SST.GestposService.validarLinkRequest request) {
            return base.Channel.validarLink(request);
        }
        
        public SG_SST.GestposService.rtaValidarLink validarLink(SG_SST.GestposService.paramValidarLink param) {
            SG_SST.GestposService.validarLinkRequest inValue = new SG_SST.GestposService.validarLinkRequest();
            inValue.Body = new SG_SST.GestposService.validarLinkRequestBody();
            inValue.Body.param = param;
            SG_SST.GestposService.validarLinkResponse retVal = ((SG_SST.GestposService.ws_loginSoap)(this)).validarLink(inValue);
            return retVal.Body.validarLinkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SG_SST.GestposService.validarLinkResponse> SG_SST.GestposService.ws_loginSoap.validarLinkAsync(SG_SST.GestposService.validarLinkRequest request) {
            return base.Channel.validarLinkAsync(request);
        }
        
        public System.Threading.Tasks.Task<SG_SST.GestposService.validarLinkResponse> validarLinkAsync(SG_SST.GestposService.paramValidarLink param) {
            SG_SST.GestposService.validarLinkRequest inValue = new SG_SST.GestposService.validarLinkRequest();
            inValue.Body = new SG_SST.GestposService.validarLinkRequestBody();
            inValue.Body.param = param;
            return ((SG_SST.GestposService.ws_loginSoap)(this)).validarLinkAsync(inValue);
        }
    }
}
